ministryofjustice/opg-use-an-lpa

.circleci/config.yml, features/steps/viewer.py, service-viewer/app/test/AppTest/Handler/HomePageHandlerTest.php
- Added more commenting
- Standardised around `circleci/python` containers
- Split build job into one per container
- Added unit testing
- Amended job names so they can be easier read in CircleCI
- Parameterised ECR URLs
=> UML-75: Various CI config changes

.circleci/config.yml, docker-compose.yml, service-api/docker/app/Dockerfile, terraform_environment/shared_data_sources.tf, terraform_environment/viewer_ecs.tf
- Moved the existing front containers to use the new repo paths; front_web & front_app
- Added the build of the api_web & api_app containers into the pipeline
This PR doesn't include making use of those containers.
Unit test are not being run on the api_app yet as Zend hasn't been installed.
=> LPA-116: Added API container into pipeline

terraform_environment/actor_ecs.tf, terraform_environment/actor_load_balancer.tf, terraform_environment/api_ecs.tf, terraform_environment/dns.tf, terraform_environment/shared_data_sources.tf, terraform_shared/certificate.tf, terraform_shared/kms.tf
Adds:
- Actor ESC service
- Actor ALB
- Actor DNS record
- Actor TLS certificate 
- Actor sessions KMS key
- Ingress rule allowing Actor to talk to API on port 80
=> UML-137: Actor AWS Infrastructure

.circleci/config.yml, .gitignore, features/aws_ecs_task.py, terraform_environment/actor_ecs.tf, terraform_environment/api_ecs.tf, terraform_environment/outputs.tf, terraform_environment/viewer_ecs.tf
Introduce a wait for all three ecs services to stabilise before progressing the workflow
=> Wait for services

.circleci/config.yml
Use the -lock-timeout=300s argument on terraform init and apply commands to try to reduce the need for force-unlocks
=> Wait for state lock

.circleci/config.yml
Fixes bug where AWS cannot create resources with underscores in the name.
=> Allow underscores in branch names

features/ci_ingress.py
Update verify added so that it searches for rules rather than assumes an index position.
=> combine and improve verify steps

.circleci/config.yml, service-front/app/.gitignore, service-front/app/config/routes.php, service-front/app/phpunit.xml.dist, service-front/app/src/Actor/src/Form/Login.php, service-front/app/src/Actor/src/Handler/LoginPageHandler.php, service-front/app/src/Actor/templates/actor/create-account.html.twig, service-front/app/src/Actor/templates/actor/home-page.html.twig, service-front/app/src/Actor/templates/actor/login.html.twig, service-front/app/src/Common/src/Form/AbstractForm.php, service-front/app/src/Common/src/Service/ApiClient/ApiException.php, service-front/app/src/Common/src/View/Twig/GovUKZendFormErrorsExtension.php, service-front/app/src/Common/src/View/Twig/GovUKZendFormExtension.php, service-front/app/src/Common/templates/layout/default.html.twig, service-front/app/src/Common/templates/partials/govuk_error.html.twig, service-front/app/src/Common/templates/partials/govuk_form.html.twig, service-front/app/src/Viewer/templates/viewer/enter-code.html.twig, service-front/app/test/ActorTest/ConfigProviderTest.php, service-front/app/test/ActorTest/Handler/LoginPageHandlerTest.php, service-front/app/test/ViewerTest/Handler/CheckCodeHandlerTest.php
As a user (actor)
I want to enter my email and password
So that I can access my account
=> UML-158 Sign into account (Actor)

service-front/app/src/Common/src/Entity/User.php, service-front/app/src/Common/src/Exception/AbstractApiException.php, service-front/app/src/Common/src/Exception/ApiException.php, service-front/app/src/Common/src/Service/ApiClient/Client.php, service-front/app/src/Common/src/Service/User/UserService.php, service-front/app/src/Viewer/src/Handler/CheckCodeHandler.php, service-front/app/test/CommonTest/Service/User/UserServiceTest.php, service-front/app/test/ViewerTest/Handler/CheckCodeHandlerTest.php
Is based on the login form PR #96
=> UML-188 add auth service to frontend

.circleci/config.yml, service-api/app/phpunit.xml.dist
Would be better to bring this functionality in via a separate PR
=> Add CodeCov export and testing to build process.

service-front/app/src/Actor/src/Handler/LoginPageHandler.php, service-front/app/src/Actor/src/Handler/LpaAddHandler.php, service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Common/templates/partials/account-bar.html.twig, service-front/app/src/Common/templates/partials/new-service.html.twig, service-front/app/test/ActorTest/Handler/LoginPageHandlerTest.php, service-front/app/test/ActorTest/Handler/LpaAddHandlerTest.php
Add logout view partial to add-lpa page.
Depends on #107 (UML-190)
=> Uml 192 create view partial

service-front/app/config/routes.php, service-front/app/src/Actor/src/Handler/LogoutPageHandler.php, service-front/app/src/Common/src/Handler/SessionAware.php, service-front/app/src/Common/src/Handler/Traits/Session.php, service-front/app/src/Common/src/Service/Session/EncryptedCookiePersistence.php, service-front/app/test/ActorTest/Handler/LoginPageHandlerTest.php, service-front/app/test/ActorTest/Handler/LogoutPageHandlerTest.php
Depends on UML-201 #112 
Add logout handler and functionality around sessions.
=> Uml 193 logout

service-api/app/config/routes.php, service-api/app/src/App/src/DataAccess/DynamoDb/ActorUsers.php, service-api/app/src/App/src/DataAccess/DynamoDb/DynamoHydrateTrait.php, service-api/app/src/App/src/DataAccess/Repository/ActorUsersInterface.php, service-api/app/src/App/src/Handler/RequestPasswordResetHandler.php, service-api/app/src/App/src/Service/User/UserService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/ActorUsersTest.php, service-api/app/test/AppTest/Handler/RequestPasswordResetHandlerTest.php, service-api/app/test/AppTest/Service/User/UserServiceTest.php, service-front/app/config/routes.php, service-front/app/src/Actor/src/Form/PasswordReset.php, service-front/app/src/Actor/src/Handler/PasswordResetPageHandler.php, service-front/app/src/Actor/templates/actor/login.html.twig, service-front/app/src/Actor/templates/actor/password-reset-done.html.twig, service-front/app/src/Actor/templates/actor/password-reset.html.twig, service-front/app/src/Common/src/Service/Email/EmailClient.php, service-front/app/src/Common/src/Service/User/UserService.php, service-front/app/test/ActorTest/Handler/LoginPageHandlerTest.php, service-front/app/test/ActorTest/Handler/PasswordResetPageHandlerTest.php, service-front/app/test/CommonTest/Service/Email/EmailClientTest.php, service-front/app/test/CommonTest/Service/User/UserServiceTest.php
This is based on the work of UML 158 so will be merged after. It consequently lists as quite large but will shrink considerably when that one goes in.
=> Uml 164 password reset

scripts/generate_actor_codes.py, service-api/app/composer.json, service-api/app/composer.lock, service-api/app/config/autoload/console.global.php, service-api/app/console.php, service-api/app/src/App/src/Command/ActorCodeCreationCommand.php, service-api/app/src/App/src/Command/ActorCodeCreationCommandFactory.php, terraform/environment/code_creation_ecs.tf
A big and horrible single class cli command function that can create actor codes for lpa's that are passed in.
Takes a comma separated list of lpa uids and spits out a bunch of JSON telling you of codes created for actors. 
It *does not* create any codes for actors that exist already. But *may* create codes for other 'new' actors on an LPA.
=> Uml 264 creation of actor codes from lpa uids

pdf/app/package-lock.json, pdf/app/package.json, pdf/app/src/app.js, pdf/app/src/app.test.js, pdf/app/src/lib/generatePdf.js, pdf/app/src/lib/generatePdf.test.js, pdf/app/src/lib/htmlToPdf.js, pdf/app/src/lib/htmlToPdf.test.js, pdf/app/src/lib/stripAnchorTags.test.js, pdf/app/src/server.js, pdf/docker/app/Dockerfile
Added 100% coverage to new PDF Service. Split app.js into 2 files to make it easier to test and maintain.
=> Uml 312 unit tests

docker-compose.yml, zap/Dockerfile, zap/readme.md, zap/scripts/actor.sh, zap/scripts/viewer.sh
So that you can locally test the app for known security issues.
Initial proof of concept for local use that can be integrated into the pipeline with later work.
=> OWASP ZAP container

service-front/web/README.md, service-pdf/app/README.md
Added 2 readmes to recent work done on the PDF Service and the web project
=> Uml 327 pdf documentation

service-api/app/src/App/src/DataAccess/DynamoDb/ActorUsers.php, service-api/app/test/AppTest/DataAccess/DynamoDb/ActorUsersTest.php
=> Ensure we remove the actor record ttl when activating an account

service-api/app/composer.json, service-api/app/composer.lock, service-api/app/features/bootstrap/app.php, service-api/app/test/AppTest/Service/ActorCodes/ActorCodeServiceTest.php, service-front/app/composer.json, service-front/app/composer.lock, service-front/app/features/bootstrap/app.php, service-front/app/features/context/Integration/AccountContext.php, service-front/app/features/context/UI/AccountContext.php, service-front/app/test/CommonTest/Service/Email/EmailClientFactoryTest.php
I have pushed necessary changes upstream (https://github.com/alphagov/notifications-php-client/pull/70)
=> UML 282 Move Notify library to a MoJ port.

.pre-commit-config.yaml, docs/pull_request_template.md, docs/runbooks/pre_commit.md
The team have agreed that we can improve pull requests and ensure we've completed all the requirements from our definition of done with a pull request template.
Fixes UML-480
Add a pr template file to our docs.
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
=> add PR template

service-api/app/features/context/Acceptance/AccountContext.php, service-api/app/features/context/Integration/AccountContext.php, service-front/app/features/context/UI/AccountContext.php
=> Added last login value in api response, also fixed test on ui front

service-api/app/behat.yml, service-api/app/features/context/Acceptance/ViewerContext.php, service-api/app/features/context/BaseAcceptanceContextTrait.php, service-api/app/features/context/Integration/BaseIntegrationContext.php, service-api/app/features/context/Integration/ViewerContext.php, service-api/app/features/view-lpa-using-sharecode.feature, service-api/app/src/App/src/Handler/ViewerCodeFullHandler.php, service-api/app/src/App/src/Handler/ViewerCodeSummaryHandler.php, service-front/app/composer.json, service-front/app/composer.lock, service-front/app/features/context/Integration/ViewerContext.php, service-front/app/features/context/UI/ViewerContext.php, service-front/app/features/view-lpa-using-sharecode.feature, service-front/app/src/Viewer/src/Handler/CheckCodeHandler.php
Feature test improvements around cancelled LPA viewing. Also added feature tests for the API side of viewer functionality
Fixes UML-571
=> Uml 571 viewing a cancelled lpa

service-front/app/features/actor-add-an-lpa.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Form/LpaAdd.php, service-front/app/src/Actor/templates/actor/check-lpa.html.twig, service-front/app/src/Actor/templates/actor/lpa-blank-dashboard.html.twig, service-front/app/src/Actor/templates/actor/your-details.html.twig
Minor content changes
Content changes to correct grammar and passive language
=> UML-524 content changes for grammar and consistency

.circleci/config.yml
The run of the pipeline against master failed due to dependencies on building an environment.
Fixes UML-540
add an entry for the job for development branches and master branch, including filtering branches.
=> run ecr scan results after preprod env build

docker-compose.yml, docs/architecture/decisions/0016-logging-and-tracing.md, service-api/app/composer.json, service-api/app/composer.lock, service-api/app/config/autoload/monolog.global.php, service-front/app/composer.lock, service-front/app/config/autoload/monolog.global.php
Implements the logging as JSON so that cloudwatch can interrogate it better. Also set a default log level and set a development log level of DEBUG.
Added ADR describing logging
Mostly config
=> Json logging

service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/templates/actor/login.html.twig, service-front/web/package-lock.json
Small content change to the sign in page to inform users that even if they have an account for the LPA service, they will still need to create a new account for the use an LPA service
Fixes UML-627
Made small content changes for sign in page, and updated the actor UI behat tests to click the button named 'Sign in' now rather than 'Continue'
=> sign in page content changes and updates to relevant behat tests

.gitignore, .idea/.gitignore, .idea/codeStyles/codeStyleConfig.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/misc.xml, .idea/modules.xml, .idea/opg-use-an-lpa.iml, .idea/php-test-framework.xml, .idea/php.xml, .idea/runConfigurations/API.xml, .idea/runConfigurations/API_Acceptance.xml, .idea/runConfigurations/API_Integration.xml, .idea/runConfigurations/All_tests.xml, .idea/runConfigurations/Behat___API.xml, .idea/runConfigurations/Behat___Front.xml, .idea/runConfigurations/Front.xml, .idea/runConfigurations/Front_Integration.xml, .idea/runConfigurations/Front_UI.xml, .idea/runConfigurations/PHPUnit.xml, .idea/runConfigurations/opg_use_an_lpa.xml, .idea/vcs.xml
Brings project run configs into source control
This will break your current PHPStorm config without appropriate preparation. 
* Exit PHPStorm
* Backup current run folder  
`mv .idea .idea-bak`
* Checkout master/branch
* Start PHPStorm
* Remove backup (optional)  
`rm -R .idea-bak`
=> Add project run configuration

service-api/app/composer.lock, service-front/app/composer.lock, service-front/app/features/actor-account-creation.feature, service-front/app/features/actor-login.feature, service-front/app/features/actor-password-reset.feature, service-front/app/features/context/Integration/AccountContext.php, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Form/CreateAccount.php, service-front/app/src/Actor/src/Form/Login.php, service-front/app/src/Actor/src/Form/PasswordResetRequest.php, service-front/app/src/Actor/src/Handler/PasswordResetRequestPageHandler.php, service-front/app/src/Common/src/Service/User/UserService.php, service-front/web/package-lock.json
Ticket is make email address case in sensitive  when creating an account, logging in and resetting password
Fixes UML-600
Added filters and feature tests
=> changes to make the email field case insensitive and tests added

service-front/app/features/actor-change-details.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/templates/actor/change-details.html.twig
Update the change details page with new content and email link
Fixes UML-515
- Changed content to match the new prototype: 
https://opg-lpa-prototype-v2.herokuapp.com/use-lpa/V18/change-lpa
- Added feature test for accessing the change details page from the full lpa
=> Update change details page

service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php, service-api/app/test/AppTest/Service/ActorCodes/ActorCodeServiceTest.php
Log failures when validating a code to add to an LPA so problems can be debugged/monitored/etc.
Fixes [UML-603](https://opgtransform.atlassian.net/browse/UML-603)
It adds logging. Maybe it is too defensive?
=> Log reasons validation of code details failed

service-front/app/features/actor-create-access-code.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/templates/actor/lpa-create-viewercode.html.twig, service-front/app/src/Common/templates/partials/govuk_form.html.twig, service-front/web/package-lock.json
Added text to the create access code page to give users information/examples of the organisation to enter
Fixes UML-403
Updated content to show the correct organisation information based on LPA type. Also added to. existing feature test to check correct text is shown
=> Updated create code page and added new info to feature test

service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodesTest.php
tests the cancel() function for the ViewerCodes class
Fixes UML-607
Tests that the function contains the correct data and keys, as well as asserting that the correct response `true` is returned
=> added unit test for the cancel() function

terraform/account/elasticache.tf
Introduce elasticache to the project to handle the brute force protection store
New terraform configuration to setup the cache. Permissions onto the cache will be dealt with by the main PR.
=> Add elasticache terraform configuration

.circleci/config.yml, docker-compose.yml, service-api/docker/seeding/Dockerfile, service-api/seeding/dynamodb.py, service-api/seeding/requirements.txt, terraform/environment/config_file.tf
Seeds a test user account into the database to save dev's having to create a new account each time they bring up the containers
=> edited python script to seed test user into database

service-api/app/test/AppTest/Service/Log/RequestTracingLogProcessorFactoryTest.php, service-api/app/test/AppTest/Service/Log/RequestTracingLogProcessorTest.php, service-front/app/test/CommonTest/Service/Log/RequestTracingLogProcessorFactoryTest.php, service-front/app/test/CommonTest/Service/Log/RequestTracingLogProcessorTest.php
Add test coverage for RequestTracingLogProcessor and RequestTracingLogProcessorFactory.
Fixes UML-612 / UML-613
I wrote tests! 
=> UML-612/3 Add tests for RequestTracingLogProcessor/Factory

.circleci/config.yml, pipeline_scripts/check_ecr_scan_results/README.md, pipeline_scripts/check_ecr_scan_results/aws_ecr_scan_results.py
The ecr_scan_results script would only return the first finding, and if there were no findings at all, post an empty message to slack.
Bring the improvements of this script made on opg-lpa into this project.
=> iterate over all findings and report

docs/architecture/decisions/0018-session-lifetime-and-session-based-cookies.md
Add ADR document for session cookie lifetime
Fixes UML-637
=> UML-637 Add an ADR document for the session cookie decision.

service-api/app/test/AppTest/Service/ApiClient/ClientFactoryTest.php, service-front/web/package-lock.json
Increases test coverage by writing tests for all paths for the api ClientFactory class
Fixes UML-610
Created 3 tests, happy path and 2 tests where exceptions are thrown if there is certain missing configuration
=> UML-610 - Api tests for client factory

docs/runbooks/logs/searching_logs.md
I created a little guide on searching the logs, with a few handy filter snippets
=> created a guide for searching logs

terraform/environment/actor_load_balancer.tf, terraform/environment/viewer_load_balancer.tf
Remove ITHC ingress from preproduction
Fixes UML-772
Remove the ingress rules from the actor and viewer load balancers.
=> remove ithc ingress

.circleci/config.yml, scripts/pipeline/workspace_cleanup/workspace_cleanup.sh
Start automatically cleaning up workspaces.
Fixes UML-808
Add the destroy and workspace delete commands to the workspace cleanup job
Remove hold and workspace destroy steps from pipeline
Remove destroy job code from CircleCI config
=> UML-808 - Start cleaning up workspace

.circleci/config.yml
The pipeline is returning errors not produced locally.
Fixes UML-811
Update the version of node being used on the pipeline
Try using CircleCI's new convenience images.
https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/
=> try new circleci images

service-front/app/src/Actor/templates/actor/lpa-create-viewercode.html.twig
To let users know which organisations are part of the trial
https://opgtransform.atlassian.net/secure/RapidBoard.jspa?rapidView=149&modal=detail&selectedIssue=UML-810
Fixes UML-810
Added extra paragraph into lpa-create-viewercode.html.twig
=> add trial sentence to lpa-create-viewercode.html.twig

service-front/app/config/autoload/envs.global.php, service-front/app/features/bootstrap/behat.config.php, service-front/app/src/Actor/src/ConfigProvider.php, service-front/app/src/Actor/src/Handler/CheckLpaHandler.php, service-front/app/src/Actor/src/Handler/Factory/CheckLpaHandlerFactory.php
To add the brute force rate limiter to Checking LPA Actor Codes.
Fixes UML-297
- Take existing pattern for brute force limiting as per Viewer Codes
- Implement this in Check LPA Actor Codes handler.
- How the Brute force protection works from a previous PR: #273
=> added brute force to actor code check

service-api/app/config/autoload/features.global.php, service-api/app/features/bootstrap/behat.config.php, service-api/app/src/App/src/ConfigProvider.php, service-api/app/src/App/src/Service/ActorCodes/CodeValidationStrategyFactory.php, service-api/app/test/AppTest/Service/ActorCodes/CodeValidationStrategyFactoryTest.php
Add a feature flag configuration value and factory for the Codes service
Fixes UML-818
Add in factory class and configure using  ConfigProvider to be used as the source for the newly abstracted interface
=> Uml 818 feature flag switching

service-front/app/config/autoload/envs.global.php, service-front/app/features/bootstrap/behat.config.php, service-front/app/src/Actor/src/ConfigProvider.php, service-front/app/src/Actor/src/Handler/Factory/LoginPageHandlerFactory.php, service-front/app/src/Actor/src/Handler/LoginPageHandler.php
https://opgtransform.atlassian.net/browse/UML-295
Fixes UML-295
- Take existing pattern for brute force as per Actor Codes
- Implement this in Login page handler.
- How the Brute force protection works from a previous PR: #273
=> UML-295 Added brute force to actor login

.idea/php.xml, .idea/runConfigurations/opg_use_an_lpa.xml, README.md, docker-compose.dependencies.yml, docker-compose.testing.yml, docker-compose.yml, service-api/app/composer.json, service-api/docker/seeding/Dockerfile, service-api/docker/seeding/start.sh, service-front/app/composer.json
Integrate application with new codes service
- Altered environment for easy upping
=> UML-819 Get environments up and running together

codecov.yml
set exact target with initial 5% drop leniency. we can adjust this later once more confident.
Relates to UML-431
adjust codecov.yml
=> set to 80% with 1% leniency above that level

service-api/app/config/autoload/envs.global.php, service-api/app/src/App/src/ConfigProvider.php, service-api/app/src/App/src/DataAccess/ApiGateway/RequestSigner.php, service-api/app/src/App/src/DataAccess/ApiGateway/RequestSignerFactory.php, service-api/app/test/AppTest/DataAccess/ApiGateway/RequestSignerFactoryTest.php, service-api/app/test/AppTest/DataAccess/ApiGateway/RequestSignerTest.php
Small service class ready to use for signing requests for the codes api service and associated configuration.
(currently sans tests)
=> Uml 819 request signing

service-front/web/package-lock.json
we need to re-check in the package lock.
Fixes master branch
npm i && npm audit && npm audit fix
=> fix erroneous package lock file missing

scripts/generate_actor_codes/README.md, scripts/generate_actor_codes/generate_actor_codes.sh, scripts/generate_actor_codes/requirements.txt
- To call the API gateway to check if an LPA exists prior to code-gen.
- To fix an issue with trailing empty lines in a file.
Fixes issues with hunting down failed LPA id's
- Add additional calls and logic to check that an LPA exists using an existing python script
- with aborts on fail to find.
- fix the trailing empty line issue
- some prettifying
- contains comparison in bash: https://stackoverflow.com/questions/4277665/how-do-i-compare-two-string-variables-in-an-if-statement-in-bash
- loop through a comma separated var: https://stackoverflow.com/questions/27702452/loop-through-a-comma-separated-shell-variable
- remove excess empty lines on end of file: https://unix.stackexchange.com/questions/81685/how-to-remove-multiple-newlines-at-eof
=> updated to add validation of LPA prior to codegen.

terraform/environment/terraform.tfvars.json
Enable lpa-codes on production
Fixes UML-914
Set the flag use_legacy_codes_service to false
=> Uml 914 production

service-front/app/src/Common/templates/layout/default.html.twig, service-front/app/src/Common/templates/partials/session-dialog.html.twig, service-front/web/package-lock.json, service-front/web/package.json, service-front/web/src/index.js, service-front/web/src/javascript/countdownTimer.js, service-front/web/src/javascript/countdownTimer.test.js, service-front/web/src/javascript/dialog.js, service-front/web/src/javascript/googleAnalytics.test.js, service-front/web/src/javascript/sessionDialog.js, service-front/web/src/javascript/sessionDialog.test.js, service-front/web/src/scss/_lpa-dialog.scss, service-front/web/src/scss/_lpa-typography.scss, service-front/web/src/scss/lpa.scss
Creates a dialog box in JS ready for the implementation of the session timeout. 
Fixes UML-881
Adds in a timeout and a dialog for when when a session is about to expire.
Cannot test key pressses in JSDom which means our testing is a little short on the JS. One to investigate in the future or cover via Behat in the future.
=> Uml 881 expire dialog

service-front/web/package-lock.json, service-front/web/package.json, service-front/web/src/javascript/googleAnalytics.js
Adds performance and error capturing and send to Google Analytics
Fixes UML-931
Uses the OGP performance library [https://www.npmjs.com/package/@ministryofjustice/opg-performance-analytics](https://www.npmjs.com/package/@ministryofjustice/opg-performance-analytics) to collect data and send to the existing GA integration.
=> Uml 931 perf analytics

service-front/app/src/Actor/templates/actor/check-lpa.html.twig, service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Actor/templates/actor/lpa-not-found.html.twig
to align the time and content to be consistent for opening times. 
Fixes UML-929
twig changes
N/A
=> Uml 929 fix content for opening times

.circleci/config.yml
Reduce CircleCI costs.
Fixes UML-967
Set a resource class of small for some executors
https://circleci.com/docs/2.0/configuration-reference/#executors-requires-version-21
https://circleci.com/docs/2.0/configuration-reference/#resource_class
https://circleci.com/docs/2.0/optimizations/
=> UML-967 - Reduce CircleCI costs

scripts/count_lpas/README.md, scripts/count_lpas/countLPAs
_UML-942 a script to count LPAs added in a certain date range_
_Use the aws cli to do a DynamoDB scan, pipe into sort and uniq to remove duplicates_
=> script to count LPAs

scripts/count_lpas/README.md, scripts/count_lpas/countLPAs
Answer some extra questions about the use of the UaL service.
Extend the countLPAs script with functions to count different fields.
=> add counts of viewer codes created and viewed to stats script

terraform/account/cloudwatch_alarms.tf
Changes monitor level threshold from 50b to 50 MB
=> Updated value from 50b to 50Mb

service-front/app/src/Actor/templates/actor/actor-privacy-notice.html.twig, service-front/app/src/Actor/templates/actor/check-access-codes.html.twig, service-front/app/src/Actor/templates/actor/lpa-create-viewercode.html.twig, service-front/app/src/Actor/templates/actor/lpa-show-viewercode.html.twig, service-front/app/src/Actor/templates/actor/stats-page.html.twig, service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig, service-front/app/src/Common/templates/partials/cookies.html.twig
Prevent duplication of h1 tags and make sure other heading levels are not skipped.
Fixes UML-685
=> correct heading hierarchy throughout service

.circleci/config.yml
Fixes the build issue by updating the package cache before installing python
=> Update package cache before installing things

service-front/app/src/Common/src/Service/Security/UserIdentificationService.php, service-front/app/test/CommonTest/Service/Security/UserIdentificationServiceTest.php
=> Add logging to user identity creation to help figure out why our identities are all identical.

scripts/count_lpas/README.md, scripts/count_lpas/countLPAs
Count the number of Actor accounts created between a date range
Add function to pull metric filter statistics from AWS Cloudwatch and use jq to add the Sum statistic of each data point.
https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/get-metric-statistics.html
Reduce section of the JQ manual
https://stedolan.github.io/jq/manual/v1.4/#Advancedfeatures
=> add function to count accounts created on actor side

.circleci/config.yml
=> pin terraform to version 12

service-front/app/src/Actor/templates/actor/create-account.html.twig, service-front/app/src/Actor/templates/actor/login.html.twig, service-front/app/src/Actor/templates/actor/your-details.html.twig
https://opgtransform.atlassian.net/browse/UML-367
Fixes UML-367
=> UML:367 Expanded the email fielddset width

service-front/app/composer.json, service-front/app/composer.lock, service-front/app/config/pipeline.php, service-front/app/features/actor-add-an-lpa.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Handler/CheckLpaHandler.php, service-front/app/src/Actor/src/Handler/LpaDashboardHandler.php, service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig, service-front/app/src/Actor/templates/actor/partials/flash-message.html.twig, service-front/web/src/scss/_lpa-flash-message.scss, service-front/web/src/scss/lpa.scss
Displays a flash message on the dashboard page after the user has added an LPA
Fixes UML-292
Installed and included mezzio flash middleware. Added the donor's full name and lpa type to the session so that it can be used in the post request to complete the adding of the lpa. The flash message is set the check lpa handler on POST request before the user is redirected to the dashboard page. The dashboard page handler takes the flash object and passes it to the twig template where the message is rendered if the flash message key is set
Also refactored the CheckLpaHandler, splitting the get and post requests into separate handle functions
=> Uml-292 Added lpa flash message (2)

service-front/app/src/Actor/templates/actor/check-lpa.html.twig, service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Actor/templates/actor/lpa-blank-dashboard.html.twig, service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig, service-front/app/src/Actor/templates/actor/lpa-not-found.html.twig, service-front/app/src/Actor/templates/actor/partials/new-use-service.html.twig, service-front/app/src/Common/templates/partials/account-bar.html.twig
https://opgtransform.atlassian.net/browse/UML-1041
Fixes UML-1041
=> Uml 1041 - page templates

.circleci/config.yml, docker-compose.yml, service-api/seeding/dynamodb.py, terraform/environment/config_file.tf
Seeds 2 lpa's into the test user's account to save dev's and PM's from having to generate a letter in sirius to add an LPA for UAT.
=> Seeding added lpas

service-front/app/src/Actor/templates/actor/email-reset-not-found.html.twig, service-front/app/src/Actor/templates/actor/instructions-preferences.html.twig, service-front/app/src/Actor/templates/actor/password-change.html.twig, service-front/app/src/Actor/templates/actor/password-reset-not-found.html.twig, service-front/app/src/Actor/templates/actor/password-reset.html.twig, service-front/app/src/Actor/templates/actor/request-email-change-success.html.twig
https://opgtransform.atlassian.net/browse/UML-1053
Fixes UML-1053
=> UML-1053: Added tag for templates

service-front/app/src/Common/templates/error/404.html.twig, service-front/app/src/Common/templates/error/error.html.twig, service-front/app/src/Common/templates/error/session-timeout.html.twig, service-front/app/src/Common/templates/layout/default.html.twig, service-front/app/src/Common/templates/partials/session-dialog.html.twig
https://opgtransform.atlassian.net/browse/UML-1052
Fixes UML-1052
=> UML 1052: Added tag for templates

service-front/app/languages/en_GB.pot, service-front/app/src/Actor/templates/actor/activate-account-not-found.html.twig, service-front/app/src/Actor/templates/actor/activate-account.html.twig, service-front/app/src/Actor/templates/actor/password-reset-request-done.html.twig, service-front/app/src/Actor/templates/actor/password-reset-request.html.twig
Fixes UML-1040
https://opgtransform.atlassian.net/browse/UML-1040?atlOrigin=eyJpIjoiYjRhMWMxMzdkYzc1NGRlNGFmYTVlYWEyODU0OGJhYzciLCJwIjoiaiJ9 
=> Uml 1040 list4

service-front/app/src/Actor/templates/actor/check-access-codes.html.twig, service-front/app/src/Actor/templates/actor/confirm-cancel-code.html.twig, service-front/app/src/Actor/templates/actor/lpa-create-viewercode.html.twig, service-front/app/src/Actor/templates/actor/lpa-removed.html.twig, service-front/app/src/Actor/templates/actor/lpa-show-viewercode.html.twig, service-front/app/src/Actor/templates/actor/partials/cancel-code-option.html.twig, service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig, service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig
https://opgtransform.atlassian.net/browse/UML-1051
Fixes UML-1051
=> UML-1051 Translation tags added for few more templates

service-front/app/src/Actor/templates/actor/change-details.html.twig, service-front/app/src/Actor/templates/actor/death-notification.html.twig, service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig, service-front/app/src/Actor/templates/actor/partials/lpa-sub-navigation.html.twig, service-front/app/src/Actor/templates/actor/your-details.html.twig
https://opgtransform.atlassian.net/browse/UML-1048
Fixes UML-1048
=> Uml 1048 - Translation tag added for few more templates

terraform/environment/actor_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/pdf_ecs.tf, terraform/environment/viewer_ecs.tf
=> scale back down

tests/features/welsh-translations-are-working.feature, tests/smoke/context/CommonContext.php
Add smoke test to verify that the Welsh language files are loaded and presented correctly.
=> Add smoke test for Welsh language availability

service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Common/templates/partials/govuk_form.html.twig
https://opgtransform.atlassian.net/browse/UML-687
Fixes UML-687
=> UML-687: Changes to add numeric type to reference and date field

service-front/app/features/actor-check-access-codes.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/templates/actor/check-access-codes.html.twig, service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
https://opgtransform.atlassian.net/browse/UML-1064
Fixes UML-1064
=> UML-1064: Removed inactive code duplication

service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Common/templates/partials/govuk_form.html.twig
https://opgtransform.atlassian.net/browse/UML-1096
Fixes UML-1096
=> UML-1096:Bug fix to avoid firefox overriding custom validation with its own

service-front/app/src/Actor/templates/actor/check-access-codes.html.twig, service-front/app/src/Common/templates/partials/govuk_error.html.twig
https://opgtransform.atlassian.net/browse/UML-840
Fixes UML-840
=> Uml 840: Minor dac changes applied

service-api/app/features/actor-access-code-cancellation.feature, service-api/app/features/actor-check-access-codes.feature, service-api/app/features/context/Acceptance/LpaContext.php, service-api/app/features/context/Integration/LpaContext.php, service-api/app/src/App/src/DataAccess/DynamoDb/ViewerCodes.php, service-api/app/src/App/src/DataAccess/Repository/ViewerCodesInterface.php, service-api/app/src/App/src/Handler/LpasResourceCodesCollectionHandler.php, service-api/app/src/App/src/Service/ViewerCodes/ViewerCodeService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodesTest.php, service-api/app/test/AppTest/Service/ViewerCodes/ViewerCodeServiceTest.php, service-front/app/src/Actor/src/Handler/CheckAccessCodesHandler.php
https://opgtransform.atlassian.net/browse/UML-1086
Fixes UML-1086
=> UML - 1086 : Show all access codes generated by co-actors in check access code page

service-api/app/features/actor-access-code-cancellation.feature, service-api/app/features/actor-check-access-codes.feature, service-api/app/features/context/Acceptance/LpaContext.php, service-api/app/features/context/Integration/LpaContext.php, service-api/app/src/App/src/DataAccess/DynamoDb/ViewerCodes.php, service-api/app/src/App/src/DataAccess/Repository/ViewerCodesInterface.php, service-api/app/src/App/src/Handler/LpasResourceCodesCollectionHandler.php, service-api/app/src/App/src/Service/ViewerCodes/ViewerCodeService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodesTest.php, service-api/app/test/AppTest/Service/ViewerCodes/ViewerCodeServiceTest.php, service-front/app/src/Actor/src/Handler/CheckAccessCodesHandler.php
Reverts ministryofjustice/opg-use-an-lpa#585
=> Revert "UML - 1086 : Show all access codes generated by co-actors in check access code page"

service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile
2 Notices for CVEs
Fixes UML-1109
Use next version of alpine and upgrade curl
=> Upgrade Curl

terraform/environment/resource_group.tf
Create a resource group for each environment that can be used in cost explorer and/or identify straggling resources.
Fixes UML-1120
Create a resource group defined by the environment-name tag
=> UML-1120 - Create resource groups for each environment

terraform/account/autoscaling_role.tf
create an autoscaling role for ecs autoscaling
Fixes UML-486
=> UML-486 - Create account level autoscaling role

.gitignore, scripts/analysis_scripts/get_organisation_names.py
Export organisation names for data analysis.
Fixes UML-1178
Paginating scan operations to get all items
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Paginator.Scan
https://alexwlchan.net/2020/05/getting-every-item-from-a-dynamodb-table-with-python/
=> UML-1178 Get all organisation names and output to csv

scripts/analysis_scripts/lookup_account.py
PM and UR want to be able to help with customer queries and look up account details so they can do so.
Fixes UML-1188
Scan, filter and get items.
=> add script to lookup account by email address

terraform/account/vpc_flowlogs.tf
Create VPC Flow Logs
Fixes UML-1204
=> create vpc flow logs for default vpc

terraform/environment/backup_plan.tf
update backup plan to meet the minimum of 90.
Fixes UML-1208
=> UML-1208 - Fix backup plans for production

scripts/analysis_scripts/lookup_account.py
Add the activation status to the output of the script.
Set a default of value of activated and update if an ActivationToken exists in the ActorUser record.
=> Update account lookup script

service-front/app/features/actor-add-lpa-triage.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig, service-front/app/src/Common/src/View/Twig/GovUKLaminasFormExtension.php, service-front/app/src/Common/templates/partials/govuk_form.html.twig
https://opgtransform.atlassian.net/browse/UML-1157
Fixes UML-1157
=> UML 1157: Added conditional text explaining based on radio bution option chosen

.circleci/config.yml, terraform/environment/dns.tf
Keep the demo environment infrastructure up to date.
Fixes UML-1233
perform a terraform apply for the demo workspace
handle using the latest image tag
removed outdated private beta URLs from terraform outputs
=> UML-1233 Keep demo environment up to date

.github/dependabot.yml
Keep packages (npm and composer) up to date.
Fixes UML-1250
See if we can use Dependabot to manage package version updates as well as security updates.
https://docs.github.com/en/github/administering-a-repository/about-dependabot-version-updates
=> UML-1250 - Keep NPM and Composer packages up to date.

.github/dependabot.yml
The directory attribute didn't require the name of the manifest file
Fixes UML-1250
remove the filename from these attributes and add updates for the smoke test composer.json file.
=> UML-1250 - Fix directory attribute in dependabot.yml

service-api/docker/app/Dockerfile
```
Problem 1
- Root composer.json requires php ^7.1 but your php version (8.0.1) does not satisfy that requirement.
Problem 2
- elie29/zend-phpdi-config is locked to version v3.0.12 and an update of this package was not requested.
- elie29/zend-phpdi-config v3.0.12 requires php ^7.1 -> your php version (8.0.1) does not satisfy that requirement.
Problem 3
- paragonie/random_compat is locked to version v9.99.99 and an update of this package was not requested.
- paragonie/random_compat v9.99.99 requires php ^7 -> your php version (8.0.1) does not satisfy that requirement.
Problem 4
- php-http/guzzle6-adapter is locked to version v2.0.1 and an update of this package was not requested.
- php-http/guzzle6-adapter v2.0.1 requires php ^7.1 -> your php version (8.0.1) does not satisfy that …
```
=> UML-1263 - Pin composer version of api-app to address version constraints issues

.idea/inspectionProfiles/Project_Default.xml, service-api/app/composer.json, service-api/app/composer.lock, service-front/app/composer.lock, service-front/app/test/CommonTest/Service/User/UserServiceTest.php, tests/smoke/composer.lock
Update all the composer.lock files. Should fix all the dependabot PRs
`composer update`
=> Update all the PHP dependencies

service-pdf/app/package-lock.json, service-pdf/app/package.json
Reverted back to previously stable puppeteer version
Fixes UML-1287
Rolled back to previous version
=> Reverted back to previously stable puppeteer version

terraform/environment/api_ecs.tf
Allows access to api endpoint needed by older lpa feature
Split out of #698
=> Update terraform with appropriate permissions for codes service - split from 1161

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/misc.xml, .idea/runConfigurations/Front_UI.xml, Makefile, service-front/app/composer.json
Splitting up big PRs into smaller ones
Pulled out all IDE configuration changes from #678
=> Ide configuration updates - split out of 1163

service-api/app/src/App/src/Service/Log/EventCodes.php, service-api/app/src/App/src/Service/Lpa/GetAttorneyStatus.php, service-api/app/src/App/src/Service/Lpa/OlderLpaService.php, service-api/app/src/App/src/Service/Lpa/ValidateOlderLpaRequirements.php, service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php, service-api/app/test/AppTest/Service/Lpa/ValidateOlderLpaRequirementsTest.php
This PR breaks out the validation of LPA requirements necessary for the addition of older LPAs.
Move method into it's own class and amend calling code/tests appropriately
=> Continue refactor work of API side LPA service classes

service-front/app/languages/messages.pot
Update the translations POT file ready for new translations
Fixes UML-1199
=> New extract of translatables from templates

docker-compose.yml
https://opgtransform.atlassian.net/browse/UML-1313
Fixes UML-1313
=> UML-1313: Updated docker compose file to use right image version for front and api

service-front/app/config/routes.php, service-front/app/features/actor-add-lpa-triage.feature, service-front/app/features/context/UI/LpaContext.php, service-front/app/languages/messages.pot, service-front/app/src/Actor/src/Handler/AddLpaTriageHandler.php, service-front/app/src/Actor/src/Handler/RequestActivationKeyInfoHandler.php, service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig, service-front/app/src/Actor/templates/actor/request-activation-key-info.html.twig
Insert information page about the addition of older lpas by requesting an activation key
Fixes UML-1248
=> UML-1248 additional activation key information

.circleci/config.yml
Build a master version of the lambda function images on the path to live
Fixes UML-1322
Include jobs
=> UML-1321 - Fix Path to Live 

service-api/app/src/App/src/Service/Lpa/OlderLpaService.php, service-front/app/src/Common/src/Service/Log/EventCodes.php, service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
https://opgtransform.atlassian.net/browse/UML-1337
Fixes UML-1337
=> UML-1337: event codes renamed

.circleci/config.yml
**_As a developer
I want to run Dependabot package update on a lightweight workflow
So they are not so disruptive or costly_**
Fixes UML-1377
Modify the dependabot PR workflow to remove real infra jobs
Modify the dependabot PR workflow to remove lambda function build jobs
Create a new job called `end_of_workflow` to give a common ending to dependabot and PR Build workflows (required in branch protection)
https://circleci.com/docs/2.0/configuration-reference/
=> UML-1377 - don't provision or smoke test an environment for dependabot PRs

.github/workflows/codeql-analysis.yml
Enable static analysis of go, python and javascript with Code QL
Create codeql-analysis.yml
=> Enable Github CodeQL Action

service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig, service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig, service-front/web/src/scss/_lpa-inactive-notice.scss
Reverts ministryofjustice/opg-use-an-lpa#817
=> Revert "UML-1200: Changes to dashboard appearance"

.circleci/config.yml
Remove unused jobs from pipelines
Fixes UML-1398
remove the coveralls jobs and definition from .circleci.yaml file.
N/A
=> UML-1398 - Remove Coveralls tasks from pipelines

terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json
Feature toggle building and deploying admin app resources
Fixes UML-1406
add a tfvar for build_admin to be used for all admin resources
=> UML-406 - Feature toggle admin app resources

terraform/account/certificate.tf
Create certificates for admin app service
Fixes UML-1430
- Create a certificate for an internal use domain
- Create DNS records for validation
- Validate certificates with DNS records
- Create wildcard certificates to be shared on non-production environments
- Create a certificate for admin on production (no wildcard)
=> UML-1430 - create certificates for admin service

terraform/account/locals.tf, terraform/environment/actor_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/locals.tf, terraform/environment/pdf_ecs.tf, terraform/environment/viewer_ecs.tf, terraform/environment/viewer_load_balancer.tf
Update ownership of service and improve readability of JSON in task definitions
Fixes UML-1138
- Update owner tag in default tags
- Replace `<< EOF` with `jsonencode()`
- remove unecessary string interpolations in JSON
- Check impact on preproduction and production environments before merging
=> UML-1338 - Update tags and use jsonencode

service-api/app/composer.lock, service-front/app/composer.lock, tests/smoke/composer.lock
Update all PHP dependencies at once so we don't have to deal with all these dependabot ones.
```
make run_front_composer_update run_api_composer_update
cd tests/smoke && /usr/local/Cellar/php@7.4/7.4.19_1/bin/php /usr/local/bin/composer update
```
=> Update composer dependencies

CODEOWNERS
Update the team used in codeowners
=> Update codeowners [ci skip]

.github/workflows/golang-linting.yml
Inform developers early when there are issues with golang code.
Fixes UML-1519
Add a github action to run linting and provide inline feedback
https://golangci-lint.run/usage/install/
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
=> UML-1519 - add golang linting for service admin

.github/workflows/tfsec.yml
Check for and feedback deviations from good practice for Terraform managed AWS infrastructure as code
Fixes UML-1415
- Run TFsec as a github action against Terraform file changed in PR
- Write inline comments back to PR for any errors found
=> UML-1415 - Static analysis for IaC

.circleci/config.yml
Update terraform for workspace cleanup jobs
Fixes UML-1541
=> UML-1541 - Update terraform for workspace cleanup jobs

.circleci/config.yml
=> UML-1557 - Don't report coverage for golang app

Makefile, docker-compose.dependencies.yml, docker-compose.yml, service-api/docker/seeding/Dockerfile
Localstack was misbehaving so moved to the AWS local dynamodb instance.
=> Fix dynamodb localstack

service-front/app/features/context/UI/LpaContext.php, service-front/app/src/Actor/src/Handler/RequestActivationKey/RequestActivationKeyInfoHandler.php, service-front/app/src/Actor/templates/actor/before-requesting-activation-key-info.html.twig
https://opgtransform.atlassian.net/browse/UML-1573
Fixes UML-1573
=> UML 1573: Check if you can ask for an activation key page with new content and feature flagged

terraform/environment/actor_load_balancer.tf, terraform/environment/admin_load_balancer.tf, terraform/environment/viewer_load_balancer.tf
Fixes UML-1269
Remove support for cipher suites using RSA key exchange
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html
=> UML-1269 - Improve website encryption

service-pdf/app/package-lock.json, service-pdf/app/package.json, service-pdf/docker/app/Dockerfile
Fixes UML-1314
* Updates npm dependencies
* Upgrades to pupeteer 10.2.0
* Updates to use Docker pupeteer container 10.0.0
=> Upgrade all dependencies for pdf service

service-front/web/package-lock.json, service-pdf/app/package-lock.json, service-pdf/app/package.json
Update to close Dependabot PRs
```
make up webpack
make exec webpack /bin/sh
npm update --legacy-peer-deps
make up service-pdf
make exec service-pdf /bin/sh
npm update
npm audit fix
exit
docker cp service-pdf:/src/app/package.json service-pdf/app/
docker cp service-pdf:/src/app/package-lock.json service-pdf/app/
```
=> Update package files

.circleci/config.yml, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile
Fixes UML-1692 and UML-1688
use that latest compatible build that resolves the vulnerability
=> UML-1692 - update to alpine:3.14

Makefile, service-api/app/composer.json, service-api/app/composer.lock, service-api/docker/app/Dockerfile
update API composer files
``` 
make run_api_composer_update
```
=> Api composer update

terraform/account/credentials.tf, terraform/account/lambda_functions.tf, terraform/account/locals.tf, terraform/account/terraform.tfvars.json
Adds the API Key for OPG Metrics API Endpoint from shared development via secrets manager 
Fixes UML-1582
Create a new TF provider to access shared-development and pull the demo key into the service via the CI Pipeline
=> Uml 1582 secret metrics key

terraform/account/lambda_functions.tf, terraform/account/locals.tf, terraform/account/ship_metrics_queue.tf, terraform/account/terraform.tfvars.json
restructure opg metrics variables into an object
https://www.terraform.io/docs/language/values/variables.html
=> restructure opg metrics variables into an object

terraform/account/pagerduty.tf
Turn on SNS encryption
Fixes UML-1717
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic
=> UML-1717 - enable encryption for sns topics

service-api/seeding/put_actor_codes.py, service-api/seeding/seeding_lpa_codes.json
Seed codes to have expiry dates in the future
Fixes UML-1738
=> UML-1738 - fix code seeding for local dev

service-api/seeding/put_actor_codes.py, service-api/seeding/seeding_lpa_codes.json
add protections if running against production
- exit if the target environment is set to production
- only update expiry dates if the value is "valid"
=> update expiry dates that should be valid, don't update any other value

service-front/app/src/Actor/src/Handler/LogoutPageHandler.php
Ensure session data is cleaned on logout.
Fixes UML-1758
Clean all session data on logout
=> Ensure all data is removed from session

.circleci/config.yml, scripts/get_statistics/README.md, scripts/get_statistics/get_statistics.py
Statistics posts are exceeding character limit
Fixes UML-1746
Allow the script to default to "today - 90 days".
=> UML-1746 - Limit statistics scheduled task to producing 3 months of output

terraform/account/ship_metrics_queue.tf
SQS queues shoudl be encrypted at rest
Fixes UML-1771
- set kms key for encryption
=> UML-1771 - use encryption on sqs

.github/workflows/tfsec.yml
Provide feedback for terraform code
Fixes UML-1759
- run tfsec on account level terraform too
- run when terrafom files are changed
https://tfsec.dev/
=> UML-1759 - Feedback for terraform code issues

service-api/app/composer.lock, service-front/app/composer.lock, service-front/app/src/Common/src/Service/Session/Encryption/KmsEncryptedCookie.php, tests/smoke/composer.lock
Get rid of all this dependabot spam
=> php library updates

service-api/app/src/App/src/DataAccess/DynamoDb/DynamoHydrateTrait.php, service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php, service-api/app/src/App/src/DataAccess/Repository/UserLpaActorMapInterface.php, service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php, service-api/app/src/App/src/Service/Lpa/OlderLpaService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/UserLpaActorMapTest.php, service-api/app/test/AppTest/Service/ActorCodes/ActorCodeServiceTest.php, service-front/app/src/Actor/src/Form/RequestActivationKey/CreateNewActivationKey.php, service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckYourAnswersHandler.php, service-front/app/src/Actor/src/Handler/RequestActivationKey/CreateActivationKeyHandler.php, service-front/app/src/Actor/templates/actor/already-have-activation-key.html.twig, service-front/app/src/Actor/templates/actor/confirm-lpa-for-key-request.html.twig, service-front/app/test/ActorTest/Form/RequestActivationKey/CreateNewActivationKeyTest.php
Introduces better handling of the forcing of activation keys.
Add hidden field to form and use that value in the final endpoint.
=> Uml 1643 force activation key (pt3)

scripts/analysis_scripts/lookup_viewer_code.py
To provide support and understand what issues a user may be having, we want to retrieve data about a viewer code.
Fixes UML-1804
- Create a python script to return doata about viewer codes
- https://realpython.com/python-f-strings/
=> UML-1804 - Get viewer code data

service-api/app/composer.lock, service-front/app/composer.lock
Bulk update of dependencies in api and front
=> PHP dependency updates

service-front/web/package-lock.json, service-pdf/app/package-lock.json
Update service-pdf and web projects
=> JS dependency updates

docs/runbooks/upgrading-node-dependencies.md
Adds a run book to guide on how to update node dependencies.
=> Adds upgrade node runbook

service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig, service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig, service-front/web/src/scss/_count-lpas-added.scss, service-front/web/src/scss/_govuk-list.scss, service-front/web/src/scss/_lpa-ticket-panel.scss, service-front/web/src/scss/_lpa-typography.scss, service-front/web/src/scss/lpa.scss
- Add styling update as seen in the use prototype
- Remove dl from inside ticket-panel (dashboard items)
- Change heading levels
- Organise SCSS into appropriate files
Fixes UML-1809
=> Uml 1809 dashboard styling

docs/pull_request_template.md
Remind team members to document new event codes when they're added.
Fixes UML-1914
- add action to update event_codes to checklist
=> UML-1914 - Document Event Codes

terraform/environment/terraform.tfvars.json
Enable WAF Web ACL for production
Fixes UML-1968
- set `associate_alb_with_waf_web_acl_enabled` to true
UML-1964
=> UML-1968 - Enable WAF Web ACL for production

service-front/app/src/Actor/templates/actor/request-cleanse-note.txt.twig
Fields missing in notes field sent to sirius because of incorrect logic in template 
Fixes UML-1993
Correct the logic
*I have added tests to prove my work
=> UML-1993 Fix missing information in notes field

docker-compose.yml, terraform/environment/terraform.tfvars.json
set flags correctly for local, demo and development environments
Fixes UML-1992
- Reset the flag to 'false' for api and actor app in local, dev, demo environments
=> UML-1992: Invalid LPA reference numbers should be reported to the user

service-api/seeding/dynamodb.py
Pipelines are failing on seeding
Fixes UML-2041
- Add try/except blocks to catch botocore exceptions
=> UML-2041 - Catch errors when seeding

Makefile, service-front/app/composer.lock
Vulnerability in Twig so needs to be updated
Fixes UML-2092
`make run_front_composer_update twig/twig`
=> UML 2092 update twig

docs/pull_request_template.md
=> add section to PR checklist to notify the ID of content changes

service-api/app/composer.lock, service-front/app/composer.lock, tests/smoke/composer.lock
Bulk PHP dependency updates
composer update
=> Dependency updates in composer.lock files.

scripts/analysis_scripts/lookup_account.py
Return data for LPAs where activation codes are requested
Fixes UML-2163
- Add logging
- Replace paginator with Index Query for email lookups
- Limit attributes returned for accounts and LPAs
- Run Pylint and resolve findings
=> UML-2163 - Return data for LPAs where activation codes are requested

terraform/account/s3.tf
Fix broken PR pipeline
Fixes UML-2187
- remove KMS CMK for S3 bucket SSE
=> UML-2187 - remove CMK for lb access logging

terraform/account/.terraform.lock.hcl, terraform/account/waf.tf, terraform/environment/.terraform.lock.hcl, terraform/environment/terraform.tfvars.json
Upgrade pdf servce image
Set new WAF rule set to count
Fixes UML-2210
=> UML-2210 - upgrade pdf service image

docker-compose.yml
Update pdf service image tag for local development
Fixes UML-2218
- update docker-compose image
* ~The product team have tested these …
=> UML-2218 - update tag for pdf service

service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig, service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig, service-front/web/src/scss/_lpa-ticket-panel.scss, service-front/web/src/scss/lpa.scss, service-front/web/src/scss/ulpa-colours.scss
Make dashboard colours WCAG compliant
Fixes UML-1917
Make badges larger and change red on tickets to a darker red
=> UML-1917 Make dashboard colours WCAG compliant

.github/workflows/tfsec.yml, terraform/account/dynamodb_data_plane_cloudtrail.tf, terraform/account/locals.tf, terraform/account/modules/dynamodb_cloudtrail/.terraform.lock.hcl, terraform/account/modules/dynamodb_cloudtrail/cloudtrail.tf, terraform/account/modules/dynamodb_cloudtrail/kms.tf, terraform/account/modules/dynamodb_cloudtrail/s3.tf, terraform/account/modules/dynamodb_cloudtrail/variables.tf, terraform/account/terraform.tfvars.json
Enable the team to analyse and alert on dynamodb events that are outside the normal patterns of usage.
Fixes UML-2206
- Create a module to provision a new cloudtrail with independant S3 and KMS resources
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/logging-using-cloudtrail.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail
=> UML-2206 - Log DynamoDB Data Plane Events

terraform/account/modules/dynamodb_cloudtrail/cloudtrail.tf, terraform/account/modules/dynamodb_cloudtrail/kms.tf
Patch
Fixes UML-2206
- provide correct role names for ci
- add log group resource
=> UML-2206 fix permissions issue

terraform/environment/actor_load_balancer.tf, terraform/environment/viewer_load_balancer.tf
https://opgtransform.atlassian.net/browse/UML-2202
Fixes UML-2202
=> point to planned downtime content for fixed maintenance response

terraform/environment/terraform.tfvars.json
Build and deploy the admin service to production
Fixes UML-2244
- Set build_admin to true
=> UML-2244 - build admin service for production

terraform/account/waf.tf
Fixes UML-2228
- use exclude_rule block
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#managed-rule-group-statement
* ~I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram …
=> UML-2228 - Exclude no useragent header rule

service-front/docker/web/etc/confd/templates/nginx.conf
A permanent location has been provided for the moj security.txt redirect.
Fixes UML-2232
- update nginx conf rewrite rule
- https://www.nginx.com/blog/creating-nginx-rewrite-rules/
* ~I have notified the Interaction Designer of any content changes so that appropriate …
=> update redirect to moj security.txt

.github/workflows/golang-linting.yml
Update the golang linting github action
Fixes UML-2263
- Configure which golang to use
- update version of golangci/golangci-lint-action@v3
- update version of golangci-lint
- https://github.com/golangci/golangci-lint
- https://github.com/golangci/golangci-lint-action
- https://github.com/actions/setup-go
=> UML-2263 - Update Golang Linting

terraform/account/.terraform.lock.hcl, terraform/account/waf.tf
Actively block matches in the AWS WAF Common Rule Set
Fixes UML-2273
- remove count override
=> UML-2273 - Remove count override and start blocking matches

service-api/app/composer.lock, service-front/app/composer.lock, tests/smoke/composer.lock
=> Update PHP dependencies

terraform/environment/api_ecs.tf, terraform/environment/dns.tf, terraform/environment/pdf_ecs.tf
Part 3 of 3 - Cleanup after Service Discovery DNS changes
Fixes UML-2294
- Delete old service discovery resources
* ~The product team have …
=> UML-2238 / UML-2294 - Cleanup after Service Discovery DNS changes

terraform/account/.terraform.lock.hcl, terraform/account/dns_firewall.tf
Manage egress
Fixes UML-2333
- Add wildcardto DNS firewall for new service discovery
=> UML-2333 - Add new service discovery wildcard entry to DNS Firewall

.github/dependabot.yml
Keep dependencies up to date
Fixes UML-2344
- add dependabot configuration for service-admin gomod
- - add dependabot configuration for service-admin docker
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file
* ~I have run an accessibility tool on any pages I have …
=> UML-2344 - Add gomod and docker updates for service-admin

.circleci/config.yml
Reduce the time it takes to get meaningful feedback on update PRs
Fixes UML-2365
- Add a branch filter for `dependabot/go_modules/`
- https://circleci.com/docs2/2.0/configuration-reference#jobfilters
* ~The product team have …
=> UML-2365 - Run go_modules update PRs through admin only workflow

.circleci/config.yml
Reduce the time it takes to get feedback about admin code changes
Fixes UML-2369
- Add branch filtering for dependabot/docker/service-admin/*
* ~I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be …
=> UML-2369 - admin docker PRs run the admin-only pipeline

service-front/app/src/Common/templates/layout/default.html.twig, service-front/web/src/javascript/cookieConsent.test.js
=> default cookie banner as hidden

terraform/account/terraform.tfvars.json
Ensure dns firewall permits new Notify CDN
Fixes UML-2404
- add cdn to allowed domains list
=> UML-2404 - Add new notify CDN to allowed domains list

terraform/environment/actor_load_balancer.tf, terraform/environment/admin_load_balancer.tf, terraform/environment/shared_data_sources.tf, terraform/environment/viewer_load_balancer.tf
Remove offensive terms from code
Fixes UML-2510
- rename the module
- update module location
- upgrade module
* ~I have …
=> UML-2510 - Rename allow list module

service-api/app/composer.lock, service-front/app/composer.lock
Bring packages up to date
Fixes UML-2567
- run `make build_all`
- run `make up_all`
- run `make run_front_composer_update`
- run `make run_api_composer_update`
- commit new lock files
```php
aws/aws-sdk-php (3.224.3 => 3.231.1)
behat/behat (v3.10.0 => v3.11.0)
brick/varexporter (0.3.5 => 0.3.7)
friends-of-behat/mink-extension (v2.6.1 => v2.7.1)
laminas/laminas-component-installer (2.7.0 => 2.8.0)
laminas/laminas-diactoros (2.11.0 => 2.13.0)
laminas/laminas-form (3.1.1 => 3.2.0)
laminas/laminas-inputfilter (2.13.0 => 2.18.0)
laminas/laminas-servicemanager (3.11.2 => 3.14.0)
laminas/laminas-stdlib (3.7.1 => 3.10.1)
laminas/laminas-validator (2.17.0 => 2.20.1)
mezzio/mezzio (3.10.0 => 3.11.0)
monolog/monolog (2.6.0 => 2.7.0)
nesbot/carbon (2.58.0 => 2.59.1)
paragonie/constant_time_encoding …
```
=> UML-2567 - Upgrade composer packages

terraform/environment/actor_load_balancer.tf, terraform/environment/viewer_load_balancer.tf
Point maintenance at planned downtime messages
Fixes UML-2528
- update paths for maintenance service to /planned
=> UML-2528 - point maintenance to planned messages

service-admin/internal/server/data/account.go, service-admin/internal/server/data/account_test.go
https://opgtransform.atlassian.net/browse/UML-2268
Fixes UML-2268
* ~New event_codes have been documented on the [wiki page]~(https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* ~have added welsh translation tags and updated translation files~
* ~I have notified the Interaction …
=> UML-2268: added some tests for account

service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
add ga tags to read more link 
Fixes UML-2248
add tags
=> UML-2248 add ga tags

service-admin/.idea/.gitignore, service-admin/.idea/modules.xml, service-admin/.idea/runConfigurations/Admin_Service.xml, service-admin/.idea/runConfigurations/JWT_Proxy.xml, service-admin/.idea/service-admin.iml, service-admin/.idea/vcs.xml, service-admin/Dockerfile, service-admin/internal/server/auth/authorisation.go, service-admin/internal/server/auth/signing.go, service-admin/internal/server/auth/signing_test.go, service-admin/internal/server/server.go
Improving golang test coverage
Fixes UML-2267
=> Uml-2267 signing test coverage

terraform/environment/terraform.tfvars.json
Make the access for all journey available to users.
Fixes UML-2593
- set allow_older_lpas flag to true
* ~The product team have tested these …
=> UML-2593 - Turn on access for all journey in all environments

.github/workflows/codeql-analysis.yml
Upgrade CodeQL Actions
Fixes UML-2363
- https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
* ~The …
=> UML-2363 - Upgrade codeql actions to v2

terraform/environment/actor_ecs.tf, terraform/environment/admin_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/pdf_ecs.tf, terraform/environment/viewer_ecs.tf
Reduce the diff between commits by setting default values
Fixes UML-2367
- configure deployment_circuit_breaker
- configure deployment_controller
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service
* ~I have notified the Interaction …
=> UML-2367 - Define some default values for ECS services

service-api/app/src/App/src/Service/Log/LogStderrListener.php, service-api/app/test/AppTest/Service/Log/LogStderrListenerTest.php, service-front/app/src/Common/src/Service/Log/LogStderrListener.php, service-front/app/test/CommonTest/Service/Log/LogStderrListenerTest.php
=> Remove stack traces from api error logging 

service-api/app/src/App/src/Service/Lpa/LpaService.php, service-api/app/src/App/src/Service/User/UserService.php
=> UML-2651: Live log error reasons and fix 

service-api/docker/app/Dockerfile, service-api/docker/app/app-php.development.ini, service-api/docker/app/app-php.ini, service-front/docker/app/Dockerfile
Ensure we report all errors during development to the dev.
Fixes UML-1947
=> Uml 1947 add development error reporting

service-front/app/src/Actor/src/Handler/PasswordResetRequestPageHandler.php
All other responses should throw the exception.
Ensure that we capture the exception type before sending an email so that we can be sure we're sending the email appropriately.
* I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow …
=> Ensure we capture *only* a 404 when sending the not found email

.github/workflows/php-linting.yml, service-front/app/src/Actor/src/Handler/RequestActivationKey/ActorAddressHandler.php
Linting install wasn't optimal and Seema seems to have found out how to break it already 😂
=> Move to a different way of setting up the phpcs install

service-front/app/languages/cy/LC_MESSAGES/messages.po, service-front/app/languages/messages.pot, service-front/app/src/Actor/src/Handler/RequestActivationKey/ActorAddressHandler.php, service-front/app/src/Actor/templates/actor/request-activation-key/actor-address.html.twig
https://opgtransform.atlassian.net/browse/UML-2641
Fixes UML-2641
* ~New event_codes have been documented on the [wiki page]~(https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* ~I have added welsh translation tags and updated translation files~ [Translations will be added in a new ticket]
=> UML-2641: code changes to display postcode on current address page

service-admin/internal/server/handlers/stats.go, service-admin/internal/server/handlers/stats_test.go, service-admin/internal/server/server.go, service-admin/web/templates/header.partial.gohtml, service-admin/web/templates/stats.page.gohtml
https://opgtransform.atlassian.net/browse/UML-2643
Fixes UML-2643
=> UML-2643 : Add tabs for search and stats in admin portal

service-api/docker/seeding/start.sh, terraform/account/s3_redacted_logs.tf, terraform/environment/admin_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/backup_plan.tf, terraform/environment/config_file.tf, terraform/environment/dynamodb.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json
Create stats table in dynamo
Fixes UML-2704
Add Table with single TimePeriod key. 
Add to seeding script as well.
=> Create stats table

terraform/environment/lambda.tf
Add schedule for stats update lambda
Fixes UML-2675
Add a cloudwatch event
None
=> UML-2675 add scheduling of statistics lambda

service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile
Fix as part of trivy scan
upgrade as 3.16 still has the issue (but might as well update to 3.16 anyway)
NA
=> update libxml2 to more secure version

tests/features/security-headers.feature, tests/smoke/context/CommonContext.php
Add test that we include X-Frame-Options header with value deny
Fixes UML-2428
=> add test for header

service-api/docker/web/Dockerfile, service-front/docker/web/Dockerfile
To ensure curl is most up to date resolving CVE alerts
CVE-2022-42915
CVE-2022-42916
Fixes UML-2720
Add `apk update curl` to Dockerfiles to ensure the latest version of `curl` is installed.
Tested by running trivvy locally before and after change
=> UML-2720 - Add update curl to Dockerfile

service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php, service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMapFactory.php, service-api/app/src/App/src/Handler/LpasResourceCodesCollectionHandler.php, service-api/app/test/AppTest/DataAccess/DynamoDb/UserLpaActorMapFactoryTest.php, service-api/app/test/AppTest/DataAccess/DynamoDb/UserLpaActorMapTest.php
Adds additional logging so that we can catch what we're missing around our DB records being empty.
=> Add additional logging around arrays being unexpectedly empty

.circleci/config.yml, .github/workflows/_run-terraform.yml, .github/workflows/pull-request-path.yml, .github/workflows/scheduled-update-demo.yml, .github/workflows/scheduled-workspace-cleanup.yml, .pre-commit-config.yaml, scripts/pipeline/post_release_slack_notification/post_release_slack_notification.py, scripts/pipeline/post_release_slack_notification/successful_demo_release.txt
Add the demo environment nightly redeploy to GH actions
Fixes UML-2557
Added demo redeploy and removed from CircleCi.
Fixed missing pagerduty token for nightly destroy and tested it works
Did some minor fixes on the slack templates to handle gh actions vars
NA
=> UML-2557 add demo env redeploy wf to gh actions

service-front/web/package-lock.json, service-front/web/package.json
* Uses the latest npm version to build the package-lock file Downgrade
* @babel/runtime-corejs3 to the latest version
Fixes UML-####
nvm use before npm install to generate matching ci npm version
May need to look at the nvmrc file and specify a more exact version.
=> Fix package-lock error

.github/workflows/_node-build.yml, .github/workflows/_node-test.yml, service-front/web/package-lock.json
=> Fix npm build

.github/workflows/_build-and-push.yml, .github/workflows/scheduled-codeql-analysis.yml, .github/workflows/scheduled-package-scan.yml, .github/workflows/scheduled-tfsec.yml, .github/workflows/scheduled-update-demo.yml, .github/workflows/scheduled-workspace-cleanup.yml
create scheduled daily tfsec update
Fixes UML-UML-1793
Went for 7am each day and did the upload of sarif to sec tab as per requested in ticket.
Prefixed scheduled tasks with [Scheduled] to make it more obvious which they are in the workflows in actions tab.
NA
=> UML-1793 create scheduled daily tfsec update on main

.github/workflows/_slack-notification.yml, .github/workflows/path-to-live.yml, .github/workflows/pull-request-path.yml, scripts/pipeline/post_release_slack_notification/post_release_slack_notification.py, scripts/pipeline/post_release_slack_notification/unsuccessful_release.txt
Notify of failed path to live
Notify on path to live but not other paths
NA
=> Handle pipe fails

terraform/account/vpc_endpoints.tf
Part 1. Just enable the VPC endpoints in Dev environment
Fixes UML-2776a
Just enabling in dev whilst I work out how to get the outbound traffic to work
NA
=> UML-2776a enable vpc endpoints

service-admin/Dockerfile
Fixes:  Trivy scanned security vulnerability issue
- Pinned Alpine to version 3.17
- Upgraded the packages libcrypto3 and libssl3
=> Trivy Fix: Pin alpine version to 3.17 and upgraded some packages

service-front/app/src/Common/templates/layout/default.html.twig, service-front/web/build.js, service-front/web/package.json
Minify JS and CSS
Fixes UML-2783
=> Minify JS and CSS

.circleci/config.yml
Remove docker creds as no longer needed
=> fix stats job

.github/workflows/_seed-database.yml, .github/workflows/scheduled-update-demo.yml, scripts/pipeline/post_release_slack_notification/unsuccessful_release.txt
Update demo env to have seed data
Fixes UML-2807
Added seed data. Added extra security feature to stop us seeding prod. Changed unsuccessful release workflow text so it doesn't look like  a path to leave issue when demo env fails
NA
=> UML-2807 update demo environment with seeds

service-front/app/features/context/UI/ViewerContext.php, service-front/app/features/view-lpa-using-sharecode-with-instructions-and-preferences.feature, service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig, service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
https://opgtransform.atlassian.net/browse/UML-2803
Fixes UML-2803
=> UML-2803: Fixing UI to show instructions and preferences together

mock-integrations/mock-openapi.yaml, service-front/app/src/Common/src/View/Twig/LpaExtension.php, service-front/app/test/CommonTest/View/Twig/LpaExtensionTest.php
https://opgtransform.atlassian.net/browse/UML-2799
Fixes UML-2799
~* [ ] New event_codes have been documented on the [wiki page]~(https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
~* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made~
=> UML-2799: Add country to address data for use use and view

service-admin/internal/server/data/lpa.go, service-admin/internal/server/handlers/search.go, service-admin/internal/server/handlers/search_test.go, service-admin/web/templates/result_lpa.partial.gohtml, service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php, service-api/app/test/AppTest/DataAccess/DynamoDb/UserLpaActorMapTest.php, service-api/seeding/dynamodb.py
https://opgtransform.atlassian.net/browse/UML-2777
https://opgtransform.atlassian.net/browse/UML-2785
Fixes [UML-2777](https://opgtransform.atlassian.net/browse/UML-2777) and [UML-2785](https://opgtransform.atlassian.net/browse/UML-2785)
1. Added field 'Updated' to UserLpaActorMap table
2. Updated seeding script
3. Update field gets populated when LPA is activated by code [Added field remains the same and gets populated when LPA added to account and key requested]
4. In Admin portal, when searching by LPA number - it now shows 'Activated on' date along with 'Added by', 'Added on' details
5. Test additions and fixes
* [X ] I have performed a …
=> UML-2777-2785: Show date LPA was added by code/ activated when possible in Admin portal

service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig, service-front/app/src/Common/templates/partials/full-lpa-display.html.twig, service-front/app/src/Common/templates/partials/lpa-summary-details/lpa-attorney-details.html.twig, service-front/app/src/Common/templates/partials/lpa-summary-details/lpa-details.html.twig, service-front/app/src/Common/templates/partials/lpa-summary-details/lpa-donor-details.html.twig
https://opgtransform.atlassian.net/browse/UML-2006
Fixes UML-2006
~* [ ] New event_codes have been documented on the [wiki page]~(https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
~* [ ] I have notified the Interaction Designer of any content changes so …
=> UML-2006: Common templates moved to partial folder

docker-compose.yml, service-api/app/config/autoload/features.global.php, service-front/app/features/bootstrap/behat.config.php, terraform/environment/actor_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json
https://opgtransform.atlassian.net/browse/UML-2843
Fixes UML-2843
~* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)~
~* [ ] I have run an accessibility tool on any pages I have made changes to …
=> UML-2843: Adding API feature flag

.github/workflows/_node-build.yml, .github/workflows/_node-test.yml, service-front/web/package-lock.json, service-front/web/src/javascript/analyticsTracking.test.js, service-front/web/src/javascript/cookieHelper.test.js, service-front/web/src/javascript/googleAnalytics.test.js
Path to live broken javascript fix
=> Fix path-to-live javascript build/test issues

README.md
_bring README.md up to date for new starters_
_update README_
=> UML-2872 bring README.md up to date for new starters

service-front/app/config/autoload/features.global.php
_Add the instructions & preferences flag to globals for service-front_
_Simple addition to config file_
=> UML-2847 add instructions & preferences flag to globals for service-front

.idea/inspectionProfiles/Project_Default.xml, .idea/php-test-framework.xml, .idea/php.xml, .idea/phpunit.xml, .idea/watcherTasks.xml, service-front/app/config/autoload/development.local.php.dist
Makes sessions work for local dev.
Add configuration to development mode file. You'll need to either copy the service-front development mode dist file contents into your development mode file or  delete it and reenable using `make development_mode`
* I have notified the Interaction …
=> Development fixes

.github/workflows/pull-request-path.yml, lambda-functions/upload-statistics/app/upload-statistics.py
No workflow was running for dependabot/pip. Fixes that.
=> match dependabot prs that update pip

renovate.json
=> there was a type in renovate file

terraform/environment/shared_data_sources.tf
Allow GlobalProtect VPN addresses to connect to non-production environments
Fixes UML-2899
Update the IP allow list module to include latest addresses.
=> UML-2899 Update MOJ IP allow list

.github/workflows/pull-request-path.yml
Make the TF workspace name unique even if the first 8 characters of a branch name are the same.
Fixes UML-2893
Include the Github PR number in the workspace name to ensure uniqueness.
=> UML-2893 TF workspace name to include PR number

.github/workflows/pull-request-path.yml
Reverts ministryofjustice/opg-use-an-lpa#2262
=> Revert "UML-2893 TF workspace name to include PR number"

service-front/app/src/Common/templates/partials/lpa-summary-details/lpa-details.html.twig, service-front/app/src/Viewer/src/Handler/ViewLpaHandler.php, terraform/environment/terraform.tfvars.json
=> I&P Go Live

.github/workflows/pull-request-path.yml, terraform/account/keys.tf, terraform/account/secretsmanager.tf, terraform/environment/locals.tf, terraform/environment/shared_data_sources.tf
https://opgtransform.atlassian.net/browse/UML-3008
Fixes UML-3008
Create keypair in code.
=> UML-3009 Create AWS Secret for OneLogin private / public keys

query/README.md
Documentation update / correction.
Fixes UML-2974
No code change - documentation only.
=> UML-2974 Update documentation for DynamoDB export

service-front/docker/app/Dockerfile
Pins ext-redis so that the laminas adaptor we use continues to work.
=> Pin ext-redis to ^5

service-api/docker/app/Dockerfile
Upgrade service-api base container to include OpenSSL 3.1.
Fixes UML-3052
=> UML-3052 Upgrade service-api base container

.github/workflows/statistics.yml, scripts/pipeline/service_stats_to_slack/service_stats.txt, scripts/pipeline/service_stats_to_slack/stats_slack_notification.py
Move the stat collection and notification out of circle into gh actions. This allows us to then close off our circle ci usage for use
Fixes UML-3046 & UML-2565
=> Uml 3046 move stats to gh

service-front/docker/app/Dockerfile
Upgrade service-front alpine version from 3.16 to 3.18
Fixes UML-3053
=> UML-3053 Upgrade service-front alpine version

service-api/docker/app/Dockerfile, service-api/docker/web/Dockerfile
Fix for pipeline
Fixes UML-3087
Add required environment variable to service-api app dockerfile and remove from web dockerfile.
=> UML-3087 Add env var to correct Dockerfile

mock-integrations/one-login/main.go
_Add logout endpoint to OneLogin mock_
_Add endpoint in main.go_
=> Uml 3058 mock logout

.github/workflows/_run-terraform.yml, .github/workflows/path-to-live.yml, .github/workflows/workflow-deploy-ref-to-env.yml, terraform/environment/locals.tf, terraform/environment/viewer_load_balancer.tf
Allow developers to deploy an arbitrary branch to the UR environment.
Fixes UML-3079
Create a dispatch workflow which will run the Terraform of branch X against the Y Terraform workspace. X represents any valid branch name and Y represents an existing Terraform workspace. (This would typically be `ur`)
=> UML-3079 Deploy UR environment from any branch

.github/workflows/workflow-deploy-ref-to-env.yml
=> UML-3079: Fix typo in workflow

docs/runbooks/ur_environment.md
Add a runbook to explain how to use the UR environment
Fixes UML-3079
=> UML-3079: Add runbook for UR environment

terraform/environment/terraform.tfvars.json
Increase actor and API minimum containers from 2 to 3.
Fixes UML-3112
=> UML-3112 Increase actor and api min containers

terraform/account/region/network.tf, terraform/account/region/s3_redacted_logs.tf, terraform/account/region/vpc_endpoints.tf
Remove some temporary workarounds used in Terraform to migrate data sources without destroying resources.
Fixes UML-3147
=> UML-3147 Remove temporary workarounds from TF

.pre-commit-config.yaml, terraform/environment/region/data_sources.tf
Correct a bug to ensure ECS tasks are able to read Secrets
Fixes UML-3149
Change a data lookup to reference new MRK secrets key.
=> UML-3149 Correct Secrets Manager lookup

scripts/pipeline/check_ecr_scan_results/aws_ecr_scan_results.py
Handle UNTRIAGED severity in ECR
Fixes UML-3152
=> UML-3152 Handle UNTRIAGED severity in ECR

terraform/account/region/waf.tf
Replace a deprecated argumentin WAF Terraform to allow upgrade to Terraform => 5
Fixes UML-3160
=> UML-3160 Replace deprecated argument in WAF TF

terraform/account/.terraform.lock.hcl, terraform/account/terraform.tf, terraform/environment/.terraform.lock.hcl, terraform/environment/terraform.tf
=> UML-3170 Update AWS provider version

renovate.json
=> Remove earlyMondays schedule

renovate.json
=> Update renovate.json with prCreation: immediate

renovate.json
Prevent Renovate from raising excessive branches
Fixes UML-####
=> Add ratelimits for renovate

terraform/account/refactor.tf, terraform/account/region/certificate.tf
=> UML-3175 Move certificates to region

terraform/account/refactor.tf
Refactor necessary for prod
Fixes UML-3175
=> UML-3175 Fix for prod

service-api/app/src/App/src/Exception/ActorCodeMarkAsUsedException.php, service-api/app/src/App/src/Exception/ActorCodeValidationException.php, service-api/app/src/App/src/Exception/AuthorisationServiceException.php, service-api/app/src/App/src/Service/Authentication/AuthorisationService.php, service-api/app/src/App/src/Service/Authentication/AuthorisationServiceBuilder.php, service-api/app/src/App/src/Service/Authentication/OneLoginAuthenticationRequestService.php
Adds exception handling to unhandled exception raised from Facile's AuthorizationService getAuthorizationUri() method.
Also cleans up ActorCodeMarkAsUsedException.php and ActorCodeValidationException.php files
Fixes UML-3122
Create wrapper classes AuthorisationService and AuthorisationServiceBuilder.
- New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
- I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
- I have added tests to prove my work
- I have added welsh translation tags and updated translation files
- I have run an accessibility tool on any pages I have made changes to and fixed any issues found
- I have notified the Interaction Designer of any …
=> Uml 3122 one login api exception handling

terraform/account/region/elasticache.tf
Upgrading the elasticache node type from cache.t2.micro to cache.t4g.micro -https://opgtransform.atlassian.net/browse/UML-3089
Fixes UML-3089
=> UML-3089: upgrade es node

.github/workflows/scheduled-update-demo.yml
We currently get failures every morning about the demo environment not being able to update. This PR fixes that.
Fixes UML-####
Pass a `workflow_status` to the __slack-notification.yml reusable workflow.
=> UML-3213 Fix Slack notifcations for scheduled demo

service-front/web/package-lock.json
Recreate dependabot PR.
Bumps [@adobe/css-tools](https://github.com/adobe/css-tools) from 4.3.1 to 4.3.2.
- [Changelog](https://github.com/adobe/css-tools/blob/main/History.md)
- [Commits](https://github.com/adobe/css-tools/commits)
---
updated-dependencies:
- dependency-name: "@adobe/css-tools" dependency-type: indirect ...
Fixes UML-####
=> Bump @adobe/css-tools from 4.3.1 to 4.3.2 in /service-front/web

service-api/docker/seeding/start.sh, terraform/environment/dynamodb.tf
Add identity indexes to dynamodb tables to allow lookups for this key.
Work for UML-3015
=> UML-3015 Add identity index to DynamoDB

service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile
Currently front is on 8.1.23 so two versions behind and missing any security or stability fixes.
Fixes UML-3162
*~ [ ] I have added relevant logging with appropriate levels to my code~
* ~[ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)~
* ~[ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* ~[ ] I have added tests to prove my work~
* ~[ ] I have added welsh translation tags and updated translation files~
* ~[ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found~
*~ [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made~
=> updated docker containers

service-api/docker/seeding/start.sh, service-api/seeding/put_actor_codes.py
=> fix dev update

terraform/account/locals.tf, terraform/account/region/variables.tf, terraform/account/terraform.tf, terraform/environment/locals.tf, terraform/environment/shared_data_sources.tf
Remove unnecessary data lookups and local variables in account and environment Terraform config to reduce complexity.
Fixes UML-3225
=> UML-3225 Remove unnecessary data lookups

.github/workflows/path-to-live.yml
Add semantic versioning to the repo.
Fixes UML-3224
Uses anothrNick/ghithub-tag-action: https://github.com/anothrNick/github-tag-action
=> UML-3224: add semantic versioning

terraform/account/region/lambda_functions.tf, terraform/account/region/modules/lambda_function/terraform.tf, terraform/account/region/s3_lb_access_logs.tf
=> UML-3155 Make Lambda module regional

terraform/account/region.tf, terraform/account/terraform.tf
=> UML-3155 Add multi region ECR support

docker-compose.dependencies.yml
Pins mock to latest version and update the REDIRECT_URL 
Fixes UML-3144
=> UML-3144 pin mock to altered mock

lambda-functions/upload-statistics/Dockerfile
Replace the base image used in the stats Lambda
Fixes UML-3210
=> UML-3210 Replace stats Lambda base image

lambda-functions/upload-statistics/Dockerfile
=> UML-3210 Use Python slim for building lambda

.github/workflows/path-to-live.yml
Move to a internally managed GitHub action
Fixes UML-3242
=> UML-3242: use shared github action

.github/workflows/path-to-live.yml
Fixed an incorrect output for semver tagging from `new_tag` to `created_tag`.
Fixes UML-3242
=> UML-3242: #patch incorrect output

.github/workflows/path-to-live.yml
The previous `default_bump` was set to `patch`, but we will most commonly update with `minor`.
Fixes UML-3242
=> UML-3242: #patch change default bump to minor

.github/workflows/path-to-live.yml
Update semver version to test new python path in runner
Fixes UML-3242
=> UML-3242: #patch change semver version

.github/workflows/path-to-live.yml
Revert back to 2.6.2 to allow pipeline to run
Fixes UML-3242
=> UML-3242: #patch change back to 2.6.2

lambda-functions/upload-statistics/Dockerfile, terraform/environment/region/actor_load_balancer.tf, terraform/environment/region/viewer_load_balancer.tf
Resolve security alerts for stats upload Lambda.
Fixes UML-3249
Upgrade the system packages of the stats_upload Lambda using Debian's `apt` package manager.
=> UML-3249 Upgrade packages in Lambda function

.github/workflows/path-to-live.yml
Update semver action to 2.7.3 and change default bump to minor instead of patch
Fixes UML-3242
=> UML-3242: #patch default update to minor

terraform/account/region/s3_lb_access_logs.tf
Add bucket-level public access block
Fixes UML-3274
=> UML-3274 Add bucket-level public access block

query/dynamodb_export.py
_Add the organisations query to the dynamodb script that is run monthly, so that we can get these reports auto-generated monthly_
- Add the new sql query thanks to @ntse  :) Modified to use the date range supplied to script
- Fix an issue where empty cells couldn't be handled - now sorted
- Put the date range on the filename for the reports. Otherwise you cannot tell from a file, what date range it was for
- Ran black again, which has reformatted a bit of code 
- Have tested by hand locally_
=> UML-3278 add organisations query to script

terraform/environment/region/modules/dns/main.tf
=> UML-3281 Correct DNS name for TXT records

query/dynamodb_export.py
_Add query for created access codes_
_Add query to script_
=> added created query

.github/labeler.yml, .github/workflows/labeler.yml
Add a labeller workflow to automatically label PRs.
Fixes UML-3287
Create a new workflow that adds labels.
=> UML-3287 Add Label Pull Requests workflow

.github/labeler.yml
Add a dependencies to the labeler Github Workflow
Fixes UML-3287
=> UML-3287 Add dependencies label

service-api/docker/app/fpm-pool.ini, terraform/environment/region/api_ecs.tf
Export PHP-FPM stats for service-api
Fixes UML-3221
=> UML-3221 Export PHP-FPM stats for service-api

terraform/environment/terraform.tfvars.json
Run ECS scaled to zero in eu-west-2 for production.
Fixes UML-2457
Change the "enabled" boolean to true for production.
=> UML-2457 Run pilot light compute in eu-west-2

.github/workflows/path-to-live.yml
Update the options for semver-tag to unblock Path to Live.
Unticketed
=> Update opg-github-actions with new options

docs/runbooks/use_secondary_region.md
Document deploying environment level regional resources into second region
Fixes UML-2547
=> UML-2547 Deploy environment level regional resources into second region

.idea/php.xml, Makefile, docker-compose.dependencies.yml, service-api/app/composer.lock, service-api/app/config/routes.php, service-api/app/features/actor-logout.feature, service-api/app/features/actor-one-login.feature, service-api/app/features/context/Acceptance/OidcContext.php, service-api/app/features/context/BaseAcceptanceContextTrait.php, service-api/app/src/App/src/Handler/OneLoginAuthenticationLogoutHandler.php, service-api/app/src/App/src/Service/Authentication/AuthorisationClientManager.php, service-api/app/src/App/src/Service/Authentication/AuthorisationService.php, service-api/app/src/App/src/Service/Authentication/OneLoginService.php, service-api/app/src/App/src/Service/Cache/CacheFactory.php, service-api/app/test/AppTest/Service/Authentication/OneLoginServiceTest.php
Service-API components for logout handling via OneLogin
Fixes UML-3016
New endpoint and associated service class changes. Not explicitly feature flagged as it's a completely new endpoint.
=> Uml 3016 service api onelogin logout endpoint

service-front/app/composer.lock
_UML-3351 upgrade versions of packages using composer rather than renovate's way_
_ran composer update_
=> UML-3351 upgrade versions of packages using composer rather than renovate's way

.github/workflows/_run-behat-tests.yml, .github/workflows/_run-terraform.yml, .github/workflows/_seed-database.yml, .github/workflows/_slack-notification.yml, .github/workflows/path-to-live.yml, .github/workflows/pull-request-path.yml, .github/workflows/scheduled-update-demo.yml, .github/workflows/workflow-deploy-ref-to-env.yml
Prevent error with unique artifact name
Fixes UML-####
=> Use a unique artifact name in pipeline for cluster config

service-front/app/src/Actor/templates/actor/partials/service-message.html.twig, service-front/app/src/Viewer/templates/viewer/partials/service-message.html.twig
=> Switch to using "is not empty" for display of system message

terraform/environment/region/modules/ecs_autoscaling/variables.tf
Raising the minimum metrics to allow our actor-service tasks to scale down appropriately 
Fixes UML-3424
=> UML-3424: adjust metrics to allow scale down

terraform/account/keys.tf, terraform/account/secretsmanager.tf
Adds new secretsmanager secrets to terraform for LPA data public and private key
=> UML-3392: add lpa data secrets to terraform

terraform/account/keys.tf, terraform/account/secretsmanager.tf
to remove lpa data secret from terraform
Fixes UML-3392
=> UML-3392-remove secrets from terraform

terraform/account/region/waf.tf
Blocks requests that flood `/session-check`
Fixes UML-3425
=> UML-3425: block matching requests

service-front/web/package-lock.json
_Upgrade braces to improve security_
_package-lock file_
=> UML-3403 upgrade braces

service-admin/Dockerfile
=> Update golang version

terraform/environment/terraform.tfvars.json
Enable one-login for the UR environment using the integration GovUK One Login service.
Fixes UML-3471
=> Configure UR env in terraform

scripts/pipeline/workspace_cleanup/workspace_cleanup.sh
Adds the ur env to the reserved workspaces lists, so that it is not auto cleaned up
Fixes UML-3478
=> UML-3478: Adding ur to reserved workspaces

scripts/pipeline/check_ecr_scan_results/requirements.txt
=> RecreateDP PR.

service-api/app/config/routes.php, service-api/app/src/App/src/Handler/LpasCollectionV2Handler.php
_Implemented a new v2 LPAs endpoint for the backend_
Fixes UML-####
_created a new route and handler_
=> UML-3431 Implement v2 LPAs endpoint (back-end)

terraform/environment/terraform.tfvars.json
Due to likely increase in usage while we send our notifications of change of login, we're going to run hot on the service temporarily and also increase the maximum number of tasks available.
Fixes UML-3498
=> UML-3498: increase scaling temporarily

terraform/environment/terraform.tfvars.json
Reduces scaling back down to normal figures due to not seeing any measurable increase in figures during the Notify email sendout
Fixes UML-3498
=> UML-3498: reduce scaling

docker-compose.yml, service-api/app/config/autoload/features.global.php, service-api/app/features/actor-add-an-older-lpa.feature, service-api/app/src/App/src/Service/Lpa/AddAccessForAllLpa.php, service-api/app/test/AppTest/Service/Lpa/AddAccessForAllLpaTest.php, service-front/app/config/autoload/features.global.php, service-front/app/features/actor-add-an-older-lpa.feature, service-front/app/features/bootstrap/behat.config.php, service-front/app/src/Actor/templates/actor/cannot-find-lpa.html.twig, terraform/environment/region.tf, terraform/environment/region/api_ecs.tf, terraform/environment/region/use_ecs.tf, terraform/environment/terraform.tfvars.json, terraform/environment/variables.tf
_removed dont_send_lpas_registered_after_sep_2019_to_cleansing_team flag and defaulted to on_
Fixes UML-####
_removed references and usages_
=> UML-2223 Removed Feature Flag dont_send_lpas_registered_after_sep_2019_to_cleansing_team

service-front/app/features/context/UI/AccountContext.php, service-front/app/features/context/UI/LpaContext.php, service-front/app/src/Actor/src/Handler/LpaDashboardHandler.php, service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig
Fixes UML-3511
Description
We currently have two twig files that compose the lpa dashboard; lpa-dashboard.twig.html and lpa-blank-dashboard.twig.html. The content on both is now very similar so they can be merged into a single template file to streamline and reduce redundancy. 
AC
a new template which includes conditional logic to display the correct content based on whether there are LPAs.
updated handler - LpaDashboardHandler
=> UML-3511 combine twig files and handler functionality.

terraform/environment/region/cloudwatch_data_protection_policy.tf
Updated the regex pattern in the Data Protection Policy. This regex pattern is to filter out email addresses.
Fixes UML-3251
=> Updating data protection policy regex pattern

terraform/environment/region/cloudwatch_data_protection_policy.tf
Updates regex query within the data protection policy
Fixes UML-3251
=> Update regex query in data protection policy

terraform/environment/terraform.tfvars.json
=> UML-3533: Increase task count for One Login GoLive

terraform/environment/region/cloudwatch_data_protection_policy.tf
Adds depends on block to fix errors
Fixes UML-3535
=> UML-3535: add depends on to data protection policy

.idea/php.xml, service-api/app/src/App/src/Service/Notify/NotifyService.php, service-front/app/src/Common/src/Middleware/Session/SessionAttributeAllowlistMiddleware.php, service-front/app/src/Common/src/Service/Notify/NotifyService.php
Tidy up some of the logging so Cloudwatch is easier to follow.
Bumped some things to DEBUG and improved content in other things.
=> Logging changes

docker-compose.dependencies.yml, service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile
Enables the ability to choose a one login "user" as well as the associated email (will need to run `make pull`)
* The product team have tested these …
=> Enable new one login mock functionality

codecov.yml, service-admin/Dockerfile
=> update Go version to  v1.23.0

.github/workflows/workflow_destroy_on_merge.yml, scripts/pipeline/workspace_cleanup/destroy_workspace.sh
=> Add destroy on merge workflow

.github/workflows/workflow_destroy_on_merge.yml
Update ssh and pager duty secret setting
Fixes UML-3454
=> Uml 3454 update secret value

service-front/app/src/Actor/src/Form/OneLoginForm.php
_updating the error message that users get when they get the "missing session" error_
=> updated session missing error message

.github/workflows/workflow_destroy_on_merge.yml, scripts/pipeline/workspace_cleanup/destroy_workspace.sh
Updates the data parse workspace to correctly parse workspace names
Fixes UML-3589
=> UML-3589: fix workspace deletion

.github/workflows/workflow_destroy_on_merge.yml, scripts/pipeline/workspace_cleanup/destroy_workspace.sh
=> UML-3589: fix workspace destroy

terraform/environment/region/data_sources.tf, terraform/environment/terraform.tfvars.json
Update PDF service ECR image version
Fixes UML-3613
=> UML-3613: Update PDF service

.github/workflows/_build-and-push.yml
Set the GitHub access token to download Trivy DB. Trivy DB is downloaded by Trivy from the GitHub release page. Anonymous downloads from GitHub are subject to the limit of 60 requests per hour. Normally such rate limit is enough for production operations. If, for any reason, it's not enough, you could increase the rate limit to 5000 requests per hour by specifying the GitHub access token.
Fixes UML-3653
=> Update trivy job

.github/workflows/_build-and-push.yml
Sets up the Trivy db ecr mirror as an env var
Fixes UML-3653
=> Add trivy db ecr mirror

.github/workflows/workflow_destroy_on_merge.yml
Rolls back terraform-version to a previously working version until we can address the breaking change 
Fixes UML-3660
=> UML-3660: rollback terraform-version

.github/workflows/pull-request-path.yml
Fixes inadvertent pipeline pass when slack notify is skipped, indicating the behat test suite has failed
Fixes UML-3661
=> UML-3661: fix wonky logic

.github/workflows/workflow_destroy_on_merge.yml
Upgrades terraform-version to new major version
Fixes UML-3665
=> UML-3665: upgrade terraform-version

scripts/pipeline/generate_trivy_report/code_scan_report.py
Ensures that the code scan report script, does not post to slack, when there are no critical or high severity alerts
Fixes UML-3672
=> Update code scan report script

.github/workflows/_build-and-push.yml
Pull java db in trivy job
Fixes UML-3653
=> Add java db to trivy job

scripts/pipeline/generate_trivy_report/code_scan_report.py
Adds a heading to the trivy code scan script
Fixes UML-3670
=> Update code scan script

terraform/environment/region.tf, terraform/environment/region/application_insights.tf, terraform/environment/region/data_sources.tf, terraform/environment/region/pagerduty.tf, terraform/environment/region/resource_group.tf, terraform/environment/region/variables.tf, terraform/environment/terraform.tfvars.json, terraform/environment/variables.tf
Configure app insights for dev
Fixes UML-2205
=> Configure app insights for dev

terraform/environment/terraform.tfvars.json
Disable app insights on dev and enable for demo
Fixes UML-2205
=> Enable app insights on demo

terraform/environment/terraform.tfvars.json
Enable app insights in preprod
Fixes UML-2205
=> Enable app insights in preprod

terraform/account/region/waf.tf
Counts ratelimited IPs to see how it effects traffic before implementing block
Fixes UML-3694
=> UML-3694: add ratelimit by ip rule

terraform/environment/terraform.tfvars.json
Enable app insights in prod
Fixes UML-2205
=> Enable app insights in prod

terraform/environment/terraform.tfvars.json
Remove app insights from demo in code
Fixes UML-2205
=> App inisights demo false

scripts/get_statistics/README.md
=> fix typo and add iso date

terraform/account/region/application_insights.tf, terraform/account/region/resource_group.tf
Update resource group name
Fixes UML-2205
=> Update resource group name

terraform/account/terraform.tfvars.json
Adds app insights for prod, for the account level
Fixes UML-2205
=> App insights account prod

terraform/environment/terraform.tfvars.json
Re enable app insights for the enviroments in dev and demo
Fixes UML-2205
=> App insights env dev demo

terraform/environment/region/cloudwatch_data_protection_policy.tf
Change data protection policy from log group based, to account based.
Fixes UML-3685
=> Add account wide policy

terraform/environment/terraform.tfvars.json
Allows us to use mock one login temporarily until a permanent fix is in place
Fixes UML-3701
=> UML-3701: allow mock one login in preprod

service-front/app/src/Common/src/Service/Lpa/ParseLpaData.php, service-front/app/test/CommonTest/Service/Lpa/ParseLpaDataTest.php
_making combined lpa available for other tickets_
Fixes UML-####
_outputting a mocked combined lpa for lpa data formatter to use_
=> returning mocked combined lpa data for the frontend

.github/workflows/path-to-live.yml
Reverts ministryofjustice/opg-use-an-lpa#2919
=> Revert "Remove conditional if"

.github/workflows/path-to-live.yml
Move checkout action for workflow vars
Fixes UML-3704
=> move checkout action

terraform/environment/region.tf, terraform/environment/region/data_sources.tf, terraform/environment/region/variables.tf, terraform/environment/terraform.tfvars.json, terraform/environment/variables.tf
Update the ecr image version, so that we are not hard coding versions. This has led to us using expired versions in the past, which has broken deployments to prod
Fixes UML-3612
=> update container version

service-front/web/src/index.js, service-front/web/src/javascript/copyAccessCode.js, service-front/web/src/javascript/copyAccessCode.test.js, service-front/web/src/javascript/header.js
Fixes UML-3703
JEST tests do not like async and await when using fake timers!
=> Add modern clipboard API copy. Adjust tests.

docs/architecture/decisions/0024-library-for-lpa-data-mapping.md
_Document to provide decision making of choosing the EventsaucePHP Object Hydrator https://github.com/EventSaucePHP/ObjectHydrator?tab=readme-ov-file_
=> EventsaucePHP Object Hydrator ADR

service-front/web/package-lock.json
=> bump micromatch

terraform/account/region/waf.tf
Moves the custom rate limit from `count` to `block`. This shouldn't have any effect on real users.
Fixes UML-3694
=> UML-3694: enforce rate limit rule

.github/workflows/_build-and-push.yml
Add no cache to lambda image
Fixes UML-3714
=> Add no cache to lambda image

terraform/account/kms.tf
Adds kms key ready for sqs & eventbridge use
Fixes UML-3722
=> add sqs kms key

terraform/account/region/modules/lambda_function/iam.tf, terraform/account/region/modules/lambda_function/variables.tf
Updated logic in the lambda module for how the policy is created 
Fixes UML-3733
=> Update lambda policy

docker-compose.dependencies.yml, docker-compose.yml
Fixes typo for `event-receiver` and bumps the `pdf-service` version
Fixes UML-3727
=> fix typo and bump pdf service

.github/workflows/path-to-live.yml
Forces the end of workflow to run
Fixes UML-3762
=> UML-3762: ensure end of workflow runs

service-admin/README.md
Adding instruction to service admin readme, for how to add a new user to the admin portal
Fixes UML-3772
=> Adding instruction to service admin

query/dynamodb_export.py
_Add report of how many accounts have how many LPAs, to monthly reports_
_Add and extra Sql Select, tested by hand on athena in AWs console and by running python script by hand as is done each month_
=> UML-3683 add lpas count report to monthly reports script

terraform/account/kms.tf
=> UML-3738: allow updated key policy

terraform/account/kms.tf
Missing the action on the kms key
Fixes UML-3738
=> UML-3738: add missing action

terraform/account/kms.tf
Unblock pipeline while we find a better solution
Fixes UML-3738
=> UML-3738: remove lambda from key policy

service-front/app/config/autoload/templates.global.php, service-front/docker/web/default.conf.template, tests/smoke/behat.yml, tests/smoke/composer.lock, tests/smoke/context/AccountContext.php, tests/smoke/context/CommonContext.php
Move nonce value up a layer in the virtual server stack so that it ca…n be used in CSP variable calculations
Fixes UML-3607
The extra layer of virtual servers added to fix our iOS issue caused this to break because the header value was being removed at a level where it wasn't being seen by the CSP variables.
* I have added relevant and appropriately leveled logging, **without PII**, to my code
* I have updated documentation (Confluence/GitHub wiki/tech debt doc)
* I have run an accessibility tool on any pages I have made changes …
=> Fix CSP nonce headers not being set correctly

terraform/account/locals.tf, terraform/account/region.tf, terraform/account/region/s3_lb_access_logs.tf, terraform/account/region/variables.tf, terraform/account/region/vpc_flowlogs.tf, terraform/environment/locals.tf, terraform/environment/region/api_ecs.tf, terraform/environment/region/data_sources.tf
Reverts ministryofjustice/opg-use-an-lpa#3101
=> Revert "UML-3808: allow api ecs access to secretsmanager"

terraform/account/kms.tf
=> remove whitespace to trigger pipeline

service-front/app/src/Actor/templates/actor/partials/new-use-service.html.twig, service-front/app/src/Viewer/templates/viewer/new-view-service.html.twig
_Change link to feedback survey as it has moved_
_change href in twig files_
=> UML-3811 and UML-3810 change survey links

.github/workflows/scheduled-update-demo.yml, .github/workflows/trivy_scan_alert_report.yml
Attempt at fixing scheduled action by changing last user commit
Fixes UML-3842
=> UML-3842: update scheduled action

.github/workflows/trivy_scan_alert_report.yml
=> UML-3842: change cron

terraform/environment/terraform.tfvars.json
We know the service will get a lot of traffic, so we need to scale up in preparation of meeting the surge of demand.
Fixes UML-3857
=> UML-3857: scale up in prep for Money Show feature

renovate.json
enable github actions digest helper so it follows releases and updates comments
=> Update renovate config for github action pinning

terraform/environment/terraform.tfvars.json
Point demo environment at demo lpastore and use mock one login instead of integration
Fixes UML-3860
* ~I have added relevant and appropriately leveled logging, **without PII**, to my code~
* ~I have updated documentation (Confluence/GitHub wiki/tech debt doc)~
* ~The product team have tested …
=> UML-3860 Configure demo environment to point to demo lpastore

terraform/environment/terraform.tfvars.json
Reset our scaling to normal after the Money Show feature
Fixes UML-3857
=> UML-3857: reset scaling to normal

tests/features/user-journeys-start-on-gov-uk.feature
fixing failing build - updated user-journeys-start-on-gov-uk.feature test
=> UML-3785 fixed build 

.github/workflows/_build-and-push.yml, .github/workflows/golang-linting.yml, service-admin/.golangci.yml, service-admin/Dockerfile, service-admin/internal/server/handlers/handler_test.go, service-admin/internal/server/handlers/search.go, service-admin/internal/server/handlers/search_test.go, service-admin/internal/server/server.go
Fixes UML-3624
- Running hadolint against docker file_
- update golangci-lint version in linting action
- migrate golangci0lint config to version v2
- https://golangci-lint.run/product/migration-guide/
- https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#golangci-lint-action
- https://github.com/hadolint/hadolint-action
=> Running hadolint against docker file

service-front/docker/app/Dockerfile
Fixes UML-3887
_DL3022 - COPY --from should reference a previously defined FROM alias_
=> UML-3887 lint docker files

service-api/app/src/App/src/Entity/Lpa.php, service-api/app/src/App/src/Service/Lpa/AccessForAll/AddAccessForAllLpa.php, service-api/app/src/App/src/Service/Lpa/RestrictSendingLpaForCleansing.php, service-api/app/src/App/src/Service/Lpa/RestrictSendingLpaForCleansing/RestrictSendingLpaForCleansingInterface.php, service-api/app/src/App/src/Service/Lpa/SiriusLpa.php, service-api/app/src/App/src/Service/Lpa/ValidateAccessForAllLpaRequirements.php, service-api/app/test/AppTest/Service/Lpa/AddAccessForAllLpaTest.php, service-api/app/test/AppTest/Service/Lpa/CombinedSiriusLpaTest.php, service-api/app/test/AppTest/Service/Lpa/RestrictSendingLpaForCleansingTest.php, service-api/app/test/AppTest/Service/Lpa/SiriusLpaTest.php, service-api/app/test/AppTest/Service/Lpa/ValidateAccessForAllLpaRequirementsTest.php
Fixed call to undefined method App\Entity\LpaStore\LpaStore::toArray()
and implemented interface 
Fixes UML-3870
=> implemented interface supporting new and old sirius format

service-api/app/features/context/Integration/LpaContext.php, service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php, service-api/app/src/App/src/Service/ActorCodes/ValidatedActorCode.php, service-api/app/src/App/src/Service/Lpa/AddLpa/AddLpa.php, service-api/app/test/AppTest/Service/ActorCodes/ActorCodeServiceTest.php, service-api/app/test/AppTest/Service/Lpa/AddLpaTest.php, service-api/app/test/BehatTest/LpaTestUtilities.php
Refactor ActorCodeService to work with combined format
No interfaces as it's a bit complicated here for those. But usage of return objects
Fixes UML-3786
=> UML-3786 Add by code fixes for combined format

query/README.md
_updated readme to be clearer_
=> updated readme for monthly report stats

localstack/Dockerfile
=> fix golang version

scripts/pipeline/check_ecr_scan_results/aws_ecr_scan_results.py
=> ignore cve for all repos not just upload stats

service-api/docker/app/Dockerfile, service-api/docker/web/Dockerfile, service-front/docker/app/Dockerfile, service-front/docker/web/Dockerfile
Updates Docker images with Hadolint suggestions
Fixes UML-3927
=> UML-3927: update docker images

service-front/web/package-lock.json, service-front/web/package.json
Reverts ministryofjustice/opg-use-an-lpa#3263
Live service breakage
=> Revert "Renovate Update govuk-one-login-service-header digest to 8d977bc"

renovate.json
=> fix typo in renovate config

lambda-functions/event-receiver/Dockerfile, lambda-functions/upload-statistics/Dockerfile
Updates libxml2 package
Fixes UML-3942
=> UML-3942: update libxml2

terraform/environment/terraform.tfvars.json
=> Fix LPA Codes demo endpoint

terraform/environment/region/application_insights.tf, terraform/environment/region/variables.tf, terraform/environment/terraform.tfvars.json, terraform/environment/variables.tf
Re-implements application insights
Fixes UML-3962
=> UML-3962: implement app insights

terraform/account/region/elasticache.tf
Upgrades redis to 7.x
Fixes UML-3948
=> UML-3948: Upgrade to Redis 7.x

service-admin/Dockerfile, service-admin/go.mod, service-admin/proxy/Dockerfile, service-admin/proxy/go.mod
=> Bump golang version. Correct case in AS.

.github/workflows/golang-linting.yml, .pre-commit-config.yaml, lambda-functions/event-receiver/Dockerfile, lambda-functions/event-receiver/go.mod, localstack/Dockerfile
Docker digest updates. Remove redundant pre-commit.
=> Golang 1.24.4 event receiver

.github/workflows/php-linting.yml, .github/workflows/psalm-static-analysis-front.yml, service-front/app/composer.json, service-front/app/composer.lock, service-front/app/features/context/Integration/AccountContext.php, service-front/app/features/context/Integration/LpaContext.php, service-front/app/features/context/Integration/ViewerContext.php, service-front/app/features/context/UI/AccountContext.php, service-front/app/features/context/UI/CommonContext.php, service-front/app/features/context/UI/LpaContext.php, service-front/app/features/context/UI/RequestActivationKeyContext.php, service-front/app/features/context/UI/ViewerContext.php, service-front/app/src/Viewer/src/Handler/PaperVerification/CheckLpaCodeHandler.php, service-front/docker/app/Dockerfile
Upgrade PHP to 8.3 to stay in support and add language features for development
Fixes UML-3085
- Update required PHP in composer.json with composer
- Update Dockerfile to use the appropriate current image and library versions
=> UML-3085 Move service-front to PHP 8.3

service-front/docker/app/Dockerfile
Updates icu to currently used version in alpine3.22
Fixes UML-3996
=> UML-3996: update icu  ver

docs/runbooks/reextract-an-lpa-scan.md
=> test docs path

.github/workflows/_slack-notification.yml, .github/workflows/path-to-live.yml, scripts/pipeline/post_release_slack_notification/documentation_update.txt, scripts/pipeline/post_release_slack_notification/production_release.txt
=> UML-4026: fix docs workflow

docs/runbooks/reextract-an-lpa-scan.md
=> test docs only

.github/workflows/statistics.yml
Moves the stats into a dedicated channel
Fixes UML-4029
=> UML-4029: move stats to opg-lpa-stats

lambda-functions/upload-statistics/.trivyignore.yaml
Remove ignores on CVEs that should now be fixed to allow the security tab to be updated
- remove 3 CVEs related to libxml
- https://trivy.dev/dev/docs/configuration/filtering/#trivyignoreyaml
=> remove fixed CVEs

.github/workflows/path-to-live.yml
Prevent the failed deployment message in channel
Adds an additional logic step to running the slack notify - at the moment, both will run on docs pipeline.
=> update slack notification logic
