ministryofjustice/opg-use-an-lpa

README.md, docker-compose.yml, local-config/config.sh, terraform_environment/viewer_ecs.tf
Also added the relevant local variable, `DYNAMODB_TABLE_VIEWER_CODES`, for accessing it, both locally and in AWS.
Added missing API unit test line into the README
=> Added local DynamoDB table for Viewer Codes

service-api/app/src/App/src/Handler/ActorCodeConfirmHandler.php, service-api/app/src/App/src/Handler/ActorCodeSummaryHandler.php, service-front/app/src/Actor/src/Handler/CheckLpaHandler.php, service-front/app/src/Common/src/Service/Lpa/LpaService.php, service-front/app/test/ActorTest/Handler/CheckLpaHandlerTest.php, service-front/app/test/CommonTest/Service/Lpa/LpaServiceTest.php
The new API layer broke the addition of LPAs to an account (well, the summary page at least, fully adding the LPAs has never worked)
This updates the controller and service layer to work with the new API return values and endpoints.
=> Uml 269 fix add an lpa with new api

service-api/app/src/App/src/DataAccess/DynamoDb/ActorUsers.php, service-api/app/src/App/src/DataAccess/Repository/ActorUsersInterface.php, service-api/app/src/App/src/Handler/UserHandler.php, service-api/app/src/App/src/Service/User/UserService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/ActorUsersTest.php, service-api/app/test/AppTest/Handler/UserHandlerTest.php, service-api/app/test/AppTest/Service/User/UserServiceTest.php, service-api/docker/seeding/start.sh, terraform/environment/dynamodb.tf
In order to get dashboards working we need to attach individual lpas to actor accounts. It is not possible to do this with email so this PR ensures unique id's for users instead. We'll be able to use them for assigning LPA's to accounts.
=> Uml 199 move to id for users

README.md, service-front/docker/web/Dockerfile, service-front/web/.gitignore, service-front/web/package.json
This branch will build out the assets as defined in the `src` directory in `web` on a production build. Locally you run a watch command which will automatically build the assets for you.
I have updated the readme with instructions of the extra step required to run the webpack command.
Ideally I wanted Docker when run locally to automatically do this for us but I don't have the knowledge one whether this would be possible at the moment.
=> Configured Dockerfile to build front end assets

service-api/app/config/pipeline.php, service-api/app/config/routes.php, service-api/app/src/App/src/Handler/ActorCodeConfirmHandler.php, service-api/app/src/App/src/Middleware/UserIdentificationMiddleware.php, service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php, service-front/app/src/Actor/src/Handler/CheckLpaHandler.php, service-front/app/src/Common/src/Entity/User.php, service-front/app/src/Common/src/Service/ApiClient/Client.php, service-front/app/src/Common/src/Service/ApiClient/ClientFactory.php, service-front/app/src/Common/src/Service/Lpa/LpaService.php, service-front/app/src/Common/src/Service/User/UserService.php, service-front/app/test/ActorTest/Handler/CheckLpaHandlerTest.php, service-front/app/test/CommonTest/Entity/UserTest.php, service-front/app/test/CommonTest/Service/ApiClient/ClientTest.php, service-front/app/test/CommonTest/Service/Lpa/LpaServiceTest.php, service-front/app/test/CommonTest/Service/User/UserServiceTest.php
Ensure that we're passing through appropriate user context when attempting some actions that require it.
=> Uml 214 send appropriate user id to api

docker-compose.yml, service-front/docker/web/Dockerfile, service-front/web/babel.config.js, service-front/web/package-lock.json, service-front/web/package.json, service-front/web/src/index.js, service-front/web/src/pdf-scss.js, service-front/web/src/pdf.js, service-front/web/src/pdf.scss, service-front/web/src/scss.js, service-front/web/webpack.pdf.common.js, service-front/web/webpack.pdf.development.js, service-front/web/webpack.pdf.js, service-front/web/webpack.pdf.production.js
This branch uses webpack to build out a seperate CSS file for use in the PDF Service. It takes the latest styles and fonts then base64 encodes the fonts into the CSS for faster processing of the PDF document.
=> Uml 325 css fonts pdf

service-front/app/features/actor-account-creation.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Form/CreateAccount.php, service-front/app/src/Actor/templates/actor/create-account.html.twig, service-front/app/test/ActorTest/Form/CreateAccountTest.php, service-front/app/test/ActorTest/Handler/CreateAccountHandlerTest.php
Remove email confirmation box on account creation page to meet GDS guidelines
Fixes UML-311
Removed the email confirmation box and related validation on the account creation form. Updated unit tests and feature tests accordingly 
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a LPA service_
=> Removed email confirmation box, updated unit and feature tests

terraform/environment/actor_ecs.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json, terraform/environment/viewer_ecs.tf
Each front end wants to have independant session expiry values, and developers would like the ability to have shorter expiry times on dev environments to make it easier to test.
Fixes UML-536
Use the account level variables to set a session expiry value, and pass that value into each front end's ECS containner definition.
This PR does not affect the current session expiry, onnly provides a new place to retrieve a value from.
=> add SESSION_EXPIRES env var for view and use tasks

.circleci/config.yml
Keep up to date with the latest versions of Terraform
Remove tag for Terraform Docker image in CircleCI so that the latest version is always used.
=> remove tag for terraform to unpin and always use the latest version

.circleci/config.yml
Provide useful information about what has changed when posting slack messages
Adds `$COMMIT_MESSAGE` and colours the posts to make them stand out in slack from the other products.
=> add commit messages and colour to UAL slack messages

features/modules.py, features/steps/viewer.py, features/view-an-lpa.feature, terraform/environment/actor_load_balancer.tf, terraform/environment/viewer_load_balancer.tf
Users have reported that the service is not working when they don't use `https://` in the service URLs. The service is only listening for `https://` requests.
Fixes UML-531
This PR adds a listener rule to each load balancer to redirect the user to `https://` if they omit it.
=> add listener rule to redirect port 80 to port 443

service-front/app/src/Viewer/templates/viewer/home-page.html.twig
To remove the link to the lpa service on the viewer home page as from research some users are unnecessarily following the link which takes them away from the service and interrupts their journey
Fixes UML-484
Removed the link so that 'lasting power of attorney' is just text
=> removed govuk link on viewer home page

.circleci/config.yml
set scheduled jobs on CircleCI to run against master branch only
Fixes UML-517
=> make sure scheduled jobs only runs on master branch

features/environment.py, service-front/app/features/actor-login.feature, service-front/app/features/context/Integration/AccountContext.php, service-front/app/features/context/UI/AccountContext.php
To add feature tests to cover the scenario of a returning user logging in, having logged in previously, and being taken to the dashboard page (rather than the add an LPA page)
Fixes UML-565
Written scenario steps for the front ui and integration. For the step 'I have logged in previously', I set the LastLogin value to null to represent their first ever login (even though their previous login doesn't necessarily mean their first ever login) and had this changed to a date time in the step 'When I sign in' to show the difference in response from the first login and how that should affect the redirect
=> Uml 565 dashboard on login feature test

service-api/app/src/App/src/Command/ActorCodeCreationCommandFactory.php
So calls to $container->get('trace-id') do not fail.
The actorcode generation was failing due to logging code changes, this fixes that case.
Fixes UML-574
Attaches a CLI specific trace-id into the container when building the code creation Symfony command.
=> Set a CLI specific trace-id into the container

service-front/app/config/routes.php, service-front/app/features/context/UI/ViewerContext.php, service-front/app/features/viewer-terms-of-use.feature, service-front/app/src/Viewer/src/Handler/ViewerTermsOfUseHandler.php, service-front/app/src/Viewer/templates/viewer/enter-code.html.twig, service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig, service-front/web/package-lock.json
Added the terms of use page on the viewer side of the service. The link to the terms of use is on the enter code page
Fixes UML-582
Created the new page, with a handler and added a route in the routes file. Then added the new text and link to the enter code page. Finally I created 2 feature tests, the first checks that the user is taken to the terms of use page from the enter code page by clicking the link. The second test checks that the user is taken back to the enter code page when they click the "back" button on the terms of use page
=> Uml 582 viewer terms of use

service-api/app/features/actor-create-access-code.feature, service-api/app/features/context/Acceptance/AccountContext.php, service-api/app/features/context/Integration/AccountContext.php, service-front/app/features/actor-create-access-code.feature, service-front/app/features/context/Integration/AccountContext.php, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Handler/CheckAccessCodesHandler.php
Fixes UML-563
Added feature tests to cover the scenario : When user has not created an access code , it should display to the user relevant message and show them an option to create one if needed.
=> UML-563 Added tests to cover the single scenario when access code not created

zap/Dockerfile
To fix an issue with Zap DockerFile that was causing issues locally when spinning up in docker-compose. This does not commission the docker file to run the zap scripts it has yet.
- Upgrade PIP to PIP3 and add some prerequisites and no-cache to prevent warnings.
- add an Apk upgrade to prevent vuln creep.
- Made the docker file clearer in terms of steps taken by running each step separately.
- general research around docker and python:
https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources 
https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Upgrade_a_Running_System
- also, what is zap? 
https://www.zaproxy.org/
=> fix up python version to 3 and add apk upgrade

service-front/app/src/Common/src/Form/AbstractForm.php
Updating warning message on session time out from 60 to 20
Fixes UML-####
=> Updated session timeout message from 60min to 20min

service-front/app/src/Actor/src/Handler/CheckLpaHandler.php, service-front/web/package-lock.json
This fixes the bug for donors not being able to add an lpa to their account.
Fixes UML-641
The 'resolveLpaData' function takes in the lpa found and the DOB entered. It compares the DOB entered to the DOB of the donor and attorney(s) in the LPA to assess who the user adding the LPA is and their role on the LPA. The bug was found in the comparison of the donor's DOB on the LPA and the DOB entered into the form, as the identical operator was used (===) instead of the equal operator (==) which is used for the attorneys comparison. The DOB's do not pass as identical here as they are not from the same class 
The comparison operator:
https://www.php.net/manual/en/language.oop5.object-comparison.php
=> BUG - Donor unable to add an LPA

service-front/app/features/actor-add-an-lpa.feature, service-front/app/features/context/Integration/AccountContext.php, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Form/LpaAdd.php
We are not treating codes as case-insensitive when looking them up to add LPAs.
(Partially) fixes [UML-621](https://opgtransform.atlassian.net/secure/RapidBoard.jspa?rapidView=149&projectKey=LPA&modal=detail&selectedIssue=UML-621)
It changes the data access layer to uppercase codes before calling DynamoDB.
=> Ensure actor codes are used as uppercase

service-front/web/src/javascript/disableButtonOnClick.js, service-front/web/src/javascript/disableButtonOnClick.test.js
With the introduction of UML-446 we now need a way to test javascript related functionalities. ~Behat can do this but setup and configuration needs to happen so it can work in our environment.~
Fixes UML-549
I've added a Jest test for the function that was added in UML-446. I know this ticket talked about setting up Behat to run the tests but I don't think that is workable without a lot of changes. Since the JavaScript lives in the `web` side and we have Behat set up on the `app` side, we'd probably want to run Behat at a different "level" for these tests (like the `features` folder?). 
I did get Selenium setup, running Behat tests, with the app spun up as you would for locally playing around. Using the `@javascript` tag to only run the single test I added worked. But I don't think it is …
=> Add tests for disable button on click function

service-front/app/features/context/UI/AccountContext.php, service-front/app/features/donor-dashboard.feature, service-front/app/src/Actor/src/Handler/LpaDashboardHandler.php, test-data/api-gateway.json
Fix donors who added LPAs being able to see the dashboard. 
Fixes UML-679
The response for a donor doesn't seem to include `systemStatus`, which was naively being checked to see if the actor was active. I've changed it to check whether the actor is a donor first.
=> Handle dashboard status check when actor is the donor

terraform/environment/cloudwatch_alarms.tf
Monitor and alert team when there are 5xx errors being returned to users.
Fixes UML-673
Use a cloudwatch metric alarm to monitor absolute values within a time window. This is preferable for this service over percentage of errors.
=> UML-673 - Create a cloudwatch alarm for viewer 5xx errors

scripts/call-api-gateway/.envrc, scripts/call-api-gateway/README.md, scripts/call-api-gateway/call_api_gateway.py
The Sirius API Gateway IAM policies have been updated to allow UaL operator roles to execute requests. 
This means that individuals no longer have to assume the out of pattern `sirius-api-gateway-access-use-an-lpa role`, and permission to use the gateway is set up when new members are onboarded into the team.
To support this the IAM role and AWS account id used by the call-api-gateway script are updated and brought inside the script.
Update script to choose endpoint to call and role to assume using an argument flag.
=> Call API Gateway Script Update

.circleci/config.yml
There is a missing requirement on the path to live for UAL.the preprod and prod apply environment jobs should require pdf_build.
Fixes UML-605
It adds `pdf_build` to the `requires` list for the relevant jobs.
=> UML-605 Require pdf_build for prod and pre-prod terraform apply jobs

.circleci/config.yml
Splits the workflow into pr_build and path_to_live with their relevant jobs
Fixes UML-576
Duplicated existing path to live workflow renamed 'pr_build', and removed jobs that were not relevant to the pr build (master only filter). Repeated the opposite for the path to live workflow, removing irrelevant jobs containing ignore master filter
=> split circle ci workflow

docker-compose.yml
To Fix the Docker file for the front-composer, which requires the --ignore-platform-reqs flag.Associated with UML-300 Brute force changes.
Fixes UML-300
Add the additional flag to the docker-compose file for front-composer. 
There are also auto-linting changes here.
N/A
=> fix docker file composer flag

terraform/environment/actor_ecs.tf
Fix issue with live actor side not finding redis elasticache
Why didn't the pipeline find this?
=> Configure actor ecs with elasticache details.

service-api/app/src/App/src/Handler/LpasCollectionHandler.php
To place @codecoverageignore tag onto any Service-API handlers that can be done.
Fixes UML-617
- 1 handler had this change made. 
- There are no feature tests for the exception paths in most cases, with one happy path scenario missed. 
- The linked tickets cover the handlers to have these covered. 
- Where a @codecoverageignore is missed or not,  it has been noted on each of the tickets.
as above 😄 
Turns out to be 1 only where this could be done. We discovered a load of exception paths that need testing, and tickets have been raised in the backlog for this. it may be the tickets need further analysis, and amalgamation may be possible in some cases e.g. when some of the testing paths are similar.
=> UML-617 add code coverage ignore on LpasCollectionHandler

service-api/app/features/context/Acceptance/AccountContext.php, service-api/app/features/context/Integration/AccountContext.php
To Fix tests that fail erroneously around code generation, if run around midnight BST.  
The code expiry dates are being generated in Europe/London Timezone.
However, tests are not taking this into account, testing with an expected date in UTC. 
This fix is to align the expectation correctly with the actual. 
***No functional code was changed, only Behat tests.***
Fixes UML-757
- Use the correct date time zone.
- update date notation to a relative date and time.
- This was tested locally with the changes and by setting the local machine time to midnight (00:00:00). 
- Also tested by running with current date-time.
`DateTimeZone` format
https://www.php.net/manual/en/class.datetimezone.php
`DateTime` formats
https://www.php.net/manual/en/datetime.formats.php
=> UML 757 rework test expectations for code generation to include timezone

terraform/account/cloudwatch.tf, terraform/account/locals.tf, terraform/account/terraform.tfvars.json
Logs should only be kept for as long as they are needed
Fixes UML-748
Add a log retention policy to the AWS Log Group.
Set the number of days based on the account.
After the number of days, log events in the AWS Log Group will automatically be deleted by AWS Cloudwatch.
=> Uml 748 log retention

terraform/environment/actor_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/code_creation_ecs.tf, terraform/environment/pdf_ecs.tf, terraform/environment/viewer_ecs.tf
Finding the correct logs for your environment in the development account can be difficult because they all share the same log group and stream prefix.
Fixes UML-749
Add the environment name to the AWS logs stream prefix.
Now in Cloudwatch Insights, you can isolate logs using 
```
filter @logStream like /(?i)(environment_name)/
```
=> add environment name to the awslog stream prefix

service-api/app/src/App/src/Service/ViewerCodes/CodeGenerator.php, service-api/app/test/AppTest/Service/ViewerCodes/CodeGeneratorTest.php
To Remove Z and 2 from the code generator, which is ambiguous to our users. 
We do not validate that these characters are valid on entry, as there may still be codes out there that use these.
Fixes UML-750
- Remove the characters Z and 2 from the generator
- Adjust PHPUnit Test to match.
N/A
=> Uml-750 remove Z and 2 chars from code gen

scripts/generate_actor_codes/README.md, scripts/generate_actor_codes/transform-lpa-json.jq
- Add a jq transform file that will format the LPA id's and actor codes automatically in the correct format.
- To make our dev lives a little easier 😄 
- Add a jq filter transform file that will take the `json_output` as mentioned in the readme and edit in place the fields needed. 
- The structure of the json changes slightly but shouldn't be an issue for the business to use.
- update readme with new details of what to do.
using Jq play and jq Term to work out from a dummy set of data how to do it.
- https://jqterm.com/
- https://jqplay.org/
also using the manuals and docs:
- https://stedolan.github.io/jq/
Stack Exchange 😃 
- https://stackoverflow.com/questions/55048593/replacing-values-in-json-with-jq-and-regex
=> Improve lpa code json parse for code generation

.circleci/config.yml
Turn on asynchronous workspace cleanup
Enable a scheduled job that will list out and select each workspace, then the default workspace.
After this is shown to be working ok, the cleanup actions can be enabled also.
=> Turn on asynchronous workspace cleanup

terraform/account/certificate.tf, terraform/environment/shared_data_sources.tf
The environment build is looking for a certificate that is not required.
Fixes UML-807
Remove the data sources for the certificates in the Terraform environment configuration.
Remove the certificates from the Terraform account configuration
=> UML-807 - Remove unused certificates

.circleci/config.yml
If CircleCI is a bit congested, there can be a long delay between jobs on the pipeline. If the delay occurs between a successful Terraform environment apply and marking the environment as protected, it is possible that the automated cleanup can remove a brand new environment.
Move the command to mark the environment (workspace) as protected inside the job to apply the environment (ideally, before the "environment apply" is attempted).
=> bring 'mark workspace protected' into 'apply dev env'

service-front/app/src/Actor/src/Form/CreateAccount.php, service-front/app/src/Actor/src/Form/Login.php, service-front/app/src/Actor/src/Form/PasswordResetRequest.php, service-front/app/src/Actor/templates/actor/login.html.twig, service-front/app/src/Actor/templates/actor/password-reset-request.html.twig, service-front/app/src/Common/src/View/Twig/GovUKLaminasFormExtension.php, service-front/app/src/Common/templates/partials/govuk_form.html.twig, service-front/app/test/ActorTest/Form/CreateAccountTest.php, service-front/app/test/ActorTest/Form/LoginTest.php, service-front/app/test/ActorTest/Form/PasswordResetRequestTest.php
Allows the use of the Form Email type and updates existing components. Will show the email keyboard on mobile devices.
Fixes UML-686
Adds the Email type to the list of available field Types
None
=> Uml 686 email input

service-api/app/features/context/Acceptance/AccountContext.php, service-api/app/features/context/Integration/AccountContext.php, service-api/app/src/App/src/ConfigProvider.php, service-api/app/src/App/src/Exception/ActorCodeMarkAsUsedException.php, service-api/app/src/App/src/Exception/ActorCodeValidationException.php, service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php, service-api/app/src/App/src/Service/ActorCodes/CodeValidationStrategyInterface.php, service-api/app/src/App/src/Service/ActorCodes/DynamoCodeValidationStrategy.php, service-api/app/src/App/src/Service/Lpa/LpaService.php, service-api/app/test/AppTest/Service/ActorCodes/ActorCodeServiceTest.php, service-api/app/test/AppTest/Service/ActorCodes/DynamoCodeValidationStrategyTest.php, service-api/app/test/AppTest/Service/Lpa/LpaServiceTest.php
Abstracts our actor one time use code usage and verification out into a strategy interface so that we can replace it with the new microservice that deals with those things
Fixes UML-817
Creation of a new `CodeValidationStrategyInterface` and associated `DynamoCodeValidationStrategy` to migrate our existing strategy to the new interface.
=> Uml 817 abstract out code verification

service-front/app/src/Common/templates/partials/govuk_form.html.twig
Adds further inbuilt virutal keyboard functionality for email addresses
Fixes UML-865
Implements the DAC report suggestions
Cool stuff here for how you can take advantage of other field types https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
=> Added inputmode=email for native keyboards

service-front/app/src/Actor/templates/actor/activate-account-not-found.html.twig, service-front/app/src/Actor/templates/actor/actor-terms-of-use.html.twig, service-front/app/src/Actor/templates/actor/change-details.html.twig, service-front/app/src/Actor/templates/actor/check-access-codes.html.twig, service-front/app/src/Actor/templates/actor/confirm-cancel-code.html.twig, service-front/app/src/Actor/templates/actor/confirm-delete-account.html.twig, service-front/app/src/Actor/templates/actor/home-page.html.twig, service-front/app/src/Actor/templates/actor/instructions-preferences.html.twig, service-front/app/src/Actor/templates/actor/login.html.twig, service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Actor/templates/actor/lpa-blank-dashboard.html.twig, service-front/app/src/Actor/templates/actor/lpa-create-viewercode.html.twig, service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig, service-front/app/src/Actor/templates/actor/lpa-not-found.html.twig, service-front/app/src/Actor/templates/actor/lpa-removed.html.twig, service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig, service-front/app/src/Actor/templates/actor/password-reset-request-done.html.twig, service-front/app/src/Actor/templates/actor/start-page.html.twig, service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig, service-front/app/src/Actor/templates/actor/your-details.html.twig, service-front/app/src/Viewer/templates/viewer/check-code-cancelled.html.twig, service-front/app/src/Viewer/templates/viewer/check-code-expired.html.twig, service-front/app/src/Viewer/templates/viewer/check-code-found.html.twig, service-front/app/src/Viewer/templates/viewer/enter-code.html.twig, service-front/app/src/Viewer/templates/viewer/home-page.html.twig, service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig, service-front/web/src/scss/_lpa-typography.scss
It was requested that Acronym Markdown should be added in the alpha assessment. This will allow users to hover "LPA" and "LPAs" so alt text will be displayed explaining the meaning of these acronyms.
https://opgtransform.atlassian.net/browse/UML-873
Fixes UML-####
Find all instances of "LPA" and "LPAs" and change to:
`<abbr title="lasting power of attorney">LPA</abbr>`
and
`<abbr title="lasting powers of attorney">LPAs</abbr>`
N/A
=> add alt text to uses of LPA acronym

README.md, docker-compose.yml, service-api/docker/seeding/start.sh
LPA Codes seeding cannot run because of a duplication of the port in the waitforit command.
Remove extra port in command
=> Fix docker typos

.circleci/config.yml
Reduce the frequency of workspace cleanup jobs
Run twice during the day at 6am and 6pm instead of every two hours
=> clean up workspaces less frequently

service-front/app/config/routes.php, service-front/app/features/actor-privacy-notice.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Handler/ActorPrivacyNoticeHandler.php, service-front/app/src/Actor/templates/actor/actor-privacy-notice.html.twig, service-front/app/src/Actor/templates/actor/actor-terms-of-use.html.twig
Add a privacy notice to the Actor page.
Fixes UML-779
- new handler
- twig file with a privacy notice 
- routing
- behat tests
GDS styling: https://design-system.service.gov.uk/styles/
=> UML-779 Add Privacy notice to Actor front end

service-front/app/config/routes.php, service-front/app/features/context/UI/ViewerContext.php, service-front/app/features/viewer-privacy-notice.feature, service-front/app/src/Viewer/src/Handler/ViewerPrivacyNoticeHandler.php, service-front/app/src/Viewer/src/Handler/ViewerTermsOfUseHandler.php, service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig, service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
To Add Viewer Privacy notice
Fixes UML-780
- new handler
- twig file with a privacy notice 
- routing
- behat tests
GDS styling: https://design-system.service.gov.uk/styles/
=> UML-780 Added viewer privacy notice with links to /from ToU. 

service-front/app/src/Actor/src/Form/LpaAdd.php, service-front/app/src/Common/src/Form/Fieldset/DateTrimFilter.php, service-front/app/test/CommonTest/Form/Fieldset/DobTrimFilterTest.php
Fixes the issue of leading and trailing spaces entered into the date of birth fieldset
Fixes UML-875
- Add a custom filter in the same style as DatePrefixFilter
- Add PHPUnit Tests and cases for new filter
- data driven tests in PHP Unit using a dataProvider method
=> UML-875 Add a trim filter and php unit tests - also minor tidy up

service-front/app/config/pipeline.php, service-front/app/config/routes.php, service-front/app/features/common-session.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Handler/ActorSessionExpiredHandler.php, service-front/app/src/Actor/templates/actor/actor-session-expired.html.twig, service-front/app/src/Common/src/Middleware/Session/SessionExpiredAttributeAllowlistMiddleware.php, service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php, service-front/app/test/CommonTest/Middleware/Session/SessionExpiredAttributeAllowlistMiddlewareTest.php, service-front/app/test/CommonTest/Middleware/Session/SessionExpiredRedirectMiddlewareTest.php
Takes the user to a page to tell them why they were logged out when their session expires
Fixes UML-886
Created a new middleware that checks to see if the session expiry flag is present in the session, and redirects the user to the new page. Added the session expiry to the allow list in the SessionExpiredAttributeAllowlistMiddleware, and gave responsibility to the new SessionExpiredRedirectMiddleware to remove it.
=> Session expiry page

terraform/environment/terraform.tfvars.json
Enable lpa-codes service on preproduction
Fixes UML-914
Set the flag use_legacy_codes_service to false
=> enable lpa-codes on preproduction

terraform/account/elasticache.tf
***Part 3 of 3***:
Remove old brute force cache resource - covered by subtask UML-921
Fixes UML-804
- remove the terraform for the old brute force cache.
- more Terraform
=> UML-805 remove old brute force cache cluster

.circleci/config.yml, terraform/account/certificate.tf
Make it safer to create account-level resources in dev
Secure communications between users and our service.
Fixes UML-947
Only show the plan of account-level resources in dev during the pr-build workflow, and apply on path-to-live only.
Create a new set of certificates for the public-facing URLs.
=> UML-947 - Create Certificates

service-front/web/src/javascript/googleAnalytics.js, service-front/web/src/javascript/googleAnalytics.test.js
Fixes GA from sending PID in querystrings
Fixes UML-950
Manually override the url details to send on initial tracking of the page to strip the querystring out.
Ideally we want to not include PID in our urls but understand this is sometimes unpreventable.
=> Strips querystrings from page views in GA

service-front/web/src/javascript/googleAnalytics.js, service-front/web/src/javascript/googleAnalytics.test.js
Fixes an issue with path_name passing the full url rather than just the pages path.
Fixes UML-961
Removed the full url creation from the JS
=> Changed GA path_name to just path and not the full url

service-front/app/config/routes.php, service-front/app/features/actor-privacy-notice.feature, service-front/app/features/actor-terms-of-use.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/features/context/UI/ViewerContext.php, service-front/app/features/viewer-cookie-banner.feature, service-front/app/features/viewer-privacy-notice.feature, service-front/app/features/viewer-terms-of-use.feature, service-front/app/src/Actor/templates/actor/actor-privacy-notice.html.twig, service-front/app/src/Actor/templates/actor/actor-terms-of-use.html.twig, service-front/app/src/Actor/templates/actor/check-access-codes.html.twig, service-front/app/src/Actor/templates/actor/create-account.html.twig, service-front/app/src/Actor/templates/actor/lpa-show-viewercode.html.twig, service-front/app/src/Common/src/Handler/CookiesPageHandler.php, service-front/app/src/Common/src/Service/Url/UrlValidityCheckService.php, service-front/app/src/Common/templates/partials/cookies.html.twig, service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig, service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig, service-front/app/test/CommonTest/Service/Url/UrlValidityCheckServiceTest.php
The ticket's original purpose was to add content to the cookie preferences pages, however this content already exists. Instead this ticket now add's links to the terms of use and privacy policy pages to take the user to the cookie preferences pages
UPDATE - this ticket now also adds a back button to the cookies page with the functionality to take the user back to the page they were on before they visited the cookies page
Fixes UML-896
=> Link cookies page to terms of use and privacy policy

service-front/web/src/javascript/googleAnalytics.js, service-front/web/src/javascript/googleAnalytics.test.js
In some browsers location.pathname also send the querystring and isn't split into the search property. This means we are still being sent email addresses and other data.
Fixes UML-969
Added test case and fix to make it pass
=> Replace any strings after the first ? in a url for GA

service-front/web/package-lock.json, service-front/web/package.json
perfume.js has a known bug in their library that creates an error in the console where the PerformanceObserver does not disconnect correctly.
Upgrading the above package includes the fix for it. (1.1.1)
Fixes UML-970
Bump the version in the package.json file
=> Upgrade opg-performance-analytics to fix console error

.circleci/config.yml, service-front/docker/web/etc/confd/templates/nginx.conf, terraform/environment/actor_load_balancer.tf, terraform/environment/viewer_load_balancer.tf, tests/features/user-journeys-start-on-gov-uk.feature, tests/smoke/context/CommonContext.php
Users should start their journey from the gov.uk start page
Fixes UML-932
Add rules to the Application Load Balancer
Using referrers may be inconsistent
http://nginx.org/en/docs/http/ngx_http_referer_module.html
So instead we are performing a rewrite on the start page of the service.
http://nginx.org/en/docs/http/ngx_http_rewrite_module.html
https://www.liquidweb.com/kb/redirecting-urls-using-nginx/
=> UML-932 - Users should start their journey from the gov.uk start page

.circleci/config.yml, docker-compose.testing.yml, terraform/environment/actor_load_balancer.tf, terraform/environment/viewer_load_balancer.tf, tests/features/always-use-the-live-service-url.feature, tests/smoke/context/BaseContext.php, tests/smoke/context/CommonContext.php
Users should visit the service using the live service URL.
Fixes UML-905
Add a permanent redirect from `*.view-lasting-power-of-attorney.service.gov.uk` to `*.view.lastingpowerofattorney.opg.service.justice.gov.uk`
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html
=> rewrite private beta url to live service url

.circleci/config.yml
When running a check on the service health, use the correct fully qualified domain name.
When using the old fqdn, the http status is returned as 301 and as such fails the check.
Fixes UML-905
Update test in CircleCI config.
=> use the correct fqdn for healthcheck tests

service-front/app/features/actor-account-creation.feature, service-front/app/features/actor-login.feature, service-front/app/features/actor-password-reset.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Form/ChangeEmail.php, service-front/app/src/Actor/src/Form/CreateAccount.php, service-front/app/src/Actor/src/Form/Login.php, service-front/app/src/Actor/src/Form/PasswordResetRequest.php, service-front/app/src/Common/src/Form/Element/Email.php, service-front/app/src/Common/src/Validator/EmailAddressValidator.php, service-front/app/src/Common/src/View/Twig/GovUKLaminasFormExtension.php, service-front/app/test/ActorTest/Form/CreateAccountTest.php, service-front/app/test/ActorTest/Form/EmailChangeTest.php, service-front/app/test/ActorTest/Form/LoginTest.php, service-front/app/test/ActorTest/Form/PasswordResetRequestTest.php, service-front/app/test/CommonTest/Validator/EmailAddressValidatorTest.php, tests/features/actor-login.feature
Prevents the laminas email validator regex error from being displayed to the user if they do not enter a valid email address
Fixes UML-933
Creates a custom email element to attach the custom email validator and display the correct error messages to the user
=> Adds Custom Email component for better control of validation

terraform/account/credentials.tf, terraform/environment/credentials.tf
We're not yet ready to use the new version 3 of the aws provider for terraform. This PR will pin us to 2.70.0.
Fixes UML-989
add `version = 2.70.0` to each provider.
=> pin version of aws provider to 2.70.0

.circleci/config.yml, .idea/php.xml, service-front/app/composer.json, service-front/app/composer.lock, service-front/app/config/config.php, service-front/app/config/pipeline.php, service-front/app/config/routes.php, service-front/app/features/actor-cookie-banner.feature, service-front/app/features/common-language.feature, service-front/app/features/common-session.feature, service-front/app/features/context/UI/CommonContext.php, service-front/app/features/viewer-cookie-banner.feature, service-front/app/src/Common/src/ConfigProvider.php, service-front/app/src/Common/src/Middleware/I18n/SetLocaleMiddleware.php, service-front/app/src/Common/src/Middleware/I18n/SetLocaleMiddlewareFactory.php, service-front/app/test/CommonTest/Middleware/I18n/SetLocaleMiddlewareFactoryTest.php, service-front/app/test/CommonTest/Middleware/I18n/SetLocaleMiddlewareTest.php, service-front/docker/app/Dockerfile
Set system locale based on routing prefix. 
Default prefix (i.e. none) defaults to en_GB. A prefix of '/cy/' sets the Locale to 'cy_GB'. This is set both as a part of the system wide 'Locale::class' global object and also attached to the request as an attribute.
Fixes UML-991
A simple middleware based almost wholly on the Mezzio documentation. Sits before routing and extracts/removes the prefix before allowing it onwards. It sets a basepath onto the UrlHelper meaning that requests in the app for routes will automatically have the prefix set.
=> Uml 991 multilingual routing

service-front/app/src/Common/src/Service/Security/UserIdentificationService.php, service-front/app/test/CommonTest/Service/Security/UserIdentificationServiceTest.php
The algorithm that generated the identity key that is given to users was incorrect and quite fundamentally broken. This PR addresses that by reworking the algorithm to actually output a useful value.
The original algorithm used `implode` correctly on an incorrectly structured array. Resulting in a hash of the string "ArrayArrayArrayArrayArray". The array is now structured so that it contains the actual values. Something like;
`text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8gzip, deflateen-GB,en;q=0.5Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:78.0) Gecko/20100101 Firefox/78.0172.18.0.1`
Always verify string inputs to functions.
**Although the tests have been updated to get this PR to pass additional tests need writing to check that the expected header …
=> Fix to identity generation

.circleci/config.yml
Pin workspace cleanup terraform image to 0.12.29
=> pin the version of terraform used for workspace cleanup

terraform/account/credentials.tf, terraform/environment/credentials.tf
Provider installation is not consistant and introduces unintended upgrade of AWS provider.
Fixes UML-1027
Address the difference in behaviour between account and environment `terraform init` commands.
The issue is caused by the way that Terraform 0.13 references legacy providers using `-/`.
https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/draft-upgrade-guide.md
This is fixed by replacing the provider in the state file
```
tf state replace-provider registry.terraform.io/-/aws registry.terraform.io/hashicorp/aws 
tf state replace-provider registry.terraform.io/-/local registry.terraform.io/hashicorp/local 
tf state replace-provider registry.terraform.io/-/pagerduty registry.terraform.io/terraform-providers/pagerduty 
```
I have written a script to do this for all environments.
=> work around difference in provider installation behaviour

README.md, docker-compose.dependencies.yml
To fix an issue where we have problems retrieving LPACollections data on local dev enviroments
Fixes Dev environments locally.
- Add `PASSTHROUGH_` env vars relating to aws credentials
- update Readme with troubleshooting section to solve further issues manually.
found similar issue here: https://github.com/localstack/localstack/issues/528#issuecomment-356453460
from slack conversation: 
https://mojdt.slack.com/archives/CAQ3T5JFQ/p1597404794306100
"... We've added a bunch of PASSTHROUGH_ variables relating to aws, this is based on conversation yesterday to try this. but we'd not got that format quite right. on digging in the gateway code it mentions the above prefix, so proceeded to add that. this solved the problem, and a PR is to follow to fix that. here are the env vars:
``` shell …
```
=> DEV FIX: Fix dev seeding lpa add issues

docs/pull_request_template.md, docs/runbooks/maintenance_mode/README.md, docs/runbooks/maintenance_mode/manage_maintenance.sh, terraform/environment/actor_load_balancer.tf, terraform/environment/credentials.tf, terraform/environment/viewer_load_balancer.tf
Upgrade environment Terraform AWS provider to v3
Fixes UML-1031
Work through upgrade guide and address conflicts.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade
The change in how loadbalancer listener rule conditions are defined means the conditional setting of `field` and `values` is no longer possible in the same way. 
Instead, I have created just a single rule that sets a fixed response when the path_pattern is`/maintenance`. I've set the condition on this rule to be ignored after creating it. This allows a script to enable maintenance and a deployment (perhaps intended to fix the reason for maintenance) to not make the service live again. Only the maintenance script can put the service live again.
In addition, now that the team all have …
=> UML-1031 - Upgrade Environment Terraform AWS provider to v3

terraform/account/certificate.tf, terraform/account/credentials.tf
Upgrade account Terraform AWS Provider to version 3.
Fixes UML-1030
AWS ACM Certificates
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_acm_certificate
There were to options for addressing the change of domain validation records from lists to sets.
Option A was to use the `tolist()` function.
```hcl
resource "aws_route53_record" "certificate_validation_use" {
provider = aws.management
name     = tolist(aws_acm_certificate.certificate_use.domain_validation_options)[0].resource_record_name
type     = tolist(aws_acm_certificate.certificate_use.domain_validation_options)[0].resource_record_type
zone_id  = data.aws_route53_zone.opg_service_justice_gov_uk.zone_id
records  = [tolist(aws_acm_certificate.certificate_use.domain_validation_opti …
```
=> UML-1030 - Upgrade account Terraform AWS Provider to version 3.

terraform/environment/actor_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/pdf_ecs.tf, terraform/environment/viewer_ecs.tf
Had a threat notification of possible attempts to disrupt gov services over the weekend
We're currently using < 10% resources, so doubling the count for the weekend to provide lot of head room. AWS shield should counter any DDoS
=> increase to 4 for the weekend

service-front/app/src/Actor/src/Handler/CreateAccountHandler.php, service-front/app/src/Common/src/Service/Email/EmailClient.php, service-front/app/src/Common/src/Service/Email/EmailClientFactory.php, service-front/app/test/CommonTest/Service/Email/EmailClientTest.php
Sends emails in welsh if locale is set to cy
Fixes UML-1058
Injected locale into EmailClient constructor and used if statements within each send email function to send the email in english or welsh
=> Uml 1058 - welsh emails

service-front/app/languages/messages.pot, service-front/app/src/Actor/templates/actor/check-access-codes.html.twig, service-front/web/src/index.js
Accordion has Open/Close all text set in the external JS - we need to switch this to be multilinqual
Fixes UML-####
On setup of the JS, overwrite the function that is handling this logic
None
=> Overrides GDS accordion open all with translatable text

service-front/app/config/autoload/envs.global.php, service-front/app/config/routes.php, service-front/app/features/bootstrap/behat.config.php, service-front/app/features/bootstrap/config.php, service-front/app/languages/messages.pot, service-front/app/src/Actor/templates/actor/actor-privacy-notice.html.twig, service-front/app/src/Actor/templates/actor/actor-terms-of-use.html.twig, service-front/app/src/Actor/templates/actor/create-account.html.twig, service-front/app/src/Actor/templates/actor/form-error-messages.html.twig, service-front/app/src/Common/src/ConfigProvider.php, service-front/app/src/Common/src/Handler/CookiesPageHandler.php, service-front/app/src/Common/src/Handler/Factory/CookiesPageHandlerFactory.php, service-front/app/src/Common/templates/layout/default.html.twig, service-front/app/src/Common/templates/partials/cookies.html.twig, service-front/app/src/Viewer/templates/viewer/enter-code.html.twig, service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig, service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig, service-front/app/test/CommonTest/Handler/Factory/CookiesPageHandlerFactoryTest.php
Fixes up links across the site to the static privacy policy, cookies and terms of use pages. Sets them up to properly interpret the current language on the site and set links accordingly.
=> Fix up static links for root pages

service-front/app/README.md, service-front/app/composer.json, service-front/app/src/Common/src/Command/TranslationUpdateCommand.php, service-front/app/src/Common/src/Command/TranslationUpdateCommandFactory.php, service-front/app/src/Common/src/ConfigProvider.php, service-front/app/src/Common/src/Service/I18n/CatalogueLoader.php, service-front/app/src/Common/src/Service/I18n/TwigCatalogueExtractor.php, service-front/app/src/Common/src/Service/I18n/TwigCatalogueExtractorFactory.php, service-front/app/test/CommonTest/Command/TranslationUpdateCommandFactoryTest.php, service-front/app/test/CommonTest/Command/TranslationUpdateCommandTest.php, service-front/app/test/CommonTest/Service/I18n/CatalogueLoaderTest.php, service-front/app/test/CommonTest/Service/I18n/TwigCatalogueExtractorFactoryTest.php, service-front/app/test/CommonTest/Service/I18n/TwigCatalogueExtractorTest.php
Improvements to the way the POT files are generated so that the work Lewis has to do is less fraught with errors and repetition.
The new extractor code takes into account the current POT file when running so that the new/changed translations are placed appropriately within the new file.
=> Build better pot files

docker-compose.dependencies.yml, docker-compose.yml
The new version of localstack uses a single entrypoint for all it's services which means our docker-compose setup
broke as it was pointing at ports that simply don't exist anymore. This PR corrects all the environment variables to be
the right values.
Note: This PR will break your local environment *until* you update your opg-sirius-api-gateway project
=> Using the new localstack's single entrypoint.

.circleci/config.yml
Update the docker remote version due to deprecation of the current version
=> Upgrade docker version for circle due to deprecation

.circleci/config.yml
The introduction of limits for anonymous docker image pulls from docker hub requires us to add authentication for all docker commands.
There are 2 sets of docker commands that have to be authorised on our CircleCI pipelines.
Pulls of CircleCI images as the executors of our jobs.
Pullls of images from docker hub as the base for our build artifacts.
Fixes UML-1106
Add authentication to executor definitions. ( https://circleci.com/docs/2.0/private-images/)
Add authentication to docker pull commands using the CircleCI Docker orb.
=> add docker auth to circleci image pulls

service-api/app/features/actor-check-access-codes.feature, service-api/app/features/context/Acceptance/LpaContext.php, service-api/app/features/context/Integration/LpaContext.php, service-api/app/src/App/src/DataAccess/DynamoDb/ViewerCodes.php, service-api/app/src/App/src/DataAccess/Repository/ViewerCodesInterface.php, service-api/app/src/App/src/Handler/LpasResourceCodesCollectionHandler.php, service-api/app/src/App/src/Service/ViewerCodes/ViewerCodeService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodesTest.php, service-api/app/test/AppTest/Service/ViewerCodes/ViewerCodeServiceTest.php
Allows user to see viewer codes created by other actors on the same LPA. The active codes count on the dashboard will also reflect a total of the current users viewer codes and those created by other actors
Fixes UML-1086
Renamed the viewer code function getCodesByUserLpaActorId to getCodesByLpaId and removed the UserLpaActor filter. I changed the for loop inside the LpasResourceCodesCollectionHandler to get use the userLpaActorMap of each viewer code. This is then used to get the actor id of the user who created that code and set that actor id as a new key/value on the viewer code data. I added a behat test and updated existing check access codes/ dashboard tests to reflect the new expected behaviour
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've …
=> UML-1086-Display-co-actors-access-codes

scripts/pipeline/check_ecr_scan_results/aws_ecr_scan_results.py
Provide information to developers about any vulnerabilities found in ECR image scans.
The script had stopped providing a report when posting to slack.
Fixes UML-1112
A description is no longer part of the response for ECR scan findings. This has been removed and the content of the report updated.
Checking an older tag that has since been patched
```
aws-vault exec identity -- python aws_ecr_scan_results.py --search use_an_lpa --tag master-f46db60
Waiting for ECR scans to complete...
ECR image scans complete
Checking ECR scan results...
:warning: *AWS ECR Scan found results for use_an_lpa/front_app:* 
Severity finding counts:
{'UNDEFINED': 2}
Displaying the first 5 in order of severity
*Image:* use_an_lpa/front_app 
**Tag:* master-f46db60 
*Severity:* UNDEFINED 
*CVE:* CVE-2020-8177 …
```
=> UML-1112 - Fix ECR scan results message in Slack posts

service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Handler/ActivateAccountHandler.php, service-front/app/src/Actor/src/Handler/CompleteChangeEmailHandler.php, service-front/app/src/Common/src/Service/User/UserService.php
The Microsoft SafeURL service sends a preemptive HEAD request to a url to check that it is "safe" before sending its users on. The previous piece of code that we had did not distinguish between HEAD and GET and so was activating the account before the user actually visited the activation url. This mean't they would get the failure message
This ensures we respond to HEAD requests appropriately.
Fixes UML-1105
There is a Mezzio middleware that is responsible for managing head requests that this request hits. This middleware attaches and attribute to the request before forwarding it on to the handler. It then strips the body content away before allowing the final dispatch to the user. By using that attribute we can stop the service from carrying out actions when accessed with a HEAD request. …
=> Uml1105 head request uses activation token

terraform/account/credentials.tf, terraform/environment/credentials.tf, terraform/environment/resource_group.tf
The PagerDuty provider has a new path.
```
Warning: Additional provider information from registry
The remote registry returned warnings for
registry.terraform.io/terraform-providers/pagerduty:
- For users on Terraform 0.13 or greater, this provider has moved to
PagerDuty/pagerduty. Please update your source in required_providers.
```
Fixes UML-1123
Use the new path for PagerDuty
Use the command `terraform state replace-provider` to update the environment.
=> Use new pagerduty provider path

service-front/app/src/Common/templates/partials/account-bar.html.twig, service-front/web/src/scss/_lpa-account-menu.scss
Screen readers notify users when they come to a list, and tell them how many items are in a list. Announcing the number of list items and the current list item helps listeners know what they are listening to, and what to expect as they listen to it. If you don't mark up a list using proper semantic markup in a hierarchy, list items cannot inform the listener that they are listening to a list when no parent is indicating the presence of a list and the type of list. This ticket corrects the list markup for the account bar.
Fixes UML-836
Wraps the li elements for the account bar in a ul parent element. Edited the lpa-account-menu style sheet accordingly to include the new ul element combinator and match nested structure.
=> UML-836 DAC Invalid lists markup

service-front/app/features/actor-privacy-notice.feature, service-front/app/features/viewer-privacy-notice.feature, service-front/app/src/Actor/templates/actor/actor-privacy-notice.html.twig, service-front/app/src/Common/templates/layout/default.html.twig, service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig
Fixes UML-1087
Add link to footer and adjust order of existing links.
This introduces some issues with the back link on the privacy notice page (where does it go back to, it's been opened in a new tab)
=> Add privacy notice link

service-front/app/src/Actor/templates/actor/check-access-codes.html.twig, service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
In the accordion we have 2 attributes, id and aria-controls that have static values of accordion-default-heading-4 and accordion-default-content-4. These need to be incremented to help screen readers navigate and be able to distinguish between them
Fixes UML-1008
I created a counter in the check-access-codes.html.twig file for both active and inactive codes. The counter is then included in the check-code-details.html.twig file and appended to the relevant id's.
=> UML-1008 AND 1009 Accordion non unique id attributes

service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
In the check access codes page, there was a for loop to display all the organisations that had viewed a code. However, for codes that had been created prior to the addition of the organisation ViewedBy field in the database, this field is blank, therefore producing a list of blank data for the LPA viewed status. This ticket fixes that bug
Fixes UML-1155
I added some more logic to the twig page to first check whether the 'ViewedBy' field for all viewer activity entires was empty, and if so, just display 'Viewed'. If not, a for loop checks each 'ViewedBy' organisation entry to see if it is empty, if it is, the for loop continues, but if it is not empty, the organisation is displayed
=> UML-1155 LPA viewed by whitespace

.circleci/config.yml, terraform/environment/terraform.tfvars.json
Set production environment log level to 250
Fixes UML-1185
Update the value in the per-environment terraform variables.
=> UML-1185 Modify logging level

.github/dependabot.yml
Dependabot updates PRs are too frequent and arrive at an inconvenient time.
Fixes UML-1276
Update dependabot.yml so that Dependabot package updates run weekly on a Wednesday at 10 am.
https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy
=> UML-1276 - Schedule dependabot package updates to be weekly

.idea/misc.xml, .idea/php.xml, service-front/app/features/context/UI/LpaContext.php
Fix the test issues we're seeing as of 1st March 2021
Change a 'd' to a 'j'
Zero prefixed dates are annoying.
=> Fix test issues

.circleci/config.yml, service-pdf/docker/app/Dockerfile
Reading more into the errors in the build stage it appears to be happening around the download of local version of chromium in the npm install with timeout / connection issues
The base image we're using comes with a stable version of chrome installed, so this change sets the env flags to skip the download (which is where the fails look to be coming from) and set it to use local version
Ran the npm tests on local and they pass without issue
Fixes UML-1309 (hopefully)
=> Use local chrome installed in image

service-front/app/src/Actor/templates/actor/login.html.twig, service-front/app/src/Common/templates/partials/govuk_form.html.twig
Added show/hide password functionality to login page password field
Fixes UML-1230
Made a reusable form component to add the show/hide button alongside the input box for elements containing the attribute "moj-password-reveal__input"
=> UML-1230 Show/hide password on login page

service-front/app/config/routes.php, service-front/app/src/Actor/templates/actor/check-lpa.html.twig, service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Common/src/ConfigProvider.php, service-front/app/src/Common/src/Service/Features/FeatureEnabled.php, service-front/app/src/Common/src/Service/Features/FeatureEnabledFactory.php, service-front/app/src/Common/src/View/Twig/FeatureFlagExtension.php, service-front/app/test/CommonTest/Service/Features/FeatureEnabledFactoryTest.php, service-front/app/test/CommonTest/Service/Features/FeatureEnabledTest.php, service-front/app/test/CommonTest/View/Twig/FeatureFlagExtensionTest.php
Creation of a service and twig extension which more easily allows us to query for feature flagging needs.
Simple invokable service and associated twig extension that makes it available in templates. This lets us use a twig function to find out if we should be doing one thing or another.
=> Implement new feature flagging method

terraform/environment/api_ecs.tf
The api-app task should be permitted to use gov.uk Notify
Fixes UML-1273
Add notify key secret to the api-app task definition
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html
=> UML-1273 - Permit api-app to use gov.uk Notify

service-front/app/languages/messages.pot, service-front/app/src/Actor/templates/actor/already-have-activation-key.html.twig
Changed page title that is the same as the registration date fail page
=> Change older LPA page title that is the same as another

.circleci/config.yml
The post stats job is useful to the team to see usage of the service. The job that posts the stats automatically has not been running.
Fixes UML-1325
Remove a filter parameter in the scheduled job specification that prevented the job from running against the master branch.
https://circleci.com/docs/2.0/configuration-reference/#schedule
=> UML-1325 - Scheduled stats posting job not running

terraform/account/locals.tf, terraform/account/ship_metrics_queue.tf, terraform/account/terraform.tfvars.json
Sending metrics should be resilient to the failure of upstream services, therefore shipping metrics with be mediated by a queue. This first implementation is a simple queue.
Later iteration will introduce FIFO and Dead Letter processing.
Fixes UML-1320
Create a simple queue with a broad access policy
Only create a queue in the development account
=> UML-1320 - Create a queue to push metrics to

service-api/docker/web/etc/confd/templates/nginx.conf, service-front/docker/web/etc/confd/templates/nginx.conf
NCSC Webcheck is reporting that security.txt cannot be found.
Fixes UML-1270
The error here is that redirect should be configured for /.well-known/security.txt and we are redirecting /.well_known/security.txt (underscore should be a hyphen).
Update nginx configuration to correct error.
This is fixed when 
https://783uml1270.view-lasting-power-of-attorney.service.gov.uk/.well-known/security.txt
https://783uml1270.use-lasting-power-of-attorney.service.gov.uk/.well-known/security.txt
redirects to the common security.txt file.
https://www.nginx.com/blog/creating-nginx-rewrite-rules/
=> UML-1270 - Address missing security.txt file

service-front/app/features/context/UI/LpaContext.php, service-front/app/src/Actor/src/Handler/CheckLpaHandler.php, service-front/app/src/Common/src/Service/Lpa/LpaService.php, service-front/app/test/CommonTest/Service/Lpa/LpaServiceTest.php
The "LPA already added" page was not displayed when users were attempting to add the same LPA again by entering the same details. This was due to the order of the checks performed in the code, as validating the code was the first step and this of course failed because the code had just been used to add the LPA, resulting in the "LPA not found" page being displayed. 
Fixes UML-1307
The check to see if the user has already added the LPA had been moved up as the first check performed in the handler. Tests were amended to reflect the changes.
NOTE: This logic is due be moved into the API as part of ticket UML-1218
=> Uml 1307 lpa already added bug fix

.pre-commit-config.yaml, scripts/analysis_scripts/count_account_with_no_lpas.py, scripts/analysis_scripts/count_lpas_per_account.py
**_As a user researcher,
I want to know how many cases have how many LPAs
Where results are a count of cases grouped by LPA count
so that user behaviour can be better understood_**
Fixes UML-1110
Paginate UserLpaActorMap table
List UserIds
Use Pandas to group and count UserId series
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#paginators
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html
https://pandas.pydata.org/docs/user_guide/10min.html
=> UML-1110 - Count LPAs in each account for analysis purposes

.circleci/config.yml, scripts/pipeline/codecov_uploader/validate_codecov_uploader.sh
Reduce the chance of a compromised Codecov script being run, check the scripts SHA checksum against the github release SHA
Fixes UML-1401
- Create a bash script that can be run before the codecov upload
- Fail upload job before executing the script if validation fails
https://docs.codecov.io/docs/about-the-codecov-bash-uploader#validating-the-bash-script
=> UML-1401 - Validate Codecov before using it

service-front/app/features/context/UI/CommonContext.php, service-front/app/src/Actor/src/Handler/ActorSessionCheckHandler.php, service-front/app/src/Actor/src/Handler/ActorSessionExpiredHandler.php, service-front/app/src/Common/src/ConfigProvider.php, service-front/app/src/Common/src/Middleware/Session/SessionExpiredAttributeAllowlistMiddleware.php, service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php, service-front/app/src/Common/src/Service/Security/UserIdentificationService.php, service-front/app/src/Common/src/Service/Session/EncryptedCookiePersistence.php, service-front/app/src/Common/src/Service/Session/EncryptedCookiePersistenceFactory.php, service-front/app/src/Common/src/Service/Session/Encryption/EncryptInterface.php, service-front/app/src/Common/src/Service/Session/Encryption/KmsEncryptedCookie.php, service-front/app/src/Common/src/Service/Session/Encryption/KmsEncryptedCookieFactory.php, service-front/app/src/Common/src/Service/Session/Encryption/UnencryptedCookie.php, service-front/app/src/Viewer/src/Handler/ViewerSessionCheckHandler.php, service-front/app/src/Viewer/src/Handler/ViewerSessionExpiredHandler.php, service-front/app/test/CommonTest/Middleware/Session/SessionExpiredAttributeAllowlistMiddlewareTest.php, service-front/app/test/CommonTest/Middleware/Session/SessionExpiredRedirectMiddlewareTest.php, service-front/app/test/CommonTest/Service/Security/UserIdentificationServiceTest.php, service-front/app/test/CommonTest/Service/Session/EncryptedCookiePersistenceFactoryTest.php, service-front/app/test/CommonTest/Service/Session/EncryptedCookiePersistenceTest.php, service-front/app/test/CommonTest/Service/Session/Encryption/KmsEncryptedCookieTest.php, service-front/app/test/CommonTest/Service/Session/Encryption/UnencryptedCookieTest.php
Attempts to fix our session handling by reworking the logic flow around our various middlewares.
Fixes UML-1227
Because we use a redirect to bring the user to a session-expired page we need to ensure that upon re-entry to the site (from the redirect) the users session is still marked as expired even though it wouldn't technically be.
=> Uml 1227 fix session redirection

terraform/environment/credentials.tf
New aws provider version (3.40.0) introduces an error in validation of static response size limits.
Fixes UML-1463
Pin AWS provider in environment to 3.38.0
=> UML-1463 - Pin aws provider to 3.38.0 to avoid new linting error

service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig, service-front/app/src/Common/src/View/Twig/LpaExtension.php, service-front/app/src/Common/templates/partials/full-lpa-display.html.twig, service-front/app/test/CommonTest/View/Twig/LpaExtensionTest.php
If the donor signed the LPA before 2016-01-01 then show "unknown" for Instructions and preferences even if the record contains the correct flags.
Fixes UML-1418
Add Twig function and code to display record appropriately
=> UML-1418 Show unknown for I&P for old donor signatures

service-front/web/src/scss/_translation-switch.scss
The recently fixed flash message styling PR has unintentionally changed how the back button and welsh switch are styled together. The back button is now being displayed on the level below the welsh switch, this PR fixes that so that they are inline again
Added display: inline to the welsh switch css element
=> Back-button-translation-switch-css-fix

service-front/web/Dockerfile, service-front/web/package-lock.json, service-front/web/package.json, service-pdf/app/package-lock.json, service-pdf/app/package.json
Roll in changes from #923
Update dependencies for the node stuff
```
make up webpack
make exec webpack /bin/sh
npm update --legacy-peer-deps
make up service-pdf
make exec service-pdf /bin/sh
npm update
npm audit fix
exit
docker cp service-pdf:/src/app/package.json service-pdf/app/
docker cp service-pdf:/src/app/package-lock.json service-pdf/app/
```
Legacy peer deps is important as one of our dependencies hasn't been updated for webpack5. It needs monitoring as it could break things for us in the future.
=> Update NPM dependencies

service-front/docker/app/Dockerfile
Pipielines fail to run unit tests for service-front app image
```
Fatal error: Uncaught Error: Class 'PHPUnit\TextUI\Command' not found in /app/vendor/phpunit/phpunit/phpunit:61
Stack trace:
#0 {main}
thrown in /app/vendor/phpunit/phpunit/phpunit on line 61
PHP Fatal error:  Uncaught Error: Class 'PHPUnit\TextUI\Command' not found in /app/vendor/phpunit/phpunit/phpunit:61
Stack trace:
#0 {main}
thrown in /app/vendor/phpunit/phpunit/phpunit on line 61
Exited with code exit status 255
```
Fixes UML-1499
Pin composer layers to a previous working tag
=> UML-1499 - pin composer layers to 2.0.14

.circleci/config.yml
pip dependencies weren't installed on prod runs of the job
Fixes UML-1502
- consolidate dev and prod jobs into one
- use parameters and defaults for slack webhook
- use new consolidated job for prod notifications
=> UML-1502 - fix notifications on prod environment

docker-compose.dependencies.yml
Unable to connect to or seed locally running DynamoDB tables
Fixes UML-1595
Pin localstack/localstack version to 0.11.4
Related to https://github.com/localstack/localstack/issues/3069
=> UML-1595 - pin localstack version to 0.11.4

terraform/environment/ship_to_metrics.tf
Dev environment builds failed due to resource conflict exception
Fixes UML-1603
make aws_lambda_permission statement_ids unique by including the environment name
=> UML-1603 - ResourceConflictException for aws_lambda_permission

terraform/account/lambda/docker-compose-ship-to-opg-metrics.yml, terraform/account/lambda/ship-to-opg-metrics/Dockerfile, terraform/account/lambda/ship-to-opg-metrics/src/requirements.txt
Adds missing requirements.txt for lambda function which causes request to error as it is no longer available as default in AWS Lambda images
Fixes UML-1604
Add a requirements.txt file with the dependency
Use requirements
=> UML-1604: Add missing requirements.txt for lambda function

service-front/app/src/Common/src/Service/Lpa/Response/Parse/ParseActivationKeyExistsResponse.php, service-front/app/src/Common/src/Service/Lpa/Response/Parse/ParseLpaAlreadyAddedResponse.php, service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseActivationKeyExistsResponseTest.php, service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseLpaAlreadyAddedResponseTest.php
Fixes a bug for the LPA already added feature and when a user is requesting an activation key when they already have one, whereby if any of the donor's name fields are null, breaks the workflow
Fixes UML-1615
Updated the ParseLpaAlreadyAddedResponse.php and ParseActivationKeyExistsResponse.php files to remove the php function`isset` check on the donor name fields and replaces them with an `array_key_exists` check instead to ignore the value of the field
=> UML-1615-LPA-already-added-null-name-bug

terraform/environment/.envrc, terraform/environment/actor_load_balancer.tf, terraform/environment/shared_data_sources.tf, terraform/environment/viewer_load_balancer.tf
Remove lifecycles on loadbalancer security group rules to prevent duplicate rule errors on apply.
Fixes UML-1620
remove 
```hcl
lifecycle {
create_before_destroy = true
}
```
=> UML-1620 - Bug - Duplicate loadbalancer security group error

docker-compose.yml, service-api/app/config/autoload/features.global.php, terraform/environment/api_ecs.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json
Disabled everywhere apart from local development. This is so this strand of work does not affect PRs for other codepaths
Add feature flag `save_older_lpa_requests` to the api app for development of that feature.
Fixes UML-1619
=> UML-1619 Add feature flag for the saving of older lpa requests. 

service-front/app/src/Actor/templates/actor/request-activation-key/date-of-birth.html.twig, service-front/app/src/Actor/templates/actor/request-activation-key/postcode.html.twig, service-front/app/src/Actor/templates/actor/request-activation-key/reference-number.html.twig, service-front/app/src/Common/templates/partials/govuk_form.html.twig
500 errors were appearing on the older lpa form pages as they did not contain labels. The issue only appeared on my machine as it is maybe running in a super strict mode?
Set an aria_labelledby tag on the form fields which is set to the page heading id. This fixes the accessibility issues on the forms. Also made labels optional by wrapping them in an if block and checking if they are defined.
=> Fix forms without labels and accessibility issues

service-api/app/src/App/src/ConfigProvider.php, service-api/app/src/App/src/Service/Features/FeatureEnabled.php, service-api/app/src/App/src/Service/Features/FeatureEnabledFactory.php, service-api/app/src/App/src/Service/Lpa/LpaAlreadyAdded.php, service-api/app/test/AppTest/Service/Features/FeatureEnabledFactoryTest.php, service-api/app/test/AppTest/Service/Features/FeatureEnabledTest.php, service-api/app/test/AppTest/Service/Lpa/LpaAlreadyAddedTest.php
We need to change our check for the existence of the Lpa within a users account so that if the _ActivateBy_ column exists then the check passes (as if the user does not have the Lpa in their account.
Fixes UML-1611
Add feature flag usage and refactor code to check the db *without* pulling every LPA the user has from Sirius
=> Uml 1611 - TTL field existence

terraform/account/network.tf
Address SecurityHub findings
Fixes UML-1659
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-15-remediation
=> UML-1659 - Do not map public IP on launch - Subnets

service-front/app/src/Common/src/Service/Lpa/AddLpa.php
Logs event codes that were not being logged to allow events to be tracked in cloudwatch metrics
Added data to log messages containing the missing event codes
=> Logging missing for event codes

service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php, terraform/environment/terraform.tfvars.json
The `save_older_lpa_requests` flag has always been turned off in dev mode, meaning any tickets relying on that feature were never UAT'd properly. Since switching it on I have come across this error when requesting an activation key:
`"NUMBER_VALUE cannot be converted to String"` . I believe this is due to the fact that dynamoDB expects number values to be represented as strings (see doc for details https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html). 
Therefore this line was causing the issue:
`$array['ActivateBy'] = ['N' => $expiry->getTimestamp()];`
and has been fixed by converting the timestamp to a string
=> Switch save requests flag on and fix ActivateBy TTL put item error

service-api/app/features/actor-add-an-older-lpa.feature, service-api/app/psalm.xml, service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php, service-api/app/src/App/src/DataAccess/Repository/UserLpaActorMapInterface.php, service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php, service-api/app/src/App/src/Service/Lpa/LpaAlreadyAdded.php, service-api/app/src/App/src/Service/Lpa/LpaService.php, service-api/app/src/App/src/Service/Lpa/OlderLpaService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/UserLpaActorMapTest.php, service-api/app/test/AppTest/Service/ActorCodes/ActorCodeServiceTest.php, service-api/app/test/AppTest/Service/Lpa/LpaAlreadyAddedTest.php, service-api/app/test/AppTest/Service/Lpa/LpaServiceTest.php, service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php, service-front/app/features/bootstrap/behat.config.php
As a part of the work on UML-1643 it's been necessary to refactor some of the logic around saving records into the UserActorLpaMap table. This simplifies the code that then needs to change records in this table.
Additionally some fixes have gone in to ensure that development mode files do not affect behat test runs.
Move the loop of code  that retried UUID's down into the datamapper layer and remove that from the 2 calling services.
* ~The product team have tested …
=> Uml 1643 update existing activation key (refactor pt1)

service-front/app/features/actor-add-an-older-lpa.feature, service-front/app/features/context/UI/RequestActivationKeyContext.php, service-front/app/src/Actor/templates/actor/check-your-answers.html.twig
Only displays warning when allow_older_lpa flag is OFF
Fixes UML-1750
Wrapped content in twig file in an feature flag check and added 2 ui tests
=> UML-1750 Check answers warning

service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckYourAnswersHandler.php
We need to unset any session values that are set in the "full match" or "partial match" part of the the journey. These values are used in logic statements to map which journey the user has come from or decide whether the LPA should be send to be cleansed. If these values are not cleared from the session on each request, incorrect behaviour will occur as session values will still be present from the previous request.
Fixes UML-1788
Hard-coded the session value to unset the check answers handler
=> UML-1788-Clear session values in check answers handler

.circleci/config.yml
fromCircleCI
```
Our new convenience images were built from the ground up with CI, efficiency, and determinism in mind. Here are some of the highlights:
Faster spin-up time - In Docker terminology, these next-gen images will generally have fewer and smaller layers. Using these new images will lead to faster image downloads when a build starts, and a higher likelihood that the image is already cached on the host.
Improved reliability & stability - The current images are rebuilt practically every day with potential changes from upstream that we can’t always test fast enough. This leads to frequent breaking changes, which is not the best environment for stable, deterministic builds. Next-gen images will only be rebuilt for security and critical-bugs, leading to more stable and deterministic …
```
=> UML-1728 - Upgrade CircleCI executor images

.circleci/config.yml
BUG - docker push without specifying tags now pushes just the default tag.
Fixes UML-1790
- add --all-tags to each docker push for the path to live
https://docs.docker.com/engine/reference/commandline/push/
=> UML-1790 - docker push all tags on path to live

terraform/environment/actor_load_balancer.tf, terraform/environment/admin_load_balancer.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json, terraform/environment/viewer_load_balancer.tf
[ELB.6] Application Load Balancer deletion protection should be enabled
Fixes UML-1662
- enable protection on production
- disable protection on development and preproduction environments
For testing, AWS Security Hub checks for deletion protection in preproduction and production
=> UML-1662 - Deletion protection for load balancers

terraform/account/elasticache.tf, terraform/account/vpc_endpoints.tf
Descriptions provide context for the firewall rule reasons
Fixes UML-1778 UML-1779
- Add descriptions for all security groups
https://tfsec.dev/docs/aws/vpc/add-description-to-security-group#aws/vpc 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule
https://www.cloudconformity.com/knowledge-base/aws/EC2/security-group-rules-description.html
=> UML-1778 UML-1779 - add description for security groups

terraform/account/elasticache.tf, terraform/account/vpc_endpoints.tf, terraform/environment/shared_data_sources.tf
Path to live cannot complete because it cannot destroy security groups in use
Fixes UML-1778
- use create_before_destroy lifecycle on security groups
=> UML-1778 - Fix - Create security groups before destroying them

terraform/account/.envrc, terraform/account/.terraform.lock.hcl, terraform/account/cloudwatch.tf, terraform/account/lambda_functions.tf, terraform/account/modules/lambda_function/main.tf, terraform/account/modules/lambda_function/variables.tf, terraform/account/vpc_flowlogs.tf
Log data may be leaked if the logs are compromised. No auditing of who have viewed the logs.
Fixes UML-1783 UML-1785 UML-1786 UML-1787
- create kms key with permissions for cloudwatch log group encryption
- user kms key for log groups
- pass kms key for log group encryption into lambda function module
- https://tfsec.dev/docs/aws/cloudwatch/log-group-customer-key#aws/cloudwatch 
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#kms_key_id 
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html
=> UML-1783 UML-1785 UML-1786 UML-1787 - Cloudwatch Log Group Encryption

terraform/account/workspace_cleanup.tf
Take control of workspace cleanup table and address securityhub findings
Fixes UML-1770
- Manage workspace cleanup table with terraform
- prevent destroy on table
- set billing mode to pay per request
- suppress Security Hub check for point in time restore (not required for this table)
This change requires a terraform import before merging
```
tf import aws_dynamodb_table.workspace_cleanup_table WorkspaceCleanup
```
=> UML-1770 - workspace cleanup table management

terraform/account/modules/lambda_function/iam.tf, terraform/account/modules/lambda_function/main.tf
Without full tracing enabled, it is difficult to trace the flow of logs
Fixes UML-1780 UML-1781
- Set tracing config to Active in lambda function tf module
- add xray write policy to lambda execution role
- https://tfsec.dev/docs/aws/lambda/enable-tracing#aws/lambda 
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#mode
=> UML-1780 UML-1781 - Set tracing config to Active

terraform/environment/ecs_cluster.tf, terraform/environment/shared_data_sources.tf
Deployment triggered access denied alerts
Fixes UML-1777
Add decrypt permission for execution role
=> UML-1777 - allow execution_role to decrypt secrets manager secrets

service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
https://opgtransform.atlassian.net/browse/UML-1716
Cancelled items on dashboard should have a textual representation
Fixes UML-1716
=> Uml 1716 - Cancelled items on dashboard should have a textual representation

terraform/account/secretsmanager.tf
Demo environment will need to be able to send notifcations for any user, not just team members
Fixes UML-1859
- Create an account level Secrets Manager secret for a notify key in development
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret
=> UML-1859 - Create a notify key secret for the demo environment

terraform/account/pagerduty.tf, terraform/environment/pagerduty.tf, terraform/environment/shared_data_sources.tf
Pagerduty alarms would not trigger due to permissions errors
Fixes UML-1858 UML-1735
- create a Customer Managed Key for pagerduty SNS
https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-receive-sns-for-alarm-trigger/
=> UML-1858 UML-1735 - CMK for SNS Encryption

service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckDetailsAndConsentHandler.php, service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckYourAnswersHandler.php, service-front/app/src/Actor/src/Handler/RequestActivationKey/ReferenceNumberHandler.php, service-front/app/src/Actor/src/Handler/RequestActivationKey/RequestActivationKeyInfoHandler.php, service-front/app/src/Actor/templates/actor/activation-key-request-received.html.twig, service-front/app/src/Actor/templates/actor/before-requesting-activation-key-info.html.twig, service-front/app/src/Actor/templates/actor/cannot-find-lpa.html.twig, service-front/app/src/Actor/templates/actor/request-activation-key/info.html.twig, service-front/app/src/Actor/templates/actor/send-activation-key-confirmation.html.twig, service-front/app/src/Common/src/Service/Session/RemoveAccessForAllSessionValues.php, service-front/app/test/CommonTest/Service/Session/RemoveAccessForAllSessionValuesTest.php
Clear session values from access for all journey
Fixes UML-1854
To many different places to clear at end of journey so instead we clear before the matching is done in check answers and at the beginning of the journey
~~I have added relevant logging with appropriate levels to my code~~
~~I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~~
~~I have added welsh translation tags and updated translation files~~
~~I have run an accessibility tool on any pages I have made changes to and fixed any issues found~~
=> UML-1854 clear session values

service-front/app/src/Actor/templates/actor/lpa-add.html.twig, service-front/app/src/Actor/templates/actor/request-activation-key/reference-number.html.twig
Removing the inputmode and patterns will stop iOS devices from showing the wrong type of keyboard for this kind of field. It used to be accurate when we only accepted numbers but now we also accept hypens and such which can cause user confusion.
Fixes UML-1701
Couldn't just remove the pattern as the inputmode is also incorrect as per HTML specs
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
* The product team …
=> UML-1701 Remove pattern and inputmode types

terraform/environment/terraform.tfvars.json
Make the Delete LPA feature available for Use in production
Fixes UML-1878
- Set delete_lpa_feature to `true` in tfvars production block
=> UML-1878 - Enable delete_lpa_feature flag on production

terraform/account/lambda_functions.tf
Support rotating API keys by getting their value on execution rather than on deployment
Fixes UML-1870
- Add function to get_secret_value from opg-metrics
- give lambda function permission to get secret value from opg metrics
https://aws.amazon.com/premiumsupport/knowledge-center/secrets-manager-share-between-accounts/
=> UML-1870 - Get API key for shipping to opg-metrics

.circleci/config.yml
When PRs only relate to terraform, we only need to test terraform stages of workflow.
Fixes UML-1900
- Create a workflow for terraform only changes
- Only run terraform only workflow if the branch matches the pattern 
- `dependabot/terraform/*`
- `tf/*`
- update package update PR filtering to be
-  `dependabot/npm_and_yarn/*`
-  `dependabot/composer/*`
=> UML-1900 - Create a CircleCI workflow for Terraform only changes

.circleci/config.yml, scripts/pipeline/post_release_slack_notification/on_fail.txt
Let the team know in Slack when the path to live fails
Fixes UML-1875
- add post-step to each job on path to live
- call slack/status with fail_only condition to notify team channel of path to live failures
- https://circleci.com/docs/2.0/configuration-reference/#pre-steps-and-post-steps-requires-version-21
- https://circleci.com/developer/orbs/orb/circleci/slack
- https://support.circleci.com/hc/en-us/articles/360047082992-Send-slack-notification-at-end-of-workflow
=> UML-1875 - Notify team in Slack when there is a path to live failure

.circleci/config.yml
Reverts ministryofjustice/opg-use-an-lpa#1252
Terraform jobs don't have bash which is a requirement of the slack/status post step.
=> Revert "UML-1875 - Notify team in Slack when there is a path to live failure"

terraform/account/.terraform.lock.hcl, terraform/account/waf.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json, terraform/environment/waf.tf
Prevent unwanted requests from reaching the service applications.
Fixes UML-1964
- Create a WAF Web ACL for an account
- Create resources for encrypted logging
- Use managed rules
- Conditionally associate an environment's ALBs
- https://docs.aws.amazon.com/waf/latest/developerguide/waf-chapter.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_logging_configuration
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_key
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group
* New event_codes have been documented on the [wiki …
=> UML-1964 - create an AWS WAF Web ACL with managed rules

.circleci/config.yml, scripts/pipeline/check_ecr_scan_results/aws_ecr_scan_results.py, scripts/pipeline/requirements.txt
The check scan results job was silently failing due to changes in permissions
Fixes UML-1986
- capture boto client exceptions
- refactor to bring up to pylint spec
- https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html
=> UML-1986 - Exit on boto3 client and waiter errors

service-api/app/features/context/Acceptance/LpaContext.php
API app acceptance tests are failing with an assertion on an explicitely written date.
Fixes UML-2001
- set expiry of code to tomorrow using DateTime function
=> UML-2001 - Fix Date Assertions in API App Acceptance Text

service-api/seeding/dynamodb.py, service-front/app/features/context/UI/LpaContext.php, service-front/app/src/Actor/src/Handler/CheckAccessCodesHandler.php
The created by field is broken for LPAs added to accounts after the end of December. This adds additional checking logic so that we check the right place.
Fixes UML-2015
Check both the Uid and Id for a case actor when doing a comparison
=> UML-2015 Ensure we check both ID types when showing CreatedBy

service-front/docker/app/Dockerfile, service-front/docker/app/app-php-development.ini
Configure Service-Front App PHP to provide useful information during local development
Fixes UML-1947
- overwrite app-php.ini at develpment build target for service-front
- https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting
- https://www.php.net/manual/en/errorfunc.constants.php#122640
* have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
=> UML-1947 - configure Service Front App development build targets to report all errors and warnings

.circleci/config.yml, docker-compose.yml
We're using the wrong installation command and it could result in dependencies not exactly matching what we're expecting. The correct command to use is `ci`. This PR replaces instances of `install` so that we're doing the right thing.
=> Use correct npm invocation

service-api/app/.dockerignore, service-front/app/.dockerignore
Speed up local builds (marginally)
Adding .dockerignore files to exclude the large dependency folders means I don't wait 30seconds per image to upload context that gets ignored.
=> Ignore large dependency folders when building images locally

service-api/app/features/context/Acceptance/LpaContext.php, service-api/app/features/context/Integration/LpaContext.php, service-api/app/src/App/src/Service/Lpa/AddOlderLpa.php, service-api/app/test/AppTest/Service/Lpa/AddOlderLpaTest.php, service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckYourAnswersHandler.php
https://opgtransform.atlassian.net/browse/UML-2014
Fixes UML-2014
When requests [LPA records] do not have a due by date, check for activation code in Sirius to get the created date before sending exception
=> UML-2014: Handle requests that may not have a due by date

service-front/app/features/context/UI/LpaContext.php, service-front/app/src/Actor/templates/actor/home-page.html.twig, service-front/app/src/Actor/templates/actor/lpa-blank-dashboard.html.twig, service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig, service-front/app/src/Actor/templates/actor/partials/lpas-registered-after.html.twig, service-front/app/src/Actor/templates/actor/partials/upcoming-service-downtime.html.twig, service-front/app/src/Viewer/templates/viewer/enter-code.html.twig, service-front/app/src/Viewer/templates/viewer/partials/upcoming-service-downtime.html.twig, service-front/web/src/scss/_banner.scss
Rejig the banners to be GDS ones and make sure they're implemented as per guidelines.
New banner HTML and some css tweaks to tidy the layout slightly.
=> Accessibility fixes for banners

terraform/environment/actor_load_balancer.tf, terraform/environment/viewer_load_balancer.tf
=> UML-2133 - point to planned downtime content for fixed maintenance response

service-api/seeding/dynamodb.py, terraform/environment/dynamodb.tf
Adds the secondary index "ActivationCodeIndex" to the user_lpa_actor_map
Fixes UML-1548
Secondary key added to user_lpa_actor_map in dynamodb.tf
ActivationCode attribute specified in dynamodb.tf
Added ActivationCode to some seeded LPAs in dynamodb.py 
The secondary index of a dynamodb table needs to be defined as an attribute
This --> https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html
=> Uml 1548 activation code secondary index

terraform/environment/dynamodb.tf
To speed up queries and searches for LPAs.
Fixes UML-2165
- Define SiriusUid attribute
- Create a Global Secondary index for SiriusUids
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table
* ~I have notified the Interaction Designer …
=> UML-2165 - add a global secondary index to UserLpaActorMap for SiriusUids

terraform/environment/dns_health_check.tf
expected length of reference_name in aws_route53_health_check to be in the range (0 - 27)
Fixes UML-2200
- use a substring, the first 20 characters to keep full reference name under 27
* ~I have notified the Interaction Designer of any content changes so that appropriate …
=> UML-2200 - limit env name length in reference name

service-front/web/src/scss/_lpa-ticket-panel.scss, service-front/web/src/scss/lpa.scss, service-front/web/src/scss/ulpa-colours.scss
Red should be shaded so that if gov colours ever change our system also updates
govuk-shade 
govuk-shade exists. There should be a discussion at some point if shade should be the 25% suggested by GDS
=> Shade colour rather than defining our own

scripts/analysis_scripts/lookup_account.py
Script would replace each item returning only the last found in a list.
Fixes UML-2235
Now much quicker!
- during lookup, append entire list don't use for each
- use query on SiriusUid index for lookups by LPA ID
* ~I have notified the Interaction Designer of any content …
=> UML-2235 - Ensure all LPA items are getting added to results

service-front/app/src/Actor/templates/actor/home-page.html.twig, service-front/app/src/Actor/templates/actor/lpa-blank-dashboard.html.twig, service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig, service-front/app/src/Actor/templates/actor/partials/lpas-registered-after.html.twig, service-front/app/src/Viewer/templates/viewer/enter-code.html.twig
https://opgtransform.atlassian.net/browse/UML-2231
Fixes UML-2231
Removed the maintenance page inclusions from the pages. The pages and translations are left behind.
=> Removed the inclusion to the maintenance downtime banner from pages

terraform/account/modules/dynamodb_cloudtrail/cloudtrail.tf
Missing permissions causing silent failure of pushing events to logstream
Fixes UML-2237
- Add permission
- recreate logstream pushing
* …
=> UML-2237 - BUG - fix logging cloudtrail data events

docker-compose.yml, terraform/environment/terraform.tfvars.json
Retrive the image digest for latest and deploy that version.
Fixes UML-2236
- pick the tag latest
! Read the notes in the ticket reference above
=> UML-2236 - use latest tag when deploying pdf

terraform/environment/actor_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json
Make it easier to organise and locate application flags
Fixes UML-2224
- Create an object variable called application_flags in the accounts variable object
- move all aapplication flags into new object
- update ecs env vars to use new object address
* ~I have notified the …
=> UML-2224 - Refactor application flags into a variable object

service-front/web/src/pdf.scss, service-front/web/src/scss/_cookie-banner.scss, service-front/web/webpack.pdf.development.js
Cookie banner is displaying when downloaded. This needs to be fixed so it is not viewable in the HTML sent to pdfservice
Fixes UML-2261
Display logic is now inversed with cookie banner, it is displayed until it is hidden, this means we need to give an extra CSS rule in pdf.scss to hide the banner.
=> UML 2261 cookie banner should not display in pdf

service-front/app/src/Common/templates/partials/govuk_error.html.twig
When gaAction is empty string then analytics isn't reported
Fixes UML-2285
Set action to element name when the label doesn't exist
Gaaction is required :D
=> UML-2285 missing analytics

service-front/web/src/javascript/cookieConsent.js, service-front/web/src/javascript/cookieConsent.test.js
Stop cookies being set to essential only when navigating to cookie page 
Fixes UML-2286
logic missing to only set cookies to essential only when navigating to cookie page AND cookies have not previously been set
This last step has now been added to the logic
=> Uml 2286 cookies page always turns cookies off

.circleci/config.yml, terraform/environment/admin_ecs.tf, terraform/environment/locals.tf
Make Admin only development pipelines quicker
Fixes UML-2284
- Create a branch name filter for `admin/`
- Allow terraform to accept an image tag for Admin
- https://circleci.com/docs/2.0/configuration-reference/#jobfilters
- https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3470622721/UaL+Filtered+Pipelines
* ~I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram …
=> UML-2284 - Admin Development only workflow

terraform/environment/api_ecs.tf, terraform/environment/dns.tf, terraform/environment/pdf_ecs.tf
Change the format so that it is easier to manage egress at WAF 
Fixes UML-2238/UML-2292
- create a new aws_service_discovery_private_dns_namespace with a better format namespace
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_service
=> UML-2238 / UML-2292 - format service discovery dns to support wildcarding

terraform/environment/api_ecs.tf, terraform/environment/dns.tf, terraform/environment/pdf_ecs.tf
Part 2 of 3 of Service Discovery DNS changes
Fixes UML-2293
- build env
- move api and pdf to new service discovery
* ~The product team have …
=> UML-2238/UML-2293 - Move API and PDF services to new service discovery DNS

terraform/environment/locals.tf
Enviornment names are used in load balancer resource names and underscores are not permited there
Fixes UML-2016
- use the terraform replace function
- https://www.terraform.io/language/functions/replace
* ~I have notified the Interaction Designer of any content changes so …
=> UML-2016 - Don't let underscores be part of an env name

terraform/environment/cloudwatch_metrics.tf
Measure the reasons for log in failures
Fixes UML-1960
- Create a metric filter for each failed login status
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_metric_filter
* ~I have notified the Interaction Designer of any …
=> UML-1960 - create a metric for each failed login status

terraform/environment/cloudwatch_alarms.tf
Enrol UaL in Shield Advanced
Fixes UML-2347
- Create a cloudwatch alarm for each aws_lb monitoring the DDOSDetected events
- https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/enabling-shield-advanced.html#create-alarms
* ~I have notified the …
=> UML-2347 - Create DDOS alarms for each loadbalancer

terraform/environment/actor_ecs.tf, terraform/environment/admin_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/locals.tf, terraform/environment/pdf_ecs.tf, terraform/environment/terraform.tfvars.json, terraform/environment/viewer_ecs.tf
Reduce cost of development by running PR environment ECS services on Fargate Spot capacity providers
Fixes UML-1512
**Release instructions**
The create_before_destroy lifecycle will be temporarily set to false so that the replacement can take place, the apply run from local, then the path to live will deploy update task definitions
- Create a new variable to determine whether fargate spot should be used
- Configure capacity providers for all ecs services
- Use fargate spot on PR environments only
- https://aws.amazon.com/blogs/aws/aws-fargate-spot-now-generally-available/
- https://docs.aws.amazon.com/AmazonECS/latest/userguide/fargate-capacity-providers.html
* ~New event_codes have been documented on the [wiki …
=> UML-1512 - Use Fargate SPOT as a capacity provider for PR environments

service-front/app/src/Actor/templates/actor/request-activation-key/actor-address.html.twig
Chose the wrong address level for town/city entry as it's slightly different in the UK vs. the world.
* ~The product team have tested these …
=> Turns out in the UK level1 is the more appropriate type for address-town

service-front/app/src/Common/templates/partials/govuk_form.html.twig
Switch to GDS markup for input field prefixes. 
Fixes UML-2289
Change made to our GDS component template and will affect all fields that use a prefix. This is currently only the activation key entry and viewer code entry fields on the actor and viewer side respectively.
* ~I have notified the Interaction Designer of any content changes so that appropriate …
=> Ensure we use correct GDS markup for input prefixes

terraform/environment/cloudwatch_alarms.tf
Cloudwatch alarms for DDOS attacks were not unique per environment
Fixes UML-2512
- add environment namesapce to each alarm
* ~The product …
=> ddos alarm names were not unique and were overwritting each other

service-admin/cmd/admin/main.go, service-admin/internal/server/data/account.go, service-admin/internal/server/data/account_test.go, service-admin/internal/server/data/dynamo.go, service-admin/internal/server/data/dynamo_test.go, service-admin/internal/server/data/lpa.go, service-admin/internal/server/server.go, service-admin/internal/server/server_test.go
add coverage 
Fixes UML-2269
prefix is now added to the DynamoConnection struct. This way it is not global and can be accessed in parallel by multiple tests.
=> Add coverage to dynamodb.go

service-front/docker/app/Dockerfile
Path to live is broken due to alpha release of xdebug not installing successfully. We do not want alpha releases of php extensions unless for a specific reason.
Fixes UML-2594
- specify `stable` for version constraint
- https://github.com/mlocati/docker-php-extension-installer#installing-specific-versions-of-an-extension
* ~I have run an accessibility tool on any pages I …
=> UML-2594 - Install stable release of xdebug in development docker layer

terraform/environment/admin_ecs.tf
Allow the admin app to make requests to /code
Fixes UML-2555
- add resource to lpacodesaccess statement
* ~New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event~+logs)
* ~The product team have tested …
=> UML-2555 - Add permission for /code endpoint to admin app

terraform/environment/actor_load_balancer.tf, terraform/environment/viewer_load_balancer.tf
Don't forward on query when redirecting users to maintenance
Fixes UML-2576
- send empty string in place of query
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#query
* ~I have notified the Interaction Designer of any content …
=> UML-2576 - Drop queries when maintenaance is enabled

.github/dependabot.yml
Currently we get swamped by dependabot updates every month, this PR will change the dependencies to be reported daily to potentially make them more manageable
Fixes UML-2540
=> Uml 2540 dependabot to daily

terraform/account/modules/s3_bucket/data_sources.tf
Last PR for UML-2658 broke main pipe as the naming is different in preprod for the s3 access bucket. 
Fixes UML-2658
Make the exception for the pre access naming
NA
=> UML-2658-b fix of last PR due to naming issue in preprod

service-api/app/src/App/src/Service/Email/EmailClient.php, service-front/app/src/Actor/src/Form/PasswordResetRequest.php, service-front/app/src/Actor/src/Handler/PasswordResetRequestPageHandler.php
We were not using the correct parameter name for the force password reset email.
Fixes UML-2680
=> Uml 2680 fix password reset page issue

.idea/runConfigurations/API_Integration.xml, service-api/app/features/context/Integration/AccountContext.php, service-api/app/src/App/src/Handler/AuthHandler.php, service-api/app/src/App/src/Service/User/UserService.php, service-api/app/test/AppTest/Service/User/UserServiceTest.php
Use hidden string to avoid accidental printing of plaintext credentials
Fixes UML-2655
=> Add hidden string to authenticate method

.circleci/config.yml
Fixes UML-2686
Pin install docker credentials orb to v0.6.4 so it stops breaking
=> Pin docker credential helper

Makefile, service-front/app/src/Common/src/Service/Security/UserIdentificationService.php
Stop logging when an identity is "new" which is for us nearly all load balancer healthchecks.
=> Reduce logged output

.circleci/config.yml
circleci file became out of date on UML-2559 and some changes were missed so we are seeing some reoccurring issues. This should bring it back to how it was (minus the workflows that have been moved to actions)
=> UML-2559b fix out of date circleci file

.github/workflows/pull-request-path.yml
the team often use longer branch names in the format branch_description.
whilst I thought about trying to just extract the branch name using combination of awk and some regex logic, there are quite a few variants that get used and I feel like I will miss some without a bit of thought so for now i'm just cutting the branch to be first 8 chars.
NA
=> UML-2559c handle longer path names

.circleci/config.yml
Had removed this as part of the GH work as we now post directly to dynamo. However, having this back in for now as that piece of work isn't fully active yet
Fixes UML-2565
Adding back to circle rather than GH as would have to find a slack action that formatted results similarly and not worth doing now as we likely won't need this in future. 
NA
=> UML-2565 add stats weekly run back into circle for now

service-front/app/src/Common/src/Exception/ApiException.php, service-front/app/src/Common/src/Service/ApiClient/Client.php, service-front/app/test/CommonTest/Service/ApiClient/ClientTest.php
When the connection between our Frontend and API 
Fixes UML-2740
When connections fail it raises an implementation of the ClientExceptionInterface. If one of these exceptions have been raised we can tell that the connection has failed. In this case we need to force the resulting exception to be a 502 error instead of a 500
=> make 500 errors on api connection failure a 502 (Bad Gateway)

.github/workflows/_run-terraform.yml
If TF lock is in conflict currently this fails the PR straight away. Adding a timeout will allow the PR to wait up to 5 minutes before failing. If the lock becomes available again in this time the TF plan should go ahead.
https://developer.hashicorp.com/terraform/cli/commands/plan#lock-timeout-duration:~:text=%2Dlock%2Dtimeout%3DDURATION)
=> add lock timeout to plan command. 

service-front/app/src/Common/templates/layout/default.html.twig
We do not use onload events and JS loads quicker than the DOM being rendered. Moving the script tag to the bottom of the document ensures the JS is preloaded but not executed until the DOM is parsed and rendered.
Fixes UML-2788
Move JS script tag to bottom of document
=> Move JS script tag to bottom of document

service-front/app/features/actor-dashboard.feature, service-front/app/features/context/UI/LpaContext.php, service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig, service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig, service-front/app/src/Common/src/Service/Lpa/PopulateLpaMetadata.php
Replace "No organisations have access" with badge that says no active codes. When no codes have been made at all this area is blank
Fixes UML-2700
add access to share codes in PopulateLPAMetadata access length of this array in twig template 
* [] The product team have tested these changes
[UML-2700]: https://opgtransform.atlassian.net/browse/UML-2700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UML-2700 NO ACTIVE CODES badge

service-admin/web/templates/stats.page.gohtml, service-api/seeding/dynamodb.py
https://opgtransform.atlassian.net/browse/UML-2793
Fixes UML-2793
Number of access code views was looking at wrong event, code changed to now look at event viewer codes viewed event
~* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)~
~* [ ] I have run an …
=> UML-2793: Number of access code views should look at event viewer codes viewed

service-admin/web/templates/result_code.partial.gohtml
https://opgtransform.atlassian.net/browse/UML-2778
Fixes UML-2778
~* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)~
~* [ ] I have run an accessibility tool on any pages I have made changes to …
=> UML-2778: show not applicable in email row when added lpa is deleted

.github/workflows/_build-and-push.yml
fix missing trivy file scans when unit tests fail
try the newish outcome syntax.
NA
=> fix missing trivy sarif file when step fails due to unit tests

terraform/environment/cloudwatch_alarms.tf
We still have a couple of lingering api 5xx errors that need fixing so lets make alarms less sesnsitive for now
Make alarms less sensitive on provisio that we examine what the remaining 5xx occasioanl errors are so that our channel doesn't get bombarded but that we are still looking to fix the underlying issues
NA
=> tweak for api alarms to make them less sensitive for now

service-api/app/features/context/Acceptance/AccountContext.php, service-api/app/features/context/Integration/AccountContext.php, service-api/app/src/App/src/DataAccess/DynamoDb/ActorUsers.php, service-api/app/src/App/src/DataAccess/Repository/ActorUsersInterface.php, service-api/app/src/App/src/Service/User/UserService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/ActorUsersTest.php, service-api/app/test/AppTest/Service/User/UserServiceTest.php
Verify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow, typically at least 13
Fixes UML-2467
Increase the work factor for the PHP password hashing and implement a technique for updating users stored passwords to the new hashing scheme when they successfully login.
Turns out that PHPs standard hashing option is for a work factor of 10. 
* I have run an …
=> Uml 2467 improve password hashing

renovate.json
https://github.com/renovatebot/renovate/discussions/13637?sort=top
To fix renovate issues with PHP 8.2 being used despite our lock files saying 8.1 (!?)
* …
=> Contrain renovate so that it does not use PHP 8.2

service-api/app/composer.json, service-api/app/composer.lock, service-api/docker/app/Dockerfile, service-front/app/composer.json, service-front/app/composer.lock, service-front/docker/app/Dockerfile
update composer dependencies and pin docker to specific version
Fixes UML-2868
Let renovate do it's thing and update our dockerfiles so we don't get weird bugs which aren't caused by a PR. We will likely have to update the package version manually though.. we will find out on next renovate upgrade.
NA
=> UML-2868 update composer dependencies and pin docker to specific version

service-api/app/src/App/src/Handler/AccessForAllLpaValidationHandler.php
Postcode is an optional request parameter yet this was mistakenly added as a required.
Fixes UML-2873
=> Postcode is optional

service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php, service-api/app/src/App/src/Service/ActorCodes/CodeValidationStrategyInterface.php, service-api/app/src/App/src/Service/ActorCodes/Validation/CodesApiValidationStrategy.php, service-api/app/src/App/src/Service/ActorCodes/Validation/DynamoCodeValidationStrategy.php, service-api/app/src/App/src/Service/Lpa/LpaService.php, service-api/app/src/App/src/Service/Lpa/ResolveActor.php, service-api/app/test/AppTest/Service/ActorCodes/ActorCodeServiceTest.php, service-api/app/test/AppTest/Service/ActorCodes/Validation/CodesApiValidationStrategyTest.php, service-api/app/test/AppTest/Service/ActorCodes/Validation/DynamoCodeValidationStrategyTest.php, service-api/app/test/AppTest/Service/Lpa/LpaServiceTest.php, service-api/app/test/AppTest/Service/Lpa/ResolveActorTest.php
Fixes UML-2851
Ensures all usages of ResolveActor use an integer for ActorID
Converting a dynamic codebase to static is tricksy.
=> Uml 2851 change id to be integer

docker-compose.dependencies.yml, mock-integrations/nginx.conf, service-api/seeding/seeding_lpa_codes.json
Mock api was not working for lpa lambda requests
Nginx redirects configuration not correct.
=> Fix mock environment

terraform/environment/api_ecs.tf
Allow the API task role to execute-api:Invoke on the Instructions and Preferences API gateway.
Fixes UML-2913
Add an extra statement to the `api_permissions_role` resource.
=> UML-2913 Allow API to access I&P API gateway

mock-integrations/opg-data-lpa/mock-openapi.yaml, service-front/app/src/Common/src/Entity/Lpa.php, service-front/app/src/Common/src/Service/Lpa/Factory/Sirius.php, service-front/app/test/CommonTest/Service/Lpa/ParseLpaDataTest.php, service-front/app/test/CommonTest/Service/Lpa/SiriusLpaFactoryTest.php, service-front/app/test/fixtures/full_example.json, service-front/app/test/fixtures/simple_example.json
Severance warning attribute added.
Relates to  UML-2794  and UML-2830
*~ [ ] I have added relevant logging with appropriate levels to my code~
* ~[ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* ~[ ] I have added welsh translation tags and updated translation files~
* ~[ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found~
* ~[ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made~
=> Severance warning attribute

.github/workflows/_run-behat-tests.yml
Screenshots of failed tests not saved after failures in behat smoke tests.
=> Ensure test screenshots always get uploaded

service-front/app/src/Common/templates/partials/lpa-summary-details/lpa-details.html.twig
https://opgtransform.atlassian.net/browse/UML-2918
UML-2918
Removes special handling of LPAs older than 2019 as it's no longer required
* ~[ ] I have added relevant logging with appropriate levels to my code~
* ~[ ] New event_codes have been documented on the [wiki page]~(https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)~
* ~[ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* ~[ ] I have added tests to prove my work~
* ~[ ] I have added welsh translation tags and updated translation files~
* ~[ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found~
* ~[ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow …
=> UML-2969: Remove always-on severance warning for older lpas

service-admin/.idea/runConfigurations/Admin_Service.xml, service-admin/README.md, service-admin/internal/server/data/statistics.go, service-admin/internal/server/data/statistics_test.go, service-admin/internal/server/handlers/stats.go, service-admin/web/templates/stats.page.gohtml
- Adds column for "three months previous" to admin stats page
Fixes UML-2806
Adapted existing code to add a '3 months ago' a column.
No readme to build or run the Service Admin. This slowed down setting up.
~* [ ] New event_codes have been documented on the [wiki page]~~(https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)~
~* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found~
~* [ ] I have notified the Interaction Designer of any content changes so that …
=> UML 2806 - Add last three months to admin stats page

scripts/pipeline/post_release_slack_notification/post_release_slack_notification.py
Fixes broken admin link in slack notification
=> Remove /home from admin service url.

terraform/environment/actor_ecs.tf, terraform/environment/admin_ecs.tf, terraform/environment/api_ecs.tf, terraform/environment/ecs_cluster.tf, terraform/environment/locals.tf, terraform/environment/main.tf, terraform/environment/modules/iam/iam_ecs_execution_role.tf, terraform/environment/modules/iam/iam_ecs_task_roles.tf, terraform/environment/modules/iam/outputs.tf, terraform/environment/modules/iam/variables.tf, terraform/environment/pdf_ecs.tf, terraform/environment/viewer_ecs.tf
Move the ECS IAM roles from being environment specific to being global in preparation for changes to allow Use to run in multiple regions.
Fixes UML-3024
Create IAM module that is called only once.
=> UML-3024 Move IAM roles to global config

service-api/docker/app/Dockerfile, service-front/docker/app/Dockerfile
Curl is breaking in our images as we erroneously still upgrade it when we don't need to. Also removed the libxml upgrade as upgrades need not persist when the image version is bumped (they'll be included)
* I have notified the Interaction Designer of any content changes so that …
=> Remove curl and libxml upgrade

service-api/docker/app/fpm-pool.ini, service-api/docker/web/Dockerfile, service-front/docker/app/Dockerfile, service-front/docker/app/fpm-pool.ini, terraform/environment/actor_ecs.tf, terraform/environment/api_ecs.tf
Increase the worker pool size from 4 to 25 in PHP.
Fixes UML-3087
Set the pool size to be an environment variable and set the env variable to have a size of 25.
=> UML-3087 Increase PHP pool size 

terraform/environment/dynamodb.tf, terraform/environment/locals.tf, terraform/environment/region.tf, terraform/environment/region/actor_ecs.tf, terraform/environment/region/admin_ecs.tf, terraform/environment/region/api_ecs.tf, terraform/environment/region/locals.tf, terraform/environment/region/pdf_ecs.tf, terraform/environment/region/variables.tf, terraform/environment/region/viewer_ecs.tf, terraform/environment/terraform.tfvars.json
Use Global DynamoDB tables
Fixes UML-3114
Enable streaming on the DynamoDB and create a replica for each non-primary region.
=> UML-3114 Use global DynamoDB tables

.github/workflows/path-to-live.yml
Prevent other pull requests from overwriting changes to Terraform shared / account
Fixes UML-3146
Disable applying the Terraform shared / account during the PR workflow and do only a plan. Also, temporarily disabled in (Pre-)production to allow this PR to be merged.
=> UML-3146 Disable apply shared TF in PR workflow

.github/workflows/pull-request-path.yml
Create ephemeral environments when a PR is raised. Currently, one is created on pushing to a non-main branch. This will also give each ephemeral environment a unique name based on its PR number.
Fixes UML-3040
Change Github Workflow to run on PR instead of Push. Use common OPG reusable workflow to generate environment name.
=> UML-3040 Create ephemeral environments when PR is raised

terraform/account/region.tf, terraform/account/region/cloudwatch.tf, terraform/environment/shared_data_sources.tf, terraform/environment/terraform.tf
Enable Terraform account level resources in eu-west-2 for all environments. This is required to continue developing the environment Terraform code for multi-region.
Fixes UML-3155
Add a region stanza for eu_west_2 in account Terraform.
=> UML-3155 Enable account resources in eu-west-2

Makefile, service-front/app/config/routes.php, service-front/app/src/Actor/src/Handler/OneLoginCallbackHandler.php
This endpoint will handle end user requests upon return from One Login. At this stage it will return a dummy /  “hello world” response. This enables testing of the end to end control. 
Fixes UML-3102
Going to need a rework of the smoke tests or implementation of alternative ui/acceptance testing for the end to end part.
* I have run an accessibility tool on any pages I have made …
=> Endpoint to handle callback from OneLogin

service-admin/.vscode/launch.json, service-admin/README.md
_Hyphens no long allowed in AWS secrets (this issue affects for local running only)_
_Use word instead of hyphen_
=> replace no longer allowed hyphens with word

terraform/environment/region/api_ecs.tf
Allow access to Redis from the api-app
Fixes UML-3204
Add a new security group rule to the Elasticache security group to allow network access from the api-app containers.
=> UML-3204: Allow access to Redis from API

docker-compose.dependencies.yml
When the codes lambdas were updated the Dockerfile name changed. 
This updates UMLPA locally to point at the local test helper dockerfile.
=> Point at new location of the Dockerfile in codes repo.

.github/workflows/_slack-notification.yml
Include information about the pipeline triggering commit in Slack messages. Currently, it only shows the merge commit (i.e. Merge X into Y)
Fixes UML-3188
Use -2 commit for the message rather than -1.
=> UML-3188: Fix commit messages for pipeline

terraform/environment/region/actor_load_balancer.tf, terraform/environment/region/admin_load_balancer.tf, terraform/environment/region/viewer_load_balancer.tf
Add automatic response to AWS Shield in COUNT mode. This will be changed to BLOCK mode in the future after testing.
Fixes UML-2353
=> UML-2353: Add Automatic Response to Shield - COUNT mode

terraform/account/region.tf
Enable the account Terraform module in eu-west-2 for development environments
Fixes UML-3155
=> UML-3155 Enable development eu_west_2 account

terraform/account/kms.tf, terraform/account/region/cloudwatch_alarms.tf, terraform/account/region/lambda_functions.tf, terraform/account/region/modules/s3_bucket/main.tf, terraform/account/region/modules/s3_bucket/variables.tf, terraform/account/region/s3_lb_access_logs.tf, terraform/account/region/vpc_flowlogs.tf, terraform/environment/region/data_sources.tf, terraform/environment/region/ship_to_metrics.tf
Various fixes to ensure resource names are unique and can be created in both eu-west-1 and eu-west-2.
Fixes UML-3155
Because we are reusing resource names, the moved {} block cannot be used so the state needs to be manually updated with rm and import commands
tf state rm module.eu_west_1.aws_s3_bucket.access_log
tf import "module.eu_west_1.aws_s3_bucket.old_access_log[0]" opg-ual-[ACCOUNT NAME]-lb-access-logs
tf state rm module.eu_west_1.aws_cloudwatch_log_group.vpc_flow_logs
tf import "module.eu_west_1.aws_cloudwatch_log_group.old_vpc_flow_logs[0]" vpc_flow_logs
tf state rm "module.eu_west_1.module.clsf_to_sqs[0].aws_cloudwatch_log_group.lambda_function"
tf state rm "module.eu_west_1.module.ship-to-opg-metrics[0].aws_cloudwatch_log_group.lambda_function"
_Any tips and tricks, blog posts …
=> UML-3155 Fixes for multi-region account Terraform

terraform/account/region/s3_lb_access_logs.tf
Add an explicit provider for aws_s3_bucket_ownership_controls.access_log
Fixes UML-3155
=> UML-3155 Add explicit provider for S3 resource

service-api/app/config/autoload/envs.global.php, service-api/app/features/bootstrap/config.php, service-api/app/src/App/src/DataAccess/ApiGateway/RequestSignerFactory.php, service-api/app/test/BehatTest/DataAccess/ApiGateway/PactLpasFactory.php, service-front/app/config/autoload/envs.global.php
Remove hardcoded eu-west-1 references from applications.
Fixes UML-3177
Change the config to load the region name from the ECS-supplied AWS_REGION environment variable instead of being hardcoded to 'eu-west-1'.
=> UML-3177 Remove hardcoded region from applications

docker-compose.yml, service-front/app/src/Actor/templates/actor/activation-key-request-received.html.twig, service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig, service-front/app/src/Actor/templates/actor/already-requested-activation-key.html.twig, service-front/app/src/Actor/templates/actor/cannot-find-lpa.html.twig, service-front/app/src/Actor/templates/actor/check-lpa.html.twig, service-front/app/src/Actor/templates/actor/confirm-lpa-for-key-request.html.twig, service-front/app/src/Actor/templates/actor/confirm-remove-lpa.html.twig, service-front/app/src/Actor/templates/actor/request-activation-key/before-requesting-activation-key-info.html.twig, service-front/app/src/Actor/templates/actor/send-activation-key-confirmation.html.twig
Fix spacing between buttons on all pages where there are 2 buttons next to each other ” Spacing is too narrow.
A clone of one ticket that only addressed one button. 
see attachment for where the problem has occurred elsewhere. 
acceptance criteria - please list all pages that have 2 buttons and then check they all have the appropriate space. 
[Team UaL Miro board](https://miro.com/app/board/uXjVOjVLfTY=/?moveToWidget=3458764570121456246&cot=14)  this is the page where @Sarah Mills has put all the pages. search for service flow if link doesn’t go to the right place.
Fixes UML-3223
~* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Underst …
=> UML 3223 fix all multi-button spacing

service-admin/.idea/runConfigurations/Admin_Service.xml
_fix aws keys for admin portal running locally ( hyphen is no longer allowed as a key)_
_Updated in Goland_
=> fix aws keys for admin portal local running

terraform/account/locals.tf, terraform/account/region.tf, terraform/account/region/workspace_cleanup.tf, terraform/account/terraform.tfvars.json
Add an option to enable eu-west-2 in the account terraform. 
Fixes UML-3108
=> UML-3108 Add option to enable eu-west-2

scripts/modify_emails.py
Python script to preventing email addresses turning into links when sending them on Notify. 
Achieves this by adding a zero-width space `&#8203;` before each character.
Takes a csv file with a list of email addresses and outputs a file with the original email list and the modified emails. 
Fixes UML-3208
=> UML-3208 script to preventing email addresses turning into links

terraform/environment/region/actor_load_balancer.tf, terraform/environment/region/viewer_load_balancer.tf
Change the `aws_shield_application_layer_automatic_response` resources from COUNT to BLOCK now that we've established that no legitimate traffic will be affected by it.
Fixes UML-2353
=> UML-2353 Change Application layer to block

terraform/account/region/cloudwatch_alarms.tf, terraform/account/terraform.tfvars.json
Enable account level resources in eu-west-2 for production. This will allow (scaled to zero) resources to be created in eu-west-2 in a different PR.
Fixes UML-3269
Switch flag from false to true.
=> UML-3269 Enable prod eu-west-2 for account level resources

terraform/environment/region/dns.tf, terraform/environment/region/modules/dns/main.tf, terraform/environment/region/modules/dns/variables.tf
Update Terraform DNS module with SPF/DMARC records. Block emails being sent from Use / View domains.
Fixes UML-3281
Add a boolean input var to DNS module and create SPF / DMARC records blocking all emails from being sent if the variable is set to true.
=> LPAL-3281 Update TF DNS module with SPF/DMARC records

terraform/account/terraform.tfvars.json
Enable eu-west-2 account-level resources in preproduction for subsequent PR to enable environment-level resources.
Fixes UML-2547
=> UML-2547 Enable account eu-west-2 resources in preproduction

terraform/environment/region/modules/dns/main.tf
Do not attempt to create DMARC and SPF records in the secondary region as they cannot exist twice.
Fixes UML-2547
Add a check to the DNS module to ensure that we are in the active region before attempting to create the DNS records.
=> UML-2547 Fix attempt to create DNS records in secondary region

terraform/environment/region/waf.tf
Fix the Web ACL creation in secondary region.
Fixes UML-2547
Explicitly use aws.region provider when doing data lookup for ACL.
=> UML-2547 Fix Web ACL in secondary region

terraform/environment/terraform.tfvars.json
Make eu-west-2 the active region for preproduction.
Fixes UML-2547
Enable eu-west-2 active flag and disable eu-west-1 active flag.
=> UML-2547 Make eu-west-2 active for preproduction

.github/workflows/_run-behat-tests.yml, .github/workflows/_seed-database.yml, .github/workflows/path-to-live.yml, scripts/pipeline/set_environment_variables/set_slack_message_values.sh, terraform/environment/backup_plan.tf, terraform/environment/config_file.tf, terraform/environment/dynamodb.tf, terraform/environment/modules/iam/iam_ecs_task_roles.tf, terraform/environment/modules/iam/outputs.tf, terraform/environment/refactor.tf, terraform/environment/refactor_actor.tf, terraform/environment/region.tf, terraform/environment/region/actor_ecs.tf, terraform/environment/region/actor_load_balancer.tf, terraform/environment/region/admin_ecs.tf, terraform/environment/region/api_ecs.tf, terraform/environment/region/autoscaling.tf, terraform/environment/region/cloudwatch_alarms.tf, terraform/environment/region/dns.tf, terraform/environment/region/locals.tf, terraform/environment/region/outputs.tf, terraform/environment/region/viewer_load_balancer.tf, terraform/environment/region/waf.tf
Rename the Terraform resources to be consistent with the service name
Fixes UML-972
Rename the Terraform resources but do not change the AWS names as many AWS resources cannot be renamed and would result in resources (such as loadbalancers) being recreated. This would be far too disruptive for the gain. Use moved blocks for all renamed objects.
=> UML-972 Rename Terraform resources from Actor to Use

terraform/account/region/s3_lb_access_logs.tf
Fix to allow loadbalancers to write access logs to S3 bucket
Fixes UML-1911
Remove unnecessary condition block from IAM policy.
=> UML-1911 Allow LB to write access logs

service-front/app/config/autoload/dependencies.global.php, service-front/app/config/pipeline.php, service-front/app/config/routes.php, service-front/app/features/bootstrap/behat.config.php, service-front/app/src/Common/src/ConfigProvider.php, service-front/app/src/Common/src/Middleware/ErrorHandling/GoneHandler.php, service-front/app/src/Common/src/Middleware/ErrorHandling/GoneHandlerFactory.php, service-front/app/src/Common/templates/error/410.html.twig, service-front/app/test/CommonTest/Middleware/ErrorHandling/GoneHandlerFactoryTest.php, service-front/app/test/CommonTest/Middleware/ErrorHandling/GoneHandlerTest.php
Password reset form needs to be 410
AC:
Following URLs need to 410
`/reset-password` 
`/verify-new-email`
content taken from 404 page
behind feature flag `ALLOW_GOV_ONE_LOGIN`
Fixes [UML-3271](https://opgtransform.atlassian.net/jira/software/c/projects/LPA/boards/149?selectedIssue=UML-3273)
* ~[ ] I have added relevant logging with appropriate levels to my code~
* ~[ ] New event_codes have been documented on the [wiki page]~~(https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)~
*~ [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* ~[ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found~
* ~[ ] I have notified the Interaction Designer of any content changes so …
=> UML-3271 Password reset form need to 410

.github/workflows/_build-and-push.yml, .github/workflows/_codecov.yml, .github/workflows/_node-build.yml, .github/workflows/_run-behat-tests.yml, .github/workflows/_run-terraform.yml, .github/workflows/_seed-database.yml, .github/workflows/_slack-notification.yml, .github/workflows/path-to-live.yml
Revert upgrade to upload-artifact to fix Path to Live issues
Unticketed work
Roll back due to https://github.com/actions/upload-artifact/issues/478
=> Revert download and upload-artifact version upgrade

terraform/environment/region/modules/ecs_autoscaling/main.tf
Use Max CPU rather than average for autoscaling to allow faster autoscaling.
Fixes UML-3092
Change metric from Average to Max
=> UML-3092: Use max CPU rather than average for autoscaling

terraform/account/secretsmanager.tf
Unblock pipeline by adding a secret value to gov_uk_onelogin_client_id if it doesn't already exist.
Fixes UML-3359
=> UML-3359 Add default value for gov_uk_onelogin_client_id

terraform/account/region/certificate.tf
The host given for the mock one login certificate exceeded AWS' 64 character maximum in length. Changed the name to fix.
Fixes UML-3180
* The product team …
=> Fix forward overly long certificate domain name.

service-api/app/features/actor-dashboard.feature, service-api/app/features/system-message.feature, service-front/app/features/actor-dashboard.feature, service-front/app/features/context/Integration/LpaContext.php, service-front/app/features/context/UI/AccountContext.php, service-front/app/features/context/UI/LpaContext.php, service-front/app/src/Actor/src/Handler/LpaDashboardHandler.php, service-front/app/src/Actor/templates/actor/partials/service-message.html.twig, service-front/app/src/Common/src/ConfigProvider.php, service-front/app/src/Common/src/Service/SystemMessage/SystemMessageService.php, service-front/app/src/Common/src/Service/SystemMessage/SystemMessageServiceFactory.php, service-front/app/test/CommonTest/Service/SystemMessage/SystemMessageServiceFactoryTest.php, service-front/app/test/CommonTest/Service/SystemMessage/SystemMessageServiceTest.php
https://opgtransform.atlassian.net/browse/UML-2981
Shows the system message on the LPA dashboard if it's set
- Adds common SystemMessageService which talks to the API to fetch messages
- Uses this in the LPA dashboard handler to obtain messages
- Uses existing system message template with messages (if set)
=> UML-2981 Show system messages on use side

terraform/environment/region/admin_ecs.tf, terraform/environment/region/api_ecs.tf
Missing an `ssm:GetParameters` permission for API and Admin task roles.
Fixes UML-####
=> UML-2981 Add GetParameters permission

service-api/app/src/App/src/Service/SystemMessage/SystemMessage.php, service-api/app/test/AppTest/Service/SystemMessage/SystemMessageFactoryTest.php, service-api/app/test/AppTest/Service/SystemMessage/SystemMessageTest.php
Fixes UML-2982, UML-3410, UML-2981
Parameter store values must contain something, in this case we chose a single whitespace character to show that it was empty but the code failed to account for that.
* I have notified the Interaction …
=> Add trim operation to return of parameter store

service-front/app/features/actor-one-login.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Handler/AuthenticateOneLoginHandler.php
Currently, when logged in, accessing the /home path will show the button to login via One Login. This is potentially not desirable as it may give the impression that a user is not logged in when they are.
The /home url should automatically direct to /lpa/dashboard when you are logged in to remove this potential confusion.
AC
Add behat UI test to ensure the redirect occurs as intended.
Fixes UML-3400
=> uml-3400-logged in redirects to dashboard

terraform/environment/region/api_ecs.tf, terraform/environment/region/pdf_ecs.tf, terraform/environment/region/use_ecs.tf, terraform/environment/region/viewer_ecs.tf
Currently, every deploy we do resets the `desired_count` of our ECS tasks to the default, whether or not there's increased load on the service.
Fixes UML-3426
=> UML-3426: stop task desired count reset on deploy

service-api/app/config/autoload/mezzio.global.php, service-api/app/config/development.config.php.dist, service-api/app/features/bootstrap/config.php, service-api/app/features/bootstrap/container.acceptance.php, service-api/docker/app/Dockerfile, service-api/docker/app/app-php.development.ini, service-api/docker/app/app-php.ini, service-front/app/config/autoload/mezzio.global.php, service-front/app/config/development.config.php.dist, service-front/app/features/bootstrap/behat.config.php, service-front/docker/app/Dockerfile, service-front/docker/app/app-php-development.ini, service-front/docker/app/app-php.ini
Enables opcache in PHP to improve application resource usage and speed. Also enable the DI container cache.
Fixes UML-3439
=> Uml 3439 enable opcache

docker-compose.dependencies.yml, terraform/environment/terraform.tfvars.json
When deploying an environment, Use an LPA always [deploys the latest version](https://github.com/ministryofjustice/opg-use-an-lpa/blob/494b5e13fe6ec3830edebb3c77cab39c9c19b8b0/terraform/environment/terraform.tfvars.json#L313) of the PDF service. This could lead to releasing untested code, as the PDF service may update between deployments. For example, the following timeline could occur:
Preproduction deploys the latest version of the PDF service, v10.0.0
Preproduction runs smoke tests to check the deployment, ensuring v10.0.0 works
The PDF service updates to v11.0.0
Production deploys the now-latest version of the PDF service, v11.0.0
PDF generation now breaks in production, even though the pipeline passed to this point
Instead, the deployment pipeline should ensure that the same version …
=> uml-3286 Ensure same version of PDF service is deployed through pipeline

tests/smoke/context/AccountContext.php, tests/smoke/context/OneLoginImplementation.php
Currently the smoke tests do not function if the production one login environment is configured... which we need to do in our pre-production environment.
Extra checks around what page we're on and what would be the appropriate step to take.
* I have notified the Interaction Designer …
=> Ensure smoke tests work with production one login

terraform/environment/region/cloudwatch_data_protection_policy.tf
Adds a data protection policy for use, which masks email address in our cloudwatch logs
Fixes [UML-3251](https://opgtransform.atlassian.net/browse/UML-3251)
[UML-3251]: https://opgtransform.atlassian.net/browse/UML-3251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding cloudwatch data protection policy

renovate.json
_Update renovate config to be more manageable on UMLPA_
_updated config to split renovate PRs_
_renovate docs - https://docs.renovatebot.com/configuration-options/_
=> UML-3427 updated renovate config to split PRs

terraform/environment/region/cloudwatch_data_protection_policy.tf
Update Data Protection Policy with HTTPGetEmailAddress Identifier. This adds regex for email address's with a `%40` in place of `@`
Fixes UML-3251
=> Update Data Protection Policy with HTTPGetEmailAddress Identifier

service-api/app/src/App/src/Service/User/UserService.php
Found an error in testing when logging in. Fixes that.
`"Bcrypt password must not contain null character on line 494 in /app/src/App/src/DataAccess/DynamoDb/ActorUsers.php"`
Encode random bytes with bin2hex to remove null characters.
Security change in PHP introduced in 8.3.5/8.2.18/8.1.28 means null characters are not allowed.
* I have run an accessibility tool on any pages I …
=> Ensure null bytes are not passed to bcrypt.

terraform/environment/region/cloudwatch_data_protection_policy.tf
Reverting the data protection policies back to the default, including the email address identifier
Fixes UML-3251
=> Uml 3251 revert dp policy

service-front/app/languages/messages.pot, service-front/app/src/Actor/src/Form/OneLoginForm.php, service-front/app/src/Actor/src/Handler/OneLoginCallbackHandler.php, service-front/app/src/Actor/templates/actor/form-error-messages.html.twig, service-front/app/src/Actor/templates/actor/one-login.html.twig, service-front/app/src/Common/src/Service/Log/EventCodes.php, terraform/environment/region/cloudwatch_metrics.tf
In testing earlier we found that when the users session is expired, or somehow missing, when the user returns from the One Login flow they can get an unhelpful error. This should now return them to the login page to try again.
Catch the error and redirect.
=> Catch missing session on one login return

service-api/docker/web/Dockerfile, service-front/docker/web/Dockerfile
Every time docker updates it seems to re-enable the Rosetta setting on my mac which causes the web images to fail to run since confd was built with unsupported processor instructions. The fix for that is to build your own confd. 
Build confd in multistage image instead of downloading the github release (which is super old at this point anyway). Additionally remove the waitforit download as thats not even used anymore.
* I have added welsh …
=> Build confd as a part of the Dockerfiles so that we get ARCH specific versions

service-front/app/config/routes.php, service-front/app/features/actor-privacy-notice.feature, service-front/app/features/actor-terms-of-use.feature, service-front/app/features/common-language.feature, service-front/app/features/context/UI/AccountContext.php, service-front/app/src/Actor/src/Handler/CheckLpaHandler.php
Remove routes responsible for logging of PII as they're not used under One Login anyway.
Fixes UML-3251
Using conditional routing middleware.
=> Remove account creation routes under one login

service-front/docker/web/etc/confd/templates/nginx.conf
Fixes logins being broken on old devices or browsers.
Fixes UML-3581
Fix that skirts around the problem by just making our broken devices special cases. Uses nginx configuration to take all the complexity away from the app.
The problem we have is that modern versions of Chrome set a default SameSite cookie setting of "Lax" which doesn't work for us, so we set it to "None" which does. But this breaks all sorts of old iOS and MacOS Safari browsers as they don't understand "None" and assume you meant "Strict", which definitely doesn't work for us.
So the trick here is to have our app continue to assume you're all modern and set a "None" value, but then utilise an Nginx configuration to strip the SameSite configuration option from any cookies that pass through it. The Regex used is derived …
=> Utilise nginx to strip out the problematic SameSite cookie setting if the UserAgent is broken.

service-api/app/src/App/src/Service/Lpa/SiriusPerson.php, service-api/app/test/AppTest/Service/Lpa/SiriusPersonTest.php
To ensure that the returned value matches the type specified in the method definition.
Fixes UML-3657 #patch
Used PHP's [inline type casting](https://www.php.net/manual/en/language.types.type-juggling.php#language.types.typecasting)
Check the logs first 😄 Though running locally was useful to ensure it would fix the underlying issue
=> Add type coersion to SiriusPerson getters

.github/workflows/pull-request-path.yml
Prevents docker build step when a docs only update is happening
Fixes UML-3699
=> UML-3699: update PR workflow docs only path

.github/workflows/path-to-live.yml
Updates the workflow, so that if only docs are changed, the whole workflow does not need to run.
This logic matches what we currently have in the pr workflow
Fixes UML-3704
=> Update path to live workflow

scripts/pipeline/generate_trivy_report/code_scan_report.py
Hardcodes the severity in the report, as the api request sometimes gives the incorrect severity for high alerts
Fixes UML-3652
=> Update serveritys in report

docker-compose.yml, service-api/docker/web/Dockerfile, service-api/docker/web/default.conf.template, service-api/docker/web/etc/confd/conf.d/nginx.toml, service-front/docker/web/Dockerfile, service-front/docker/web/default.conf.template, service-front/docker/web/etc/confd/conf.d/nginx.toml
Removes the older confd templating of web server files and replaces with the native nginx one. Fixes UML-3774
=> Remove confd for nginx config and use native templating instead

terraform/account/kms.tf
Removes environment name from the kms key due to misalignment in envronment terraform
Fixes UML-3738
=> UML-3738: remove env name from kms

terraform/account/kms.tf
Allows the Lambda role to decrypt the KMS key
Fixes UML-3738
=> UML-3738: add role permissions to decrypt kms key

terraform/environment/lambda.tf
Allows the Lambda execution role permissions to read/write to DynamoDB. It's quite permissive at the moment, but we'll refine it later on.
Fixes UML-3731
=> UML-3731: allow lambda access to DynamoDB

.github/workflows/_build-and-push.yml, .github/workflows/_codecov.yml, .github/workflows/_node-build.yml, .github/workflows/_run-behat-tests.yml, .github/workflows/_run-terraform.yml, .github/workflows/_seed-database.yml, .github/workflows/_slack-notification.yml, .github/workflows/path-to-live.yml
_UML-3813 upload_artifact and download-artifact v3 are deprecated and will break a build. upgrade this. Using version nos instead of sha, so that renovate will maintain this_
_update version in yml_
=> UML-3813 upgrade deprecated upload_artifact and download_artifact in CI build

terraform/environment/region.tf, terraform/environment/region/api_ecs.tf, terraform/environment/region/variables.tf, terraform/environment/terraform.tfvars.json, terraform/environment/variables.tf
Request to POST to the LPA store in it's development account returned a 403 error
Fixes UML-3816
The IAM role for API ECS APP didn't have permission to execute the the POST or GET lpas endpoints for the correct account.
- add lpa store account variable
- pass to ecs api app task role
- fix http verb
=> UAL-3816 - allow ecs api-app to execute lpa-store api gateway

.idea/phpunit.xml, Makefile, docker-compose.dependencies.yml, service-api/app/src/App/src/DataAccess/DynamoDb/ViewerCodes.php, service-api/app/src/App/src/DataAccess/Repository/ViewerCodesInterface.php, service-api/app/src/App/src/Entity/Value/LpaUid.php, service-api/app/src/App/src/Enum/LpaSource.php, service-api/app/src/App/src/Service/Lpa/RemoveLpa.php, service-api/app/src/App/src/Service/ViewerCodes/ViewerCodeService.php, service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodesTest.php, service-api/app/test/AppTest/Entity/Value/LpaUidTest.php, service-api/app/test/AppTest/Service/ViewerCodes/ViewerCodeServiceTest.php
Get viewercode viewing functionality working on the actor side of the application for MLPAs
Fixes UML-3781
For now we're going to store the codes with a SiriusUid field without regard to the actual source of the LPA future work to change the field name will need planning.
=> Uml 3781 actor side code viewing

docker-compose.dependencies.yml, docker-compose.yml, service-api/docker/seeding/start.sh, service-api/seeding/dynamodb.py, service-api/seeding/put_actor_codes.py
Removes DynamoDB as a container from the stack in preference of the builtin functionality of localstack.
Make the port number options (i.e. not hardcoded) in the upstream codes service repo and then alter our urls so we can specify the port.
=> Dynamodb container removal

.github/workflows/_ecr-scanning.yml, .github/workflows/path-to-live.yml, .github/workflows/pull-request-path.yml, .github/workflows/workflow-deploy-ref-to-env.yml, terraform/environment/region/data_sources.tf
The tj-actions/files-changed action had been compromised, and tags pointed to malicious code.
Upgrade to a new tag (specifying commit sha) that doesn't have the malicious commit.
- upgrade tj-actions/files-changed to sha 2f7c5bfce28377bc069a65ba478de0a74aa0ca32 (v46.0.1)
- https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
=> upgrade tj-actions/files-changed to post incident version

localstack/localstack-init.sh
removed un-needed line which was to set environment but since we are using localstack, it is not needed
=> removed environment flag when creating lambda function

terraform/environment/lambda.tf
Gives the Event Receiver Lambda environment variables for the current environment DynamoDB tables. This will help simplify the current Lambda code.
Fixes UML-3807
=> UML-3807: add dynamodb envars to Lambda

lambda-functions/event-receiver/Dockerfile, lambda-functions/upload-statistics/Dockerfile
Forcibly updates the DNF repo to a newer version AL2023 doesn't have access to currently. Will revert back to normal means once AL2023 includes `sqlite-libs` security fix. This only includes a CVE patch and shouldn't affect the behaviour of sqlite.
Fixes UML-3942
=> UML-3942: force dnf update

service-front/app/src/Common/src/Filter/ActorViewerCodeFilter.php, service-front/app/src/Common/src/Filter/ConvertQuotesToApostrophe.php, service-front/app/src/Common/src/Filter/ShareCodeFilter.php, service-front/app/src/Common/src/Filter/StripSpacesAndHyphens.php, service-front/app/src/Viewer/src/Form/PVShareCode.php, service-front/app/src/Viewer/src/Form/ShareCode.php, service-front/app/test/CommonTest/Filter/ActorViewerCodeFilterTest.php, service-front/app/test/CommonTest/Filter/ConvertQuotesToApostropheTest.php, service-front/app/test/CommonTest/Filter/ShareCodeFilterTest.php, service-front/app/test/CommonTest/Filter/StripSpacesAndHyphensTest.php
Adds the already implemented apostrophe normalisation filter to the viewer code entry forms. 
Additionally refactors the filters away from the deprecated InputFilters abstract class to interface usage.
Fixes UML-3999
* ~I have added relevant and appropriately leveled logging, **without PII**, to my code~
* ~I have updated documentation (Confluence/GitHub wiki/tech debt doc)~
* ~I have notified the Interaction Designer of any content changes so that appropriate …
=> Uml 3999 Implement apostrophe normalisation in viewer

terraform/account/region/elasticache.tf, terraform/account/region/modules/dns_firewall/main.tf, terraform/environment/region/admin_ecs.tf, terraform/environment/region/admin_load_balancer.tf, terraform/environment/region/api_ecs.tf, terraform/environment/region/dns.tf, terraform/environment/region/mock_onelogin_ecs.tf, terraform/environment/region/mock_onelogin_load_balancer.tf, terraform/environment/region/outputs.tf, terraform/environment/region/pdf_ecs.tf, terraform/environment/region/use_ecs.tf, terraform/environment/region/use_load_balancer.tf, terraform/environment/region/viewer_ecs.tf, terraform/environment/region/viewer_load_balancer.tf
Use the network firewall in preproduction to manage egress
Fixes UML-4002
- Change switch to migrate all accounts except production
I've checked plans against account and environment level production account and confirmed no changes will be made as a result of this PR.
See ticket for confirmation
=> UML-4002 - migrate preproduction to new network

docker-compose.yml, lambda-functions/event-receiver/Dockerfile, lambda-functions/upload-statistics/Dockerfile, service-admin/Dockerfile
Fixes the CVE relating to golang's stdlib
Simple enough for the go projects but the python lambda included a binary in the base container that fails trivy validation so rip all that out and do our own image based on Amazons docs (https://docs.aws.amazon.com/lambda/latest/dg/python-image.html#python-image-clients)
* I have added relevant and appropriately leveled logging, **without PII**, to my code
* I have updated documentation (Confluence/GitHub wiki/tech debt doc)
* I have run an accessibility tool on any pages I have made …
=> Fixes for CVE-2025-47907

.github/workflows/_run-terraform.yml
Use terraform plans in the apply, makes the terraform job quicker and applies what was printed in the plan, or fails if changes occurred in between the two steps
- Move planfile to the end of the command
- extend lockfile timeout
- https://developer.hashicorp.com/terraform/cli/commands/plan
- https://developer.hashicorp.com/terraform/cli/commands/apply
=> move planfile to the end and extend lock-timeout

.github/workflows/pull-request-path.yml, .github/workflows/trigger_build, terraform/environment/region/admin_ecs.tf, terraform/environment/region/api_ecs.tf, terraform/environment/region/data_sources.tf, terraform/environment/region/use_ecs.tf, terraform/environment/region/viewer_ecs.tf
Terraform doesn't trigger a new deployment when the container version latest, because it sees no difference in the string.
Fixes UML-4088
- add aws_ecr_image data source for each image (pdf already does this)
- replace `:${var.container_version}` with the image_digest attribute for each image
- replace `:${var.admin_container_version}` with the image_digest attribute for the admin image
- use the image tag made by this run when planning a preproduction deployment
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecr_image
=> UML-4088 - use the container_version variable to lookup and use the relevant image digest
